$ErrorActionPreference='Stop';$root=$PSScriptRoot;$base='http://127.0.0.1:8090'
& (Join-Path $root 'Stop-GameBridge.ps1')
& (Join-Path $root 'Start-Prototype.ps1') -NoGodot
Invoke-RestMethod "$base/session/reset" -Method Post|Out-Null
$commit=(git -C $root rev-parse --short HEAD).Trim()
$inputs=@('look around the room','misty step to the desk','examine the painting','try to open the safe','use the crowbar to open the safe','read the note','do I have the note?','look at the dark patterns on the ground and have guillermo look at the painting','look at the dark patterns first','light a fire using your spells','the fireplace','is there a fire?','investigate the dark mark','investigate the dark mark','investigate the dark mark','carefully investigate the dark mark','move through the study door','enter the study')
$path=Join-Path $root 'eval/turn_continuity_live_replay.jsonl';if(Test-Path $path){Remove-Item -LiteralPath $path};$rows=@()
foreach($inputText in $inputs){$watch=[Diagnostics.Stopwatch]::StartNew();$response=Invoke-RestMethod "$base/action" -Method Post -ContentType 'application/json' -Body (@{text=$inputText}|ConvertTo-Json);$watch.Stop();$row=[ordered]@{turn=($rows.Count+1);running_commit=$commit;input=$inputText;status=$response.status;narration=$response.narration;roll_feedback=$(if($null-eq$response.roll_feedback){$null}else{$response.roll_feedback});location=$response.state.location.id;safe_open=$response.state.slice_state.safe_open;latency_seconds=[math]::Round($watch.Elapsed.TotalSeconds,4)};$rows+=[pscustomobject]$row;$row|ConvertTo-Json -Depth 10 -Compress|Add-Content -Encoding utf8 $path;Write-Host "$($row.turn): $inputText -> $($response.status) [$($row.location)] $($row.roll_feedback)"}
$telemetry=@(Get-Content (Join-Path $root 'eval/playtest_turns.jsonl')|Select-Object -Last $inputs.Count|ConvertFrom-Json)
$summary=[ordered]@{generated_utc=[datetime]::UtcNow.ToString('o');running_commit=$commit;turns=$rows.Count;resolved=@($rows|Where-Object status -eq resolved).Count;clarifications=@($rows|Where-Object status -eq needs_clarification).Count;engine_rejections=@($rows|Where-Object status -eq engine_rejected).Count;stale_method_leaks=@($rows|Where-Object{$_.input-eq'read the note'-and$_.narration-match'crowbar'}).Count;false_movements=@($rows|Where-Object{$_.input-in@('look around the room','misty step to the desk')-and$_.narration-match'(?i)step through|step into|enter|leave|return to'}).Count;null_render_values=@($rows|Where-Object{$_.narration-match'<null>'-or$_.roll_feedback-match'<null>'}).Count;partial_compound_executions=@($rows|Where-Object{$_.input-match'and have guillermo'-and$_.status-ne'needs_clarification'}).Count;state_query_rejections=@($rows|Where-Object{$_.input-in@('do I have the note?','is there a fire?')-and$_.status-ne'resolved'}).Count;narrator_retries=@($telemetry|Where-Object retry_occurred).Count;fallbacks=@($telemetry|Where-Object fallback_used).Count;average_live_latency_seconds=[math]::Round((($rows.latency_seconds|Measure-Object -Average).Average),4)}
$summary|ConvertTo-Json -Depth 8|Set-Content -Encoding utf8 (Join-Path $root 'eval/turn_continuity_live_replay_summary.json');$summary|ConvertTo-Json -Depth 8
