$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
$cases=@(
 'look around the room','wave at guillermo and whistle','how high is the window?','got to window and try to open it','look at the top of the desk','investigate the coarse fibers','read any letters i find','read the receipts','smell the rug','look beneath the chair','knock on the wall','stare at the bookshelves','look at the dark discoloration','investigate the dark mark','carefully investigate the dark mark',
 'look at the fireplace','investigate the dark patterns','use Detect Magic on the fireplace','touch the hearth','examine the painting','use Finesse to open the safe','read the note','is there a fire?','look through the drawers and see if there are any papers','inspect the window latch','look at the bookshelf gap','ask Guillermo about the painting','poke the desk','move through the study door','enter the study'
)
function FailureCategories($Validation){$c=@();foreach($e in @($Validation.GroundingErrors)){if($e-match'different target'){$c+='wrong_target'}elseif($e-match'unsupported physical'){$c+='unsupported_physical_object'}elseif($e-match'known context'){$c+='known_fact_repetition'}elseif($e-match'premature|overview beyond'){$c+='premature_interpretation'}elseif($e-match'dialogue|speech|knowledge|belief'){$c+='agency_or_dialogue'}elseif($e-match'classification language'){$c+='internal_language'}elseif($e-match'location|relocat|contradict|safe|door'){$c+='state_continuity'}elseif($e-match'five-sentence'){$c+='excessive_length'}elseif($e-match'repeats a sentence'){$c+='repetition'}else{$c+='other'}};@($c|Select-Object -Unique)}
$rawPath=Join-Path $root 'eval/pre_phase6_narrative_quality_raw.jsonl';if(Test-Path $rawPath){Remove-Item -LiteralPath $rawPath};$session=New-CallumStudySession $root;$rows=@();$failures=[ordered]@{}
for($i=0;$i-lt$cases.Count;$i++){$text=$cases[$i];$interpret=Invoke-SliceInterpretation $session $text -Seed (51000+$i);if($interpret.Status-ne'RESOLVED'){throw "Diagnostic did not resolve: $text ($($interpret.Status))"};$fixed=if($text-match'(?i)open the safe'){[Nullable[int]]20}elseif($text-match'^investigate|^carefully'){[Nullable[int]]$(if($i%2){8}else{18})}else{[Nullable[int]]$null};$resolved=Resolve-SliceIntent $session $interpret.Intent $fixed;if(-not$resolved.Accepted){throw "Engine rejected: $text ($($resolved.Reason))"};$watch=[Diagnostics.Stopwatch]::StartNew();$narrated=Invoke-SliceNarration $session $resolved $null 2 $root;$watch.Stop();foreach($v in @($narrated.Validations|Where-Object{-not$_.Passed})){foreach($category in @(FailureCategories $v)){if(-not$failures.Contains($category)){$failures[$category]=0};$failures[$category]++}};$sentences=@([regex]::Matches($narrated.Text,'[.!?](?:["”'']?\s|$)')).Count;$words=@([regex]::Matches($narrated.Text,"\b[\p{L}\p{N}'’-]+\b")).Count;$opening=([regex]::Match($narrated.Text,'^(?:You\s+)?([\p{L}]+)').Groups[1].Value.ToLowerInvariant());$atmosphere=[bool]($narrated.Text-match'(?i)rain|glass|gaslight|cold|dust|soot|paper|wood|brass|stone|wool|air|sound|click|creak|dark|shadow');$row=[ordered]@{turn=$i+1;input=$text;intent=$interpret.Intent;displayed_output=$narrated.Text;sentence_count=$sentences;word_count=$words;atmospheric_detail=$atmosphere;opening=$opening;first_pass=(-not$narrated.RetryOccurred);retry=$narrated.RetryOccurred;fallback=$narrated.FallbackUsed;prompt_characters=$narrated.PromptCharacters;latency_seconds=[math]::Round($watch.Elapsed.TotalSeconds,4);validations=$narrated.Validations};$rows+=[pscustomobject]$row;$row|ConvertTo-Json -Depth 16 -Compress|Add-Content -Encoding utf8 $rawPath;Write-Host "Depth diagnostic $($i+1)/30: $text"}
$first=@($rows|Where-Object first_pass).Count;$retry=@($rows|Where-Object retry).Count;$fallback=@($rows|Where-Object fallback).Count;$openingCounts=[ordered]@{};foreach($o in $rows.opening){if(-not$openingCounts.Contains($o)){$openingCounts[$o]=0};$openingCounts[$o]++};$summary=[ordered]@{generated_utc=[datetime]::UtcNow.ToString('o');turns=$rows.Count;average_sentences=[math]::Round((($rows.sentence_count|Measure-Object -Average).Average),2);average_words=[math]::Round((($rows.word_count|Measure-Object -Average).Average),1);atmospheric_outputs=@($rows|Where-Object atmospheric_detail).Count;first_pass=$first;first_pass_percent=[math]::Round(100*$first/$rows.Count,1);retries=$retry;retry_percent=[math]::Round(100*$retry/$rows.Count,1);fallbacks=$fallback;fallback_percent=[math]::Round(100*$fallback/$rows.Count,1);validator_failure_categories=$failures;opening_distribution=$openingCounts;average_prompt_characters=[math]::Round((($rows.prompt_characters|Measure-Object -Average).Average),1);average_latency_seconds=[math]::Round((($rows.latency_seconds|Measure-Object -Average).Average),4)};$summary|ConvertTo-Json -Depth 10|Set-Content -Encoding utf8 (Join-Path $root 'eval/pre_phase6_narrative_quality_summary.json');$summary|ConvertTo-Json -Depth 10
