$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
function DirectIntent([string]$Action,[string]$Target){[pscustomobject]@{Actor='Armand';Action=$Action;Target=$Target;Method=$null;Area=$null;Spell=$null;RawInput='gate setup'}}
function Context([string]$Setup){$s=New-CallumStudySession $root;switch($Setup){blood{Resolve-SliceIntent $s (DirectIntent examine rug) 11|Out-Null}scorch{Resolve-SliceIntent $s (DirectIntent examine fireplace) 11|Out-Null}both{Resolve-SliceIntent $s (DirectIntent examine rug) 11|Out-Null;Resolve-SliceIntent $s (DirectIntent examine fireplace) 11|Out-Null}gap{Resolve-SliceIntent $s (DirectIntent examine bookshelves)|Out-Null}recent{$s.RecentReferents=@('writing_desk')}safe{Resolve-SliceIntent $s (DirectIntent examine large_painting)|Out-Null}};Get-SliceInterpretationContext $s}
function GateCase([string]$Text,[string]$Action,[string]$Target,[string]$Setup='default',[string]$Actor='armand',[string]$Spell=$null,[string]$PurposeLike=$null,[string]$Status='RESOLVED'){[pscustomobject]@{text=$Text;action=$Action;target=$Target;setup=$Setup;actor=$Actor;spell=$Spell;purpose=$PurposeLike;status=$Status}}
$cases=@(
 GateCase 'look at desk' examine writing_desk; GateCase 'inspect the writing desk carefully' examine writing_desk; GateCase 'search the table' search writing_desk; GateCase 'look under the desk' examine writing_desk;
 GateCase 'move the rug' manipulate rug; GateCase 'lift the rug' manipulate rug; GateCase 'pull the rug aside' manipulate rug; GateCase 'move the rug to examine beneath it' manipulate rug default armand $null 'underneath';
 GateCase 'misty step to the desk' cast writing_desk default armand misty_step; GateCase 'teleport beside the desk with Misty Step' cast writing_desk default armand misty_step; GateCase 'use Detect Magic on the fireplace' cast fireplace default armand detect_magic; GateCase 'cast Darkness over the doorway' cast study_door default armand darkness;
 GateCase 'look at the dark mark' examine bloodstain blood; GateCase 'inspect the stain' examine bloodstain blood; GateCase 'investigate the discoloration' investigate bloodstain blood; GateCase 'examine the mark on the floor' examine bloodstain blood;
 GateCase 'look at the scorch marks' examine scorch_marks scorch; GateCase 'check whether the scorch marks came from ordinary fire' examine scorch_marks scorch armand $null 'ordinary fire'; GateCase 'study the marks by the hearth' examine scorch_marks scorch; GateCase 'inspect the dark marks' $null $null both armand $null $null NEEDS_CLARIFICATION;
 GateCase 'inspect the bookcase' examine bookshelves; GateCase 'search the shelves' search bookshelves; GateCase 'look at the empty gap' examine bookshelf_gap gap; GateCase 'look for the book that would fit that gap' examine bookshelf_gap gap armand $null 'book'; GateCase 'check the shelf wear' examine bookshelf_gap gap armand $null 'wear';
 GateCase 'read correspondence' read correspondence; GateCase 'read the receipts' read receipt; GateCase 'look at the receipts and see where Callum has been' examine receipt default armand $null 'whereabouts'; GateCase 'check the receipts for addresses' examine receipt default armand $null 'addresses';
 GateCase 'send Guillermo to investigate the bookcase' investigate bookshelves default guillermo; GateCase 'have Guillermo examine the shelves' examine bookshelves default guillermo; GateCase 'tell Guillermo to check the desk' examine writing_desk default guillermo; GateCase 'ask Guillermo what he thinks' speak guillermo;
 GateCase 'inspect it' examine writing_desk recent; GateCase 'look underneath it' examine writing_desk recent; GateCase 'poke the fireplace' manipulate fireplace; GateCase 'peer behind the painting' examine large_painting; GateCase 'rifle through the receipts' search receipt; GateCase 'inspect the safe dial' $null $null default armand $null $null UNRECOGNIZED; GateCase 'inspect the safe dial' examine safe_dial safe
)
$out=Join-Path $root 'eval/intent_model_gate_raw.jsonl';if(Test-Path $out){Remove-Item -LiteralPath $out}
$counts=[ordered]@{actor=0;action=0;target=0;purpose=0;clarification=0;hidden_leakage=0;wrong_target=0;status=0};$latencies=@();$rows=@()
for($i=0;$i-lt$cases.Count;$i++){$case=$cases[$i];$ctx=Context $case.setup;$r=Invoke-IntentInterpretation $case.text $ctx -Seed (33000+$i);$latencies+=[double]$r.ElapsedSeconds;$fails=[Collections.Generic.List[string]]::new();if($r.Status-ne$case.status){$fails.Add('status');$counts.status++};if($case.status-eq'RESOLVED'-and$r.Status-eq'RESOLVED'){if($r.Intent.actor-ne$case.actor){$fails.Add('actor');$counts.actor++};if($r.Intent.action-ne$case.action){$fails.Add('action');$counts.action++};if($r.Intent.target-ne$case.target){$fails.Add('target');$counts.target++;$counts.wrong_target++};if($case.purpose-and([string]$r.Intent.purpose-notmatch[regex]::Escape($case.purpose))){$fails.Add('purpose');$counts.purpose++}}elseif($case.status-eq'NEEDS_CLARIFICATION'-and$r.Status-ne'NEEDS_CLARIFICATION'){$counts.clarification++};if($case.status-eq'UNRECOGNIZED'-and$r.Status-eq'RESOLVED'-and$r.Intent.target-eq'safe_dial'){$fails.Add('hidden_leakage');$counts.hidden_leakage++};$row=[ordered]@{case=($i+1);input=$case.text;expected=[ordered]@{status=$case.status;actor=$case.actor;action=$case.action;target=$case.target;purpose_contains=$case.purpose};actual_status=$r.Status;intent=$r.Intent;failures=@($fails);raw_model_output=$r.RawModelStructuredOutput;latency_seconds=[math]::Round([double]$r.ElapsedSeconds,4)};$rows+=[pscustomobject]$row;$row|ConvertTo-Json -Depth 12 -Compress|Add-Content -Encoding utf8 $out;Write-Host "Model gate $($i+1)/$($cases.Count): $($case.text) [$(@($fails)-join',')]"}
$failed=@($rows|Where-Object{@($_.failures).Count}).Count;$summary=[ordered]@{generated_utc=[datetime]::UtcNow.ToString('o');cases=$cases.Count;passed=($cases.Count-$failed);failed=$failed;failure_categories=$counts;average_latency_seconds=[math]::Round((($latencies|Measure-Object -Average).Average),4);maximum_latency_seconds=[math]::Round((($latencies|Measure-Object -Maximum).Maximum),4)};$summary|ConvertTo-Json -Depth 8|Set-Content -Encoding utf8 (Join-Path $root 'eval/intent_model_gate_summary.json');$summary|ConvertTo-Json -Depth 8
