[CmdletBinding()]param([switch]$Force)
$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/GameState.psm1') -Force
Import-Module (Join-Path $root 'src/InterpreterContext.psm1') -Force
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
function New-GateState([switch]$DuplicateDesk){
 $s=New-GameState;Add-LocationState -State $s -Id study -VisibleObjects @('desk_01','cabinet_01','window_01','brass_key','locked_door','fireplace_01','vault_01') -Exits @('hallway') -DisplayName 'Victorian study';Add-LocationState -State $s -Id hallway -VisibleObjects @() -Exits @('study') -DisplayName 'hallway'
 Add-ItemState -State $s -Id desk_01 -Location study -Owner $null -DisplayName 'writing desk' -Aliases @('desk','writing desk') -InteractableParts @('underneath','inside','on_top');Add-ItemState -State $s -Id cabinet_01 -Location study -Owner $null -DisplayName 'cabinet' -Aliases @('cabinet') -InteractableParts @('inside','behind','on_top');Add-ItemState -State $s -Id window_01 -Location study -Owner $null -DisplayName 'window' -Aliases @('window');Add-ItemState -State $s -Id brass_key -Location study -Owner $null -DisplayName 'brass key' -Aliases @('key','brass key');Add-ItemState -State $s -Id locked_door -Location study -Owner $null -DisplayName 'locked door' -Aliases @('door','locked door');Add-ItemState -State $s -Id fireplace_01 -Location study -Owner $null -DisplayName 'fireplace' -Aliases @('fireplace','grate');Add-ItemState -State $s -Id vault_01 -Location study -Owner $null -DisplayName 'locked vault' -Aliases @('vault','locked vault');Add-ItemState -State $s -Id crowbar -Location inventory -Owner Armand -DisplayName 'crowbar' -Aliases @('crowbar')
 Add-ItemState -State $s -Id secret_weapon -Location study -Owner $null -DisplayName 'murder weapon';Add-NpcState -State $s -Id guard -Location study -DisplayName 'guard' -Aliases @('guard','constable');Add-NpcState -State $s -Id hidden_lord -Location cellar -DisplayName 'Lord Blackwood'
 if($DuplicateDesk){$s.Locations.study.VisibleObjects+=@('desk_02');Add-ItemState -State $s -Id desk_02 -Location study -Owner $null -DisplayName 'oak desk' -Aliases @('desk','oak desk')};$s.Player.Location='study';$s.Guillermo.Location='study';$s
}
$cases=@(Get-Content -Raw (Join-Path $root 'tests/gate2_cases.json')|ConvertFrom-Json);$log=Join-Path $root 'eval/gate2_real_model_raw.jsonl';if($Force-and(Test-Path $log)){Remove-Item -LiteralPath $log};$done=@{};if(Test-Path $log){Get-Content $log|ForEach-Object{$x=$_|ConvertFrom-Json;$done[$x.id]=$true}}
$i=0;foreach($case in $cases){$i++;if($done.ContainsKey($case.id)){continue};$state=New-GateState -DuplicateDesk:($case.context-eq'duplicate_desks');$recent=switch($case.context){'single_recent'{@('desk_01')};'ambiguous_recent'{@('desk_01','cabinet_01')};default{@()}};$context=New-InterpretationContext $state $recent;Write-Host "GATE2 $i/30 $($case.id)";$result=Invoke-IntentInterpretation -PlayerText $case.input -Context $context -Seed (8500+$i);[ordered]@{id=$case.id;input=$case.input;context=$case.context;expected_status=$case.status;expected_intent=$case.intent;actual_status=$result.Status;actual_intent=$result.Intent;clarification=$result.Clarification;reason=$result.Reason;raw_model_structured_output=$result.RawModelStructuredOutput;elapsed_seconds=[math]::Round($result.ElapsedSeconds,3)}|ConvertTo-Json -Depth 12 -Compress|Add-Content -Encoding utf8 $log}
Write-Host 'Gate 2 real-model run complete.'
