$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/GameState.psm1') -Force
Import-Module (Join-Path $root 'src/InterpreterContext.psm1') -Force
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
Import-Module (Join-Path $root 'src/IntentSchema.psm1') -Force
Import-Module (Join-Path $root 'src/CoreEngine.psm1') -Force
Import-Module (Join-Path $root 'src/GameState.psm1') -Force
Import-Module (Join-Path $root 'src/NarrationPrompt.psm1') -Force
Import-Module (Join-Path $root 'src/NarrationPacket.psm1') -Force
Import-Module (Join-Path $root 'src/NarratorHandoff.psm1') -Force
Import-Module (Join-Path $root 'src/CommaHarness.psm1') -Force
$state=New-GameState;Add-LocationState -State $state -Id study -VisibleObjects @('desk_01','fireplace_01','brass_key') -Exits @('hallway') -DisplayName 'Victorian study';Add-LocationState -State $state -Id hallway -DisplayName hallway;Add-ItemState -State $state -Id desk_01 -Location study -Owner $null -DisplayName 'writing desk' -Aliases @('desk','writing desk') -InteractableParts @('underneath');Add-ItemState -State $state -Id fireplace_01 -Location study -Owner $null -DisplayName fireplace -Aliases @('fireplace');Add-ItemState -State $state -Id brass_key -Location hook -Owner $null -DisplayName 'brass key' -Aliases @('key','brass key');$state.Player.Location='study';$state.Guillermo.Location='study'
$context=New-InterpretationContext $state;$debug=Join-Path $root 'eval/phase4_interpreter_debug.jsonl';if(Test-Path $debug){Remove-Item $debug}
$armandInterpretation=Invoke-IntentInterpretation -PlayerText 'Look beneath the desk.' -Context $context -DebugLogPath $debug -Seed 9101
$guillermoInterpretation=Invoke-IntentInterpretation -PlayerText 'Have Guillermo steal the key.' -Context $context -DebugLogPath $debug -Seed 9102
if($armandInterpretation.Status-ne'RESOLVED'-or$guillermoInterpretation.Status-ne'RESOLVED'){throw 'End-to-end interpretation did not resolve.'}
$armandIntent=ConvertTo-EngineIntent $armandInterpretation.Intent;$guillermoIntent=ConvertTo-EngineIntent $guillermoInterpretation.Intent
$armand=Resolve-StructuredIntent -State $state -Intent $armandIntent -Skill Investigation -DC 15 -FixedRoll 13 -PostActionState ([pscustomobject]@{desk_scratches_observed=$true;desk_area='underneath'}) -Events @('scratches are observed beneath the desk') -Visible @('writing desk','fireplace','brass key on hook')
$guillermo=Resolve-StructuredIntent -State $state -Intent $guillermoIntent -Skill Finesse -DC 15 -FixedRoll 4 -Mutations @([pscustomobject]@{type='transfer_item';item_id='brass_key';to='Guillermo';apply_on=@('Success','Exceptional Success')}) -PostActionState ([pscustomobject]@{brass_key_location=$state.Items.brass_key.Location;Guillermo_has_key=$state.Guillermo.Inventory.Contains('brass_key')}) -Events @('brass key rattles','Guillermo retreats') -Visible @('writing desk','fireplace','brass key on hook')
Set-EngineInterpretationDecision $armandInterpretation $true $null $debug|Out-Null;Set-EngineInterpretationDecision $guillermoInterpretation $true $null $debug|Out-Null
if($state.Items.brass_key.Owner-or$state.Guillermo.Inventory.Contains('brass_key')){throw 'Failed theft mutated key ownership.'};if(($guillermo.Handoff|ConvertTo-Json -Depth 10)-match'Guillermo steals'){throw 'Failed theft serialized as completion.'}
$examples=@(Read-NarrationExemplars (Join-Path $root 'exemplars/narration_exemplars.json') -ExpectedCount 8)+@(Read-NarrationExemplars (Join-Path $root 'exemplars/grounding_retry_exemplars.json') -ExpectedCount 3);$cfg=Get-Content -Raw (Join-Path $root 'config.json')|ConvertFrom-Json;$cfg.temperature=.15;$cfg.max_tokens=224;$cfg.stop_sequence="`nFACTS";$work=Join-Path $root 'eval/.work';New-Item -ItemType Directory -Force $work|Out-Null;$cfgPath=Join-Path $work 'phase4_narrator_config.json';$cfg|ConvertTo-Json -Depth 8|Set-Content -Encoding utf8 $cfgPath
$runs=@([pscustomobject]@{id='armand-natural-investigation';engine=$armand;interp=$armandInterpretation;location='study';seed=9201},[pscustomobject]@{id='guillermo-natural-failed-steal';engine=$guillermo;interp=$guillermoInterpretation;location='study';seed=9202});$out=@()
foreach($run in $runs){$case=Convert-HandoffToNarrationCase $run.engine.Handoff $run.location midnight rain;$packet=ConvertTo-NarrationPacket $case;$prompt=Build-NarrationPrompt $packet facts $examples;$path=Join-Path $work "$($run.id).txt";$prompt|Set-Content -NoNewline -Encoding utf8 $path;$g=Invoke-CommaGeneration $path $cfgPath -Seed $run.seed -Temperature .15 -MaxTokens 224;$n='You '+(($g.Text-replace'(?s)\s*FACTS\s*$','').TrimStart());$out+=[pscustomobject]@{id=$run.id;player_input=$run.interp.Intent.raw_input;interpretation=$run.interp;engine_intent=$run.engine.Intent;resolution=$run.engine.Resolution;handoff=$run.engine.Handoff;authoritative_key_state=$(if($run.id-like'guillermo*'){[pscustomobject]@{location=$state.Items.brass_key.Location;owner=$state.Items.brass_key.Owner;Guillermo_has_key=$state.Guillermo.Inventory.Contains('brass_key')}}else{$null});raw_narrator_completion=$g.Text;narration=$n;interpretation_seconds=$run.interp.ElapsedSeconds;narration_seconds=$g.ElapsedSeconds;gpu_active=$g.GpuActive}}
$out|ConvertTo-Json -Depth 16|Set-Content -Encoding utf8 (Join-Path $root 'eval/phase4_end_to_end_results.json');$out|ForEach-Object{Write-Host "[$($_.id)] $($_.narration)"}
