$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
Import-Module (Join-Path $root 'src/IntentSchema.psm1') -Force
$cfg=Get-Content -Raw (Join-Path $root 'bridge_config.json')|ConvertFrom-Json;$prefix="http://$($cfg.host):$($cfg.port)/";$listener=[Net.HttpListener]::new();$listener.Prefixes.Add($prefix)
try{$listener.Start()}catch{throw "Could not start game bridge at $prefix $($_.Exception.Message)"}
$pidPath=Join-Path $root 'eval/.work/game-bridge.pid';New-Item -ItemType Directory -Force (Split-Path $pidPath)|Out-Null;$PID|Set-Content -Encoding ascii $pidPath
$script:session=New-CallumStudySession $root;$telemetry=Join-Path $root $cfg.telemetry_path
function Send-Json($Context,$Value,[int]$Status=200){$json=$Value|ConvertTo-Json -Depth 20 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$Context.Response.StatusCode=$Status;$Context.Response.ContentType='application/json; charset=utf-8';$Context.Response.ContentLength64=$bytes.Length;$Context.Response.OutputStream.Write($bytes,0,$bytes.Length);$Context.Response.Close()}
function Read-Body($Request){$reader=[IO.StreamReader]::new($Request.InputStream,$Request.ContentEncoding);try{$text=$reader.ReadToEnd()}finally{$reader.Dispose()};if([string]::IsNullOrWhiteSpace($text)){return [pscustomobject]@{}};$text|ConvertFrom-Json}
function Get-NotebookSnapshot($Session){Get-PlayerFacingNotebook $Session.State}
function Get-NotebookChanges($Before,$After){$beforeJson=$Before|ConvertTo-Json -Depth 15 -Compress;$afterJson=$After|ConvertTo-Json -Depth 15 -Compress;[pscustomobject]@{changed=($beforeJson-ne$afterJson);notebook=$After}}
Write-Host "Armand game bridge ready at $prefix (PID $PID)."
try{while($listener.IsListening){$ctx=$listener.GetContext();try{$method=$ctx.Request.HttpMethod;$path=$ctx.Request.Url.AbsolutePath
 if($method-eq'GET'-and$path-eq'/health'){Send-Json $ctx ([pscustomobject]@{status='ok';session_active=($null-ne$script:session)})}
 elseif($method-eq'POST'-and$path-in@('/session/new','/session/reset')){$script:session=New-CallumStudySession $root;Send-Json $ctx (Get-SlicePlayerState $script:session)}
 elseif($method-eq'GET'-and$path-eq'/session/state'){Send-Json $ctx (Get-SlicePlayerState $script:session)}
 elseif($method-eq'GET'-and$path-eq'/notebook'){Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory'){$body=Read-Body $ctx.Request;$id=if($body.PSObject.Properties['theory_id']){$body.theory_id}else{('theory_'+[guid]::NewGuid().ToString('N').Substring(0,8))};$entry=New-NotebookTheory $script:session.State $id $body.title $body.body;Send-Json $ctx $entry 201}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory/link'){$body=Read-Body $ctx.Request;Add-NotebookTheoryLink $script:session.State $body.theory_id $body.entity_type $body.entity_id;Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/character/important'){$body=Read-Body $ctx.Request;Set-NotebookCharacterImportant $script:session.State $body.character_id ([bool]$body.important);Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/telemetry/tag'){$body=Read-Body $ctx.Request;if($body.tag-notin@($cfg.quality_tags)){throw 'Unknown quality tag.'};[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');type='quality_tag';turn_id=$body.turn_id;tag=$body.tag}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx ([pscustomobject]@{status='tagged'})}
 elseif($method-eq'POST'-and$path-eq'/action'){$turnWatch=[Diagnostics.Stopwatch]::StartNew();$turnId=[guid]::NewGuid().ToString('N');$body=Read-Body $ctx.Request;$text=[string]$body.text;$before=Get-NotebookSnapshot $script:session;$debug=Join-Path $root 'eval/slice_interpreter_debug.jsonl';$interpret=Invoke-SliceInterpretation $script:session $text -DebugLogPath $debug -Seed (11000+$script:session.State.Time.Turn)
  if($interpret.Status-ne'RESOLVED'){$turnWatch.Stop();$message=if($interpret.Status-eq'NEEDS_CLARIFICATION'){$interpret.Clarification}else{'You cannot identify a safe target for that action.'};[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;interpretation_status=$interpret.Status;resolved_actor=$null;action=$null;target=$null;purpose=$null;aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$interpret.Reason;engine_routing_family=$interpret.RoutingFamily;result_category=$interpret.OutcomeCategory;interpreter_latency_seconds=$interpret.ElapsedSeconds}|ConvertTo-Json -Depth 8 -Compress|Add-Content -Encoding utf8 $telemetry;$response=[pscustomobject]@{turn_id=$turnId;status=$interpret.Status.ToLowerInvariant();narration=$message;state=Get-SlicePlayerState $script:session};Send-Json $ctx $response;continue}
  $engineIntent=ConvertTo-EngineIntent $interpret.Intent;$resolved=Resolve-SliceIntent $script:session $engineIntent;if(-not$resolved.Accepted){Set-EngineInterpretationDecision $interpret $false $resolved.Reason $debug|Out-Null;$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;interpretation_status='ENGINE_REJECTED';resolved_actor=$interpret.Intent.actor;action=$interpret.Intent.action;target=$interpret.Intent.target;purpose=$interpret.Intent.purpose;aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$resolved.Reason;engine_routing_family=$interpret.RoutingFamily;result_category='ENGINE_REJECTED';interpreter_latency_seconds=$interpret.ElapsedSeconds;full_turn_latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Depth 8 -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx ([pscustomobject]@{turn_id=$turnId;status='engine_rejected';narration=$resolved.Reason;state=Get-SlicePlayerState $script:session});continue}
  $script:session.RecentReferents=@($interpret.Intent.target);$narrated=Invoke-SliceNarration $script:session $resolved -MaxAttempts ([int]$script:session.Content.Slice.narrator_max_attempts) -Root $root;$script:session.History.Add($narrated.Text);$after=Get-NotebookSnapshot $script:session;$delta=Get-NotebookChanges $before $after;$turnWatch.Stop();$public=Get-SlicePlayerState $script:session;$response=[pscustomobject]@{turn_id=$turnId;status='resolved';narration=$narrated.Text;location=$public.location;time=$public.time;notebook_changed=$delta.changed;new_notebook_entries=$(if($delta.changed){$after}else{$null});guillermo=$public.guillermo;slice_state=$public.slice_state;state=$public}
  [ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;interpreted_intent=$interpret.Intent;interpretation_status=$interpret.Status;resolved_actor=$interpret.Intent.actor;action=$interpret.Intent.action;target=$interpret.Intent.target;purpose=$interpret.Intent.purpose;aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$interpret.Reason;engine_routing_family=$interpret.RoutingFamily;result_category=$resolved.Classification;classification=$resolved.Classification;engine_resolution=[pscustomobject]@{accepted=$resolved.Accepted;degree=$resolved.Degree;events=$resolved.Events};notebook_changed=$delta.changed;narrator_raw_outputs=$narrated.RawOutputs;validator_attempts=$narrated.Validations;validator=$narrated.Validation;displayed_narration=$narrated.Text;retry_occurred=$narrated.RetryOccurred;fallback_used=$narrated.FallbackUsed;interpreter_latency_seconds=$interpret.ElapsedSeconds;narrator_latency_seconds=$narrated.ElapsedSeconds;full_turn_latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Depth 16 -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx $response}
 else{Send-Json $ctx ([pscustomobject]@{error='route_not_found'}) 404}
 }catch{[Console]::Error.WriteLine("Bridge request failed: $($_.Exception.Message)");try{Send-Json $ctx ([pscustomobject]@{error='request_failed'}) 400}catch{}}}}
finally{$listener.Stop();$listener.Close();if(Test-Path $pidPath){Remove-Item -LiteralPath $pidPath -Force}}
