$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
Import-Module (Join-Path $root 'src/IntentSchema.psm1') -Force
Import-Module (Join-Path $root 'src/CombatPrototype.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/HousePrototype.psm1') -Force -DisableNameChecking
$cfg=Get-Content -Raw (Join-Path $root 'bridge_config.json')|ConvertFrom-Json;$prefix="http://$($cfg.host):$($cfg.port)/";$listener=[Net.HttpListener]::new();$listener.Prefixes.Add($prefix)
try{$listener.Start()}catch{throw "Could not start game bridge at $prefix $($_.Exception.Message)"}
$pidPath=Join-Path $root 'eval/.work/game-bridge.pid';New-Item -ItemType Directory -Force (Split-Path $pidPath)|Out-Null;$PID|Set-Content -Encoding ascii $pidPath
$script:session=New-HouseSession $root;$script:combat=$null;$script:combatTutorialSeen=$false;$telemetry=Join-Path $root $cfg.telemetry_path;$combatTelemetry=Join-Path $root 'eval/combat_turns.jsonl';$houseTelemetry=Join-Path $root 'eval/house_turns.jsonl';$houseNarrationErrors=Join-Path $root 'eval/house_narration_errors.jsonl'
function Send-Json($Context,$Value,[int]$Status=200){$json=$Value|ConvertTo-Json -Depth 20 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$Context.Response.StatusCode=$Status;$Context.Response.ContentType='application/json; charset=utf-8';$Context.Response.ContentLength64=$bytes.Length;$Context.Response.OutputStream.Write($bytes,0,$bytes.Length);$Context.Response.Close()}
function Read-Body($Request){$reader=[IO.StreamReader]::new($Request.InputStream,$Request.ContentEncoding);try{$text=$reader.ReadToEnd()}finally{$reader.Dispose()};if([string]::IsNullOrWhiteSpace($text)){return [pscustomobject]@{}};$text|ConvertFrom-Json}
function Get-NotebookSnapshot($Session){Get-PlayerFacingNotebook $Session.State}
function Get-NotebookChanges($Before,$After){$beforeJson=$Before|ConvertTo-Json -Depth 15 -Compress;$afterJson=$After|ConvertTo-Json -Depth 15 -Compress;[pscustomobject]@{changed=($beforeJson-ne$afterJson);notebook=$After}}
function Get-BridgeState {$state=Get-HousePlayerState $script:session;$state|Add-Member -NotePropertyName combat -NotePropertyValue $(if($script:combat){Get-CombatPlayerState $script:combat}else{$null}) -Force;$state}
function Sync-CombatEnvironment {if(-not$script:combat){return};foreach($change in @($script:combat.room_changes)){if(-not@($script:session.PersistentEnvironment|Where-Object{$_.referent_id-eq$change.referent_id-and$_.state-eq$change.state}).Count){$script:session.PersistentEnvironment.Add($change);$script:session.ReferentStates[$change.referent_id]=$change.state};if($change.referent_id-eq'wall_safe'){$script:session.SafeDiscovered=$true}}}
Write-Host "Armand game bridge ready at $prefix (PID $PID)."
try{while($listener.IsListening){$ctx=$listener.GetContext();try{$method=$ctx.Request.HttpMethod;$path=$ctx.Request.Url.AbsolutePath
 if($method-eq'GET'-and$path-eq'/health'){Send-Json $ctx ([pscustomobject]@{status='ok';session_active=($null-ne$script:session)})}
 elseif($method-eq'POST'-and$path-in@('/session/new','/session/reset')){$script:session=New-HouseSession $root;$script:combat=$null;Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'GET'-and$path-eq'/session/state'){Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'GET'-and$path-eq'/session/save'){Send-Json $ctx ([pscustomobject]@{save=Export-HouseSave $script:session})}
 elseif($method-eq'POST'-and$path-eq'/session/load'){$body=Read-Body $ctx.Request;$script:session=Import-HouseSave $root ([string]$body.save);$script:combat=$null;Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'POST'-and$path-eq'/combat/start'){$body=Read-Body $ctx.Request;$encounter=if($body.PSObject.Properties['encounter_id']){[string]$body.encounter_id}else{'benchmark_a'};$seed=if($body.PSObject.Properties['seed']){[int]$body.seed}else{[Environment]::TickCount};$script:combat=New-CombatSession $root $encounter $seed;$script:combat.room_id=$script:session.State.Player.Location;if($script:combatTutorialSeen){Dismiss-CombatTutorial $script:combat}else{$script:combatTutorialSeen=$true};Send-Json $ctx (Get-BridgeState) 201}
 elseif($method-eq'GET'-and$path-eq'/combat/state'){Send-Json $ctx $(if($script:combat){Get-CombatPlayerState $script:combat}else{[pscustomobject]@{active=$false}})}
 elseif($method-eq'POST'-and$path-eq'/combat/tutorial/dismiss'){if($script:combat){Dismiss-CombatTutorial $script:combat};Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'POST'-and$path-eq'/combat/reaction'){$body=Read-Body $ctx.Request;$result=Invoke-CombatReaction $script:combat ([bool]$body.use);Sync-CombatEnvironment;$result.state=Get-BridgeState;Send-Json $ctx $result}
 elseif($method-eq'GET'-and$path-eq'/notebook'){Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory'){$body=Read-Body $ctx.Request;$id=if($body.PSObject.Properties['theory_id']){$body.theory_id}else{('theory_'+[guid]::NewGuid().ToString('N').Substring(0,8))};$entry=New-NotebookTheory $script:session.State $id $body.title $body.body;Send-Json $ctx $entry 201}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory/link'){$body=Read-Body $ctx.Request;Add-NotebookTheoryLink $script:session.State $body.theory_id $body.entity_type $body.entity_id;Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/character/important'){$body=Read-Body $ctx.Request;Set-NotebookCharacterImportant $script:session.State $body.character_id ([bool]$body.important);Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/telemetry/tag'){$body=Read-Body $ctx.Request;if($body.tag-notin@($cfg.quality_tags)){throw 'Unknown quality tag.'};[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');type='quality_tag';turn_id=$body.turn_id;tag=$body.tag}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx ([pscustomobject]@{status='tagged'})}
 elseif($method-eq'POST'-and$path-eq'/action'){$turnWatch=[Diagnostics.Stopwatch]::StartNew();$turnId=[guid]::NewGuid().ToString('N');$body=Read-Body $ctx.Request;$text=[string]$body.text;if($script:combat-and$script:combat.active){$result=Invoke-CombatCommand $script:combat $text;Sync-CombatEnvironment;if(-not$script:combat.active){$script:session.Encounter.resolved=$true;$script:session.Encounter.outcome=$script:combat.end_reason};if($result.PSObject.Properties['telemetry']-and$result.telemetry){$result.telemetry|ConvertTo-Json -Depth 15 -Compress|Add-Content -Encoding utf8 $combatTelemetry};$result.state=Get-BridgeState;$result|Add-Member -NotePropertyName turn_id -NotePropertyValue $turnId -Force;Send-Json $ctx $result;continue};$house=try{Invoke-HouseTurn $script:session $text -Narrate}catch{$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;location=$script:session.State.Player.Location;error=$_.Exception.Message}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $houseNarrationErrors;Send-Json $ctx ([pscustomobject]@{turn_id=$turnId;status='narration_error';narration='[DEVELOPMENT NARRATION ERROR] The resolved turn could not be rendered. See house_narration_errors.jsonl.';state=Get-BridgeState}) 500;continue};if($house.start_combat){$script:combat=New-CombatSession $root benchmark_b ([int](6000+$script:session.State.Time.Turn));$script:combat.room_id=$script:session.State.Player.Location;if($script:combatTutorialSeen){Dismiss-CombatTutorial $script:combat}else{$script:combatTutorialSeen=$true};$house.state=Get-BridgeState};$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;status=$house.status;location=$script:session.State.Player.Location;clues_added=$house.clues_added;encounter_start=$house.start_combat;latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $houseTelemetry;$house|Add-Member turn_id $turnId -Force;Send-Json $ctx $house;continue}
 else{Send-Json $ctx ([pscustomobject]@{error='route_not_found'}) 404}
 }catch{[Console]::Error.WriteLine("Bridge request failed: $($_.Exception.Message)");try{Send-Json $ctx ([pscustomobject]@{error='request_failed'}) 400}catch{}}}}
finally{$listener.Stop();$listener.Close();if(Test-Path $pidPath){Remove-Item -LiteralPath $pidPath -Force}}
