$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/IntentInterpreter.psm1') -Force
Import-Module (Join-Path $root 'src/IntentSchema.psm1') -Force
Import-Module (Join-Path $root 'src/CombatPrototype.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $root 'src/HousePrototype.psm1') -Force -DisableNameChecking
$cfg=Get-Content -Raw (Join-Path $root 'bridge_config.json')|ConvertFrom-Json;$prefix="http://$($cfg.host):$($cfg.port)/";$listener=[Net.HttpListener]::new();$listener.Prefixes.Add($prefix)
try{$listener.Start()}catch{throw "Could not start game bridge at $prefix $($_.Exception.Message)"}
$pidPath=Join-Path $root 'eval/.work/game-bridge.pid';New-Item -ItemType Directory -Force (Split-Path $pidPath)|Out-Null;$PID|Set-Content -Encoding ascii $pidPath
$script:session=New-HouseSession $root;$script:combat=$null;$script:combatTutorialSeen=$false;$telemetry=Join-Path $root $cfg.telemetry_path;$combatTelemetry=Join-Path $root 'eval/combat_turns.jsonl';$houseTelemetry=Join-Path $root 'eval/house_turns.jsonl';$houseNarrationErrors=Join-Path $root 'eval/house_narration_errors.jsonl'
function Send-Json($Context,$Value,[int]$Status=200){$json=$Value|ConvertTo-Json -Depth 20 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$Context.Response.StatusCode=$Status;$Context.Response.ContentType='application/json; charset=utf-8';$Context.Response.ContentLength64=$bytes.Length;$Context.Response.OutputStream.Write($bytes,0,$bytes.Length);$Context.Response.Close()}
function Read-Body($Request){$reader=[IO.StreamReader]::new($Request.InputStream,$Request.ContentEncoding);try{$text=$reader.ReadToEnd()}finally{$reader.Dispose()};if([string]::IsNullOrWhiteSpace($text)){return [pscustomobject]@{}};$text|ConvertFrom-Json}
function Get-NotebookSnapshot($Session){Get-PlayerFacingNotebook $Session.State}
function Get-NotebookChanges($Before,$After){$beforeJson=$Before|ConvertTo-Json -Depth 15 -Compress;$afterJson=$After|ConvertTo-Json -Depth 15 -Compress;[pscustomobject]@{changed=($beforeJson-ne$afterJson);notebook=$After}}
function Get-BridgeState {$state=Get-HousePlayerState $script:session;$state|Add-Member -NotePropertyName combat -NotePropertyValue $(if($script:combat){Get-CombatPlayerState $script:combat}else{$null}) -Force;$state}
function Sync-CombatEnvironment {if(-not$script:combat){return};foreach($change in @($script:combat.room_changes)){if(-not@($script:session.PersistentEnvironment|Where-Object{$_.referent_id-eq$change.referent_id-and$_.state-eq$change.state}).Count){$script:session.PersistentEnvironment.Add($change);$script:session.ReferentStates[$change.referent_id]=$change.state};if($change.referent_id-eq'wall_safe'){$script:session.SafeDiscovered=$true}}}
Write-Host "Armand game bridge ready at $prefix (PID $PID)."
try{while($listener.IsListening){$ctx=$listener.GetContext();try{$method=$ctx.Request.HttpMethod;$path=$ctx.Request.Url.AbsolutePath
 if($method-eq'GET'-and$path-eq'/health'){Send-Json $ctx ([pscustomobject]@{status='ok';session_active=($null-ne$script:session)})}
 elseif($method-eq'POST'-and$path-in@('/session/new','/session/reset')){$script:session=New-HouseSession $root;$script:combat=$null;Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'GET'-and$path-eq'/session/state'){Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'GET'-and$path-eq'/session/save'){Send-Json $ctx ([pscustomobject]@{save=Export-HouseSave $script:session})}
 elseif($method-eq'POST'-and$path-eq'/session/load'){$body=Read-Body $ctx.Request;$script:session=Import-HouseSave $root ([string]$body.save);$script:combat=$null;Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'POST'-and$path-eq'/combat/start'){$body=Read-Body $ctx.Request;$encounter=if($body.PSObject.Properties['encounter_id']){[string]$body.encounter_id}else{'benchmark_a'};$seed=if($body.PSObject.Properties['seed']){[int]$body.seed}else{[Environment]::TickCount};$script:combat=New-CombatSession $root $encounter $seed;$script:combat.room_id=$script:session.State.Player.Location;if($script:combatTutorialSeen){Dismiss-CombatTutorial $script:combat}else{$script:combatTutorialSeen=$true};Send-Json $ctx (Get-BridgeState) 201}
 elseif($method-eq'GET'-and$path-eq'/combat/state'){Send-Json $ctx $(if($script:combat){Get-CombatPlayerState $script:combat}else{[pscustomobject]@{active=$false}})}
 elseif($method-eq'POST'-and$path-eq'/combat/tutorial/dismiss'){if($script:combat){Dismiss-CombatTutorial $script:combat};Send-Json $ctx (Get-BridgeState)}
 elseif($method-eq'POST'-and$path-eq'/combat/reaction'){$body=Read-Body $ctx.Request;$result=Invoke-CombatReaction $script:combat ([bool]$body.use);Sync-CombatEnvironment;$result.state=Get-BridgeState;Send-Json $ctx $result}
 elseif($method-eq'GET'-and$path-eq'/notebook'){Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory'){$body=Read-Body $ctx.Request;$id=if($body.PSObject.Properties['theory_id']){$body.theory_id}else{('theory_'+[guid]::NewGuid().ToString('N').Substring(0,8))};$entry=New-NotebookTheory $script:session.State $id $body.title $body.body;Send-Json $ctx $entry 201}
 elseif($method-eq'POST'-and$path-eq'/notebook/theory/link'){$body=Read-Body $ctx.Request;Add-NotebookTheoryLink $script:session.State $body.theory_id $body.entity_type $body.entity_id;Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/notebook/character/important'){$body=Read-Body $ctx.Request;Set-NotebookCharacterImportant $script:session.State $body.character_id ([bool]$body.important);Send-Json $ctx (Get-PlayerFacingNotebook $script:session.State)}
 elseif($method-eq'POST'-and$path-eq'/telemetry/tag'){$body=Read-Body $ctx.Request;if($body.tag-notin@($cfg.quality_tags)){throw 'Unknown quality tag.'};[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');type='quality_tag';turn_id=$body.turn_id;tag=$body.tag}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx ([pscustomobject]@{status='tagged'})}
 elseif($method-eq'POST'-and$path-eq'/action'){$turnWatch=[Diagnostics.Stopwatch]::StartNew();$turnId=[guid]::NewGuid().ToString('N');$body=Read-Body $ctx.Request;$text=[string]$body.text;if($script:combat-and$script:combat.active){$result=Invoke-CombatCommand $script:combat $text;Sync-CombatEnvironment;if(-not$script:combat.active){$script:session.Encounter.resolved=$true;$script:session.Encounter.outcome=$script:combat.end_reason};if($result.PSObject.Properties['telemetry']-and$result.telemetry){$result.telemetry|ConvertTo-Json -Depth 15 -Compress|Add-Content -Encoding utf8 $combatTelemetry};$result.state=Get-BridgeState;$result|Add-Member -NotePropertyName turn_id -NotePropertyValue $turnId -Force;Send-Json $ctx $result;continue};$house=try{Invoke-HouseTurn $script:session $text -Narrate}catch{$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;location=$script:session.State.Player.Location;error=$_.Exception.Message}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $houseNarrationErrors;Send-Json $ctx ([pscustomobject]@{turn_id=$turnId;status='narration_error';narration='[DEVELOPMENT NARRATION ERROR] The resolved turn could not be rendered. See house_narration_errors.jsonl.';state=Get-BridgeState}) 500;continue};if($house.start_combat){$script:combat=New-CombatSession $root benchmark_b ([int](6000+$script:session.State.Time.Turn));$script:combat.room_id=$script:session.State.Player.Location;if($script:combatTutorialSeen){Dismiss-CombatTutorial $script:combat}else{$script:combatTutorialSeen=$true};$house.state=Get-BridgeState};$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;status=$house.status;location=$script:session.State.Player.Location;clues_added=$house.clues_added;encounter_start=$house.start_combat;latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Compress|Add-Content -Encoding utf8 $houseTelemetry;$house|Add-Member turn_id $turnId -Force;Send-Json $ctx $house;continue;$before=Get-NotebookSnapshot $script:session;$debug=Join-Path $root 'eval/slice_interpreter_debug.jsonl';$interpret=Invoke-SliceInterpretation $script:session $text -DebugLogPath $debug -Seed (11000+$script:session.State.Time.Turn)
  if($interpret.Status-ne'RESOLVED'){$turnWatch.Stop();$message=if($interpret.Status-eq'NEEDS_CLARIFICATION'){$interpret.Clarification}elseif($text-match'(?i)\b(?:cast|spell|use|light)\b'){'What do you want to use that on?'}else{'You do not see anything matching that description.'};[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;structured_intent=$interpret.Intent;interpretation_status=$interpret.Status;resolved_actor=$null;action=$null;target=$null;purpose=$null;inherited_from_pending=@($(if($interpret.PSObject.Properties['InheritedFromPending']){$interpret.InheritedFromPending}else{@()}));pending_intent_event=$(if($interpret.PSObject.Properties['PendingEvent']){$interpret.PendingEvent}else{'none'});compound_detected=$(if($interpret.PSObject.Properties['CompoundDetected']){$interpret.CompoundDetected}else{$false});aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$interpret.Reason;engine_routing_family=$interpret.RoutingFamily;result_category=$interpret.OutcomeCategory;interpreter_latency_seconds=$interpret.ElapsedSeconds}|ConvertTo-Json -Depth 8 -Compress|Add-Content -Encoding utf8 $telemetry;$response=[pscustomobject]@{turn_id=$turnId;status=$interpret.Status.ToLowerInvariant();narration=$message;state=Get-SlicePlayerState $script:session};Send-Json $ctx $response;continue}
  $engineIntent=ConvertTo-EngineIntent $interpret.Intent;$resolved=Resolve-SliceIntent $script:session $engineIntent;if(-not$resolved.Accepted){Set-EngineInterpretationDecision $interpret $false $resolved.Reason $debug|Out-Null;$turnWatch.Stop();[ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;structured_intent=$interpret.Intent;interpretation_status='ENGINE_REJECTED';resolved_actor=$interpret.Intent.actor;action=$interpret.Intent.action;target=$interpret.Intent.target;purpose=$interpret.Intent.purpose;inherited_from_pending=@($(if($interpret.PSObject.Properties['InheritedFromPending']){$interpret.InheritedFromPending}else{@()}));pending_intent_event=$(if($interpret.PSObject.Properties['PendingEvent']){$interpret.PendingEvent}else{'none'});compound_detected=$(if($interpret.PSObject.Properties['CompoundDetected']){$interpret.CompoundDetected}else{$false});selected_method=$interpret.Intent.method;selected_tool=$(if(([string]$interpret.Intent.method)-match'(?i)crowbar|pry'){'crowbar'}else{$null});method_player_supplied=([bool]($interpret.Intent.method)-and$text-match'(?i)\b(?:with|using|crowbar|pry|force|dial|combination|lock|finesse)\b');pre_player_location=$resolved.PreLocation;post_player_location=$resolved.PostLocation;pre_relevant_item_locations=$resolved.PreItemLocations;post_relevant_item_locations=$resolved.PostItemLocations;aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$resolved.Reason;engine_routing_family=$interpret.RoutingFamily;result_category='ENGINE_REJECTED';roll_feedback=$null;narration_validation_result=$null;interpreter_latency_seconds=$interpret.ElapsedSeconds;full_turn_latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Depth 12 -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx ([pscustomobject]@{turn_id=$turnId;status='engine_rejected';narration=$resolved.Reason;state=Get-SlicePlayerState $script:session});continue}
  $script:session.RecentReferents=@($interpret.Intent.target);$narrated=Invoke-SliceNarration $script:session $resolved -MaxAttempts ([int]$script:session.Content.Slice.narrator_max_attempts) -Root $root;$script:session.History.Add($narrated.Text);$after=Get-NotebookSnapshot $script:session;$delta=Get-NotebookChanges $before $after;$turnWatch.Stop();$public=Get-SlicePlayerState $script:session;$rollFeedback=Format-SliceRollFeedback $resolved.Check $cfg.roll_feedback_mode;$response=[pscustomobject]@{turn_id=$turnId;status='resolved';narration=$narrated.Text;roll_feedback=$rollFeedback;location=$public.location;time=$public.time;notebook_changed=$delta.changed;new_notebook_entries=$(if($delta.changed){$after}else{$null});guillermo=$public.guillermo;slice_state=$public.slice_state;state=$public}
  [ordered]@{timestamp=[datetime]::UtcNow.ToString('o');turn_id=$turnId;raw_player_input=$text;structured_intent=$interpret.Intent;interpreted_intent=$interpret.Intent;interpretation_status=$interpret.Status;resolved_actor=$interpret.Intent.actor;action=$interpret.Intent.action;target=$interpret.Intent.target;purpose=$interpret.Intent.purpose;inherited_from_pending=@($(if($interpret.PSObject.Properties['InheritedFromPending']){$interpret.InheritedFromPending}else{@()}));pending_intent_event=$(if($interpret.PSObject.Properties['PendingEvent']){$interpret.PendingEvent}else{'none'});compound_detected=$(if($interpret.PSObject.Properties['CompoundDetected']){$interpret.CompoundDetected}else{$false});selected_method=$interpret.Intent.method;selected_tool=$(if(([string]$interpret.Intent.method)-match'(?i)crowbar|pry'){'crowbar'}else{$null});method_player_supplied=([bool]($interpret.Intent.method)-and$text-match'(?i)\b(?:with|using|crowbar|pry|force|dial|combination|lock|finesse)\b');pre_player_location=$resolved.PreLocation;post_player_location=$resolved.PostLocation;pre_relevant_item_locations=$resolved.PreItemLocations;post_relevant_item_locations=$resolved.PostItemLocations;state_query_result=$(if($interpret.Intent.action-eq'query_state'){@($resolved.Events)-join' '}else{$null});aliases_matched=$interpret.AliasesMatched;recent_referent_used=$interpret.RecentReferentUsed;clarification_reason=$interpret.Reason;interpreter_path=$interpret.RawModelStructuredOutput;semantic_fast_path=($interpret.RawModelStructuredOutput-eq'slice_semantic_route');model_fallback=($interpret.RawModelStructuredOutput-ne'slice_semantic_route');engine_routing_family=$interpret.RoutingFamily;result_category=$resolved.Classification;classification=$resolved.Classification;active_check=$resolved.Check;roll_feedback=$rollFeedback;engine_resolution=[pscustomobject]@{accepted=$resolved.Accepted;degree=$resolved.Degree;events=$resolved.Events};notebook_changed=$delta.changed;narrator_raw_outputs=$narrated.RawOutputs;validator_attempts=$narrated.Validations;narration_validation_result=$narrated.Validation;validator=$narrated.Validation;displayed_narration=$narrated.Text;retry_occurred=$narrated.RetryOccurred;fallback_used=$narrated.FallbackUsed;interpreter_latency_seconds=$interpret.ElapsedSeconds;narrator_latency_seconds=$narrated.ElapsedSeconds;full_turn_latency_seconds=$turnWatch.Elapsed.TotalSeconds}|ConvertTo-Json -Depth 16 -Compress|Add-Content -Encoding utf8 $telemetry;Send-Json $ctx $response}
 else{Send-Json $ctx ([pscustomobject]@{error='route_not_found'}) 404}
 }catch{[Console]::Error.WriteLine("Bridge request failed: $($_.Exception.Message)");try{Send-Json $ctx ([pscustomobject]@{error='request_failed'}) 400}catch{}}}}
finally{$listener.Stop();$listener.Close();if(Test-Path $pidPath){Remove-Item -LiteralPath $pidPath -Force}}
