$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot 'src/HousePrototype.psm1') -Force -DisableNameChecking;Import-Module (Join-Path $PSScriptRoot 'src/CombatPrototype.psm1') -Force -DisableNameChecking;Import-Module (Join-Path $PSScriptRoot 'src/GameState.psm1') -Force -DisableNameChecking
$script:p=0;$script:f=0;function Check([string]$n,[bool]$ok){if($ok){$script:p++;Write-Host "PASS $n"}else{$script:f++;Write-Host "FAIL $n" -ForegroundColor Red}}
$h=Read-HouseContent $PSScriptRoot;Check '1 Seven authored rooms' ($h.rooms.Count-eq7);Check '2 Opens outside' ($h.start_location-eq'exterior');Check '3 Twenty-three total clues with Study core' ((17+6)-eq23)
$s=New-HouseSession $PSScriptRoot 77;Check '4 Overview grants no clue' ((Invoke-HouseTurn $s 'look around').clues_added-eq0-and(Get-HouseClueCount $s)-eq0);Check '5 Overview grants no Notebook clue' (@($s.State.Notebook.Clues.Keys).Count-eq0)
$dead=@();foreach($room in $h.rooms){$s.State.Player.Location=$room.id;foreach($id in $s.State.Locations[$room.id].VisibleObjects){if(-not$s.State.Items.Contains($id)){$dead+=$id}}};Check '6 All overview objects are engine referents' ($dead.Count-eq0)
$missingClueRefs=@($h.clues|Where-Object{-not$s.State.Items.Contains([string]$_.referent)});Check '7 Every clue referent resolves' ($missingClueRefs.Count-eq0);$aff=Read-CombatAffordanceContent (Join-Path $PSScriptRoot 'content/combat_affordances.json') (Join-Path $PSScriptRoot 'content/callum_study/objects.json');Check '8 Every affordance referent validates' ($aff.rooms.affordances.Count-eq16)
$allStatic=@($s.State.Items.Values|Where-Object{$_.RenderClass-notin@('static-renderable','animate-excluded')});Check '9 Every prop has render class' ($allStatic.Count-eq0)
$s=New-HouseSession $PSScriptRoot; $r=Invoke-HouseTurn $s 'open the front door';Check '10 Front door locked' ($r.narration-match'locked');$null=Invoke-HouseTurn $s 'circle the house';Check '11 Both entry routes discovered' ($s.EntryRoutesDiscovered.Count-eq2)
$a=New-HouseSession $PSScriptRoot;$null=Invoke-HouseTurn $a 'circle house';$null=Invoke-HouseTurn $a 'go kitchen';$b=New-HouseSession $PSScriptRoot;$null=Invoke-HouseTurn $b 'circle house';$null=Invoke-HouseTurn $b 'go cellar';Check '12 Kitchen entry works' ($a.State.Player.Location-eq'kitchen');Check '13 Cellar entry works' ($b.State.Player.Location-eq'cellar');Check '14 Entry changes no clue truth' ($a.State.Clues.Count-eq$b.State.Clues.Count)
$s=New-HouseSession $PSScriptRoot;1..3|ForEach-Object{$null=Invoke-HouseTurn $s 'examine the locked front door'};Check '15 Exterior anti-stuck ambient points sideways' ((Invoke-HouseTurn $s 'look around').narration-match'side of the house|around the wall')
$reachable=[Collections.Generic.HashSet[string]]::new();$q=[Collections.Generic.Queue[string]]::new();$q.Enqueue('exterior');while($q.Count){$id=$q.Dequeue();if($reachable.Add($id)){foreach($x in @(($h.rooms|Where-Object {$_.id-eq$id}).exits)){$q.Enqueue($x)}}};Check '16 Full topology reachable' ($reachable.Count-eq7)
$s=New-HouseSession $PSScriptRoot;foreach($room in $h.rooms){$s.State.Player.Location=$room.id;$before=Get-HouseClueCount $s;$r=Invoke-HouseTurn $s 'look around';if((Get-HouseClueCount $s)-ne$before){throw "Overview leaked clue in $($room.id)"}};Check '17 Every room overview gate passes' $true
$s=New-HouseSession $PSScriptRoot;foreach($room in $h.rooms){$s.State.Player.Location=$room.id;$r=Invoke-HouseTurn $s 'ask Guillermo to look';if($r.narration-notmatch'Guillermo|Armand'){throw "Guillermo gate failed $($room.id)"}};Check '18 Guillermo opportunities retain Early handoff' $true
$s=New-HouseSession $PSScriptRoot;$s.State.Player.Location='callum_study';$s.Encounter.study_entered=$true;$s.State.Clues.mail_accumulation.Discovered=$true;$s.State.Clues.clue_tracks.Discovered=$true;$r=Invoke-HouseTurn $s 'look around';Check '19 Encounter requires three clues' (-not$r.state.house_state.encounter.warning_active);$s.State.Clues.clue_window_smudge.Discovered=$true;$r=Invoke-HouseTurn $s 'look around';Check '20 Warning occurs before contact' ($r.state.house_state.encounter.warning_active-and-not$r.start_combat);$r=Invoke-HouseTurn $s 'look around';Check '21 Contact occurs one turn later' $r.start_combat;$r2=Invoke-HouseTurn $s 'look around';Check '22 Trigger cannot fire twice' (-not$r2.start_combat)
$s=New-HouseSession $PSScriptRoot;$s.State.Player.Location='cellar';$s.Encounter.study_entered=$true;foreach($id in 'mail_accumulation','clue_tracks','clue_window_smudge'){$s.State.Clues[$id].Discovered=$true};$r=Invoke-HouseTurn $s 'look around';Check '23 Cellar suppresses trigger' (-not$r.state.house_state.encounter.warning_active)
$s=New-HouseSession $PSScriptRoot;$s.State.Player.Location='callum_study';$s.Encounter.study_entered=$true;foreach($id in 'mail_accumulation','clue_tracks','clue_window_smudge'){$s.State.Clues[$id].Discovered=$true};$null=Invoke-HouseTurn $s 'look around';$r=Invoke-HouseTurn $s 'hide behind the desk';Check '24 Stealth resolution route works' ($s.Encounter.outcome-eq'stealth'-and-not$r.start_combat)
$s=New-HouseSession $PSScriptRoot;$s.PersistentEnvironment.Add([pscustomobject]@{room_id='callum_study';referent_id='oil_lamp';state='floor_fire';description='floor fire'});$json=Export-HouseSave $s;$loaded=Import-HouseSave $PSScriptRoot $json;Check '25 Aftermath survives save load' ($loaded.PersistentEnvironment[0].state-eq'floor_fire');Check '26 Stable save serialization' ((Export-HouseSave $loaded)-eq$json)
$sample=[ordered]@{z=1.2;a=2};$j1=ConvertTo-StableStateJson $sample;$j2=ConvertTo-StableStateJson ([ordered]@{a=2;z=1.20001});Check '27 Ordered fixed-precision serialization' ($j1-eq$j2-and$j1.IndexOf('"a"')-lt$j1.IndexOf('"z"'))
$s=New-HouseSession $PSScriptRoot;$s.State.Player.Location='callum_study';$null=Invoke-HouseTurn $s 'examine the large painting';$r=Invoke-HouseTurn $s 'use 08-10-83 on the safe';$r=Invoke-HouseTurn $s 'take the burned note';Check '28 Lead endpoint reachable' $s.LeadRecovered
$s2=New-HouseSession $PSScriptRoot;$s2.State.Player.Location='callum_study';$s2.Encounter.resolved=$true;$s2.Encounter.outcome='armand_defeated';$null=Invoke-HouseTurn $s2 'examine the paneled wall';$null=Invoke-HouseTurn $s2 'use 08-10-83 on the safe';$null=Invoke-HouseTurn $s2 'take the burned note';Check '29 Lead reachable after lost encounter' $s2.LeadRecovered
$commands='look around','ask Guillermo to check mailbox','circle house','go kitchen','investigate stove';$x=New-HouseSession $PSScriptRoot 123;$y=New-HouseSession $PSScriptRoot 123;$tx=@($commands|ForEach-Object{(Invoke-HouseTurn $x $_).narration});$ty=@($commands|ForEach-Object{(Invoke-HouseTurn $y $_).narration});Check '30 Seeded replay identical' (($tx-join'|')-eq($ty-join'|'))
$ui=Get-Content -Raw (Join-Path $PSScriptRoot 'godot/Main.gd');Check '31 Three-pane shell authored' ($ui-match'HSplitContainer'-and$ui-match'VSplitContainer'-and$ui-match'AspectRatioContainer');Check '32 Split persistence authored' ($ui-match'user://layout.cfg');Check '33 Notebook remains collapsible' ($ui-match'notebook_tabs.visible')
$mundane=0;foreach($room in $h.rooms){$mundane+=@($room.mundane.PSObject.Properties).Count};Check '34 Mundane density preserved' ($mundane-ge34);Check '35 Ending remains direction not solution' ($h.ending.text-match'Blackthorn Station'-and$h.ending.text-notmatch'culprit|who took')
Write-Host "Phase 6: $script:p passed, $script:f failed";if($script:f){exit 1}
