$ErrorActionPreference='Stop';$root=$PSScriptRoot
Import-Module (Join-Path $root 'src/VerticalSlice.psm1') -Force -DisableNameChecking
function Assert($Condition,[string]$Message){if(-not$Condition){throw "FAILED: $Message"}}
function DirectIntent([string]$Action,[string]$Target){[pscustomobject]@{Actor='Armand';Action=$Action;Target=$Target;SecondaryTarget=$null;Method=$null;Area=$null;CommunicativeIntent=$null;Spell=$null;Purpose=$null;Modifiers=@();RawInput='setup'}}
function New-Scenario([string]$Setup){$s=New-CallumStudySession $root;switch($Setup){blood{Resolve-SliceIntent $s (DirectIntent examine rug) 11|Out-Null}scorch{Resolve-SliceIntent $s (DirectIntent examine fireplace) 11|Out-Null}both{Resolve-SliceIntent $s (DirectIntent examine rug) 11|Out-Null;Resolve-SliceIntent $s (DirectIntent examine fireplace) 11|Out-Null}gap{Resolve-SliceIntent $s (DirectIntent examine bookshelves)|Out-Null}recent_desk{$s.RecentReferents=@('writing_desk')}recent_many{$s.RecentReferents=@('writing_desk','rug')}safe{Resolve-SliceIntent $s (DirectIntent examine large_painting)|Out-Null}};$s}
function Case([string]$Text,[string]$Action,[string]$Target,[string]$Setup='default',[string]$Actor='armand',[string]$Spell=$null,[string]$PurposeLike=$null,[string]$Area=$null,[string]$Status='RESOLVED'){[pscustomobject]@{text=$Text;action=$Action;target=$Target;setup=$Setup;actor=$Actor;spell=$Spell;purpose=$PurposeLike;area=$Area;status=$Status}}
$cases=@(
 Case 'look at desk' examine writing_desk; Case 'inspect the writing desk' examine writing_desk; Case 'check the table' examine writing_desk; Case 'study the desk carefully' investigate writing_desk; Case 'look under the desk' examine writing_desk default armand $null $null underneath; Case 'peer inside the writing desk' examine writing_desk default armand $null $null inside;
 Case 'move the rug' manipulate rug; Case 'lift the rug' manipulate rug; Case 'pull the rug aside' manipulate rug; Case 'roll back the rug' manipulate rug; Case 'shift the rug carefully' manipulate rug; Case 'check underneath the rug' examine rug default armand $null $null underneath; Case 'move the rug to examine beneath' manipulate rug default armand $null 'examine underneath' underneath; Case 'drag the rug aside' manipulate rug;
 Case 'misty step to the desk' cast writing_desk default armand misty_step; Case 'teleport over by the desk with Misty Step' cast writing_desk default armand misty_step; Case 'use Misty Step to get beside the desk' cast writing_desk default armand misty_step; Case 'blink over to the desk' cast writing_desk default armand misty_step; Case 'cast Detect Magic on the fireplace' cast fireplace default armand detect_magic; Case 'use Detect Magic on the hearth' cast fireplace default armand detect_magic; Case 'cast Darkness over the doorway' cast study_door default armand darkness; Case 'Misty Step beside the table' cast writing_desk default armand misty_step;
 Case 'look at the dark mark' examine bloodstain blood; Case 'inspect the stain' examine bloodstain blood; Case 'check the discoloration' examine bloodstain blood; Case 'investigate the mark on the floor' investigate bloodstain blood; Case 'take a closer look at that stain' examine bloodstain blood; Case 'study the blood stain' investigate bloodstain blood; Case 'look at the scorch marks' examine scorch_marks scorch; Case 'check whether the scorch marks came from ordinary fire' examine scorch_marks scorch armand $null 'ordinary fire';
 Case 'inspect the bookcase' examine bookshelves; Case 'look at the shelves' examine bookshelves; Case 'search the bookshelves' investigate bookshelves; Case 'inspect the gap' examine bookshelf_gap gap; Case 'look at the empty space' examine bookshelf_gap gap; Case 'see what book might fit there' examine bookshelf_gap gap armand $null 'missing book'; Case 'work out what was removed' investigate bookshelf_gap gap armand $null 'missing book'; Case 'check the shelf wear' examine bookshelf_gap gap armand $null 'missing book';
 Case 'read correspondence' read correspondence; Case 'read the receipts' read receipt; Case 'look at the receipts and see where Callum has been' examine receipt default armand $null 'whereabouts'; Case 'check the receipts for addresses' examine receipt default armand $null 'addresses'; Case 'rifle through the receipts for travel clues' search receipt default armand $null 'travel';
 Case 'send Guillermo to investigate the bookcase' examine bookshelves default guillermo; Case 'have Guillermo inspect the shelves' examine bookshelves default guillermo; Case 'tell Guillermo to check the desk' examine writing_desk default guillermo; Case 'Guillermo inspect the desk' examine writing_desk default guillermo; Case 'ask Guillermo what he thinks' speak guillermo;
 Case 'inspect it' examine writing_desk recent_desk armand $null $null $null; Case 'look underneath it' examine writing_desk recent_desk armand $null $null underneath; Case 'study that carefully' investigate writing_desk recent_desk; Case 'look at those' $null $null recent_many armand $null $null $null NEEDS_CLARIFICATION;
 Case 'investigate the dark marks' $null $null both armand $null $null $null NEEDS_CLARIFICATION; Case 'look at the dark marks' $null $null both armand $null $null $null NEEDS_CLARIFICATION;
 Case 'poke the fireplace' manipulate fireplace; Case 'peer behind the painting' examine large_painting default armand $null $null behind; Case 'shift the painting' manipulate large_painting; Case 'turn the correspondence over' manipulate correspondence; Case 'knock on the wall' manipulate paneled_wall
)
$n=0;foreach($case in $cases){$n++;$s=New-Scenario $case.setup;$r=Invoke-SliceInterpretation $s $case.text;Assert ($r.Status-eq$case.status) "$n status: $($case.text)";if($case.status-eq'RESOLVED'){Assert ($r.Intent.actor-eq$case.actor) "$n actor: $($case.text)";Assert ($r.Intent.action-eq$case.action) "$n action: $($case.text)";Assert ($r.Intent.target-eq$case.target) "$n target: $($case.text)";if($case.spell){Assert ($r.Intent.spell-eq$case.spell) "$n spell: $($case.text)"};if($case.purpose){Assert ($r.Intent.purpose-match[regex]::Escape($case.purpose)) "$n purpose: $($case.text)"};if($case.area){Assert ($r.Intent.area-eq$case.area) "$n area: $($case.text)"}}}
Assert ($cases.Count-ge50) 'matrix contains at least 50 utterances'
$hidden=New-CallumStudySession $root;$hiddenResult=Invoke-SliceInterpretation $hidden 'inspect the safe dial';Assert ($hiddenResult.Status-ne'RESOLVED'-or$hiddenResult.Intent.target-ne'safe_dial') 'hidden sub-referent never leaks'
$safe=New-Scenario safe;$dial=Invoke-SliceInterpretation $safe 'inspect the safe dial';Assert ($dial.Intent.target-eq'safe_dial') 'revealed dynamic sub-referent resolves'
$capContext=Get-SliceInterpretationContext (New-CallumStudySession $root);Assert ((@($capContext.Entities|Where-Object{$_.Id-eq'rug'})[0].Capabilities)-contains'manipulate') 'authored target capability model reaches context'
$questionSession=New-Scenario gap;$question=Invoke-SliceInterpretation $questionSession 'look for the book that would fit that gap';$questionResult=Resolve-SliceIntent $questionSession $question.Intent;Assert ($questionResult.Accepted-and$questionResult.Events-match'does not reliably establish its size, title, or present location') 'clever unsupported question receives bounded partial answer'
$receiptSession=New-Scenario default;$receiptQuestion=Invoke-SliceInterpretation $receiptSession 'look at the receipts and see where Callum has been';$receiptResult=Resolve-SliceIntent $receiptSession $receiptQuestion.Intent;Assert ($receiptResult.Classification-eq'MUNDANE'-and$receiptResult.Events-match'no address, itinerary, or reliable evidence') 'purpose is answered without invented travel evidence'
$recentSession=New-Scenario recent_desk;$recentResult=Invoke-SliceInterpretation $recentSession 'inspect it';Assert ($recentResult.RecentReferentUsed-and$recentResult.Intent.target-eq'writing_desk') 'single recent pronoun is recorded and resolved'
$impossible=New-Scenario default;$moveResult=Resolve-SliceIntent $impossible ([pscustomobject]@{Actor='Armand';Action='move';Target='writing_desk';Method=$null;Area=$null;RawInput='move toward the desk'});Assert (-not$moveResult.Accepted-and$moveResult.Classification-eq'IMPOSSIBLE') 'understood impossible action remains distinct'
Write-Host "Intent resolution polish tests passed: $($cases.Count) deterministic paraphrases, clarification, lifecycle, purpose, and wrong-target prevention."
