$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot 'src/CombatPrototype.psm1') -Force -DisableNameChecking;Import-Module (Join-Path $PSScriptRoot 'src/VerticalSlice.psm1') -Force -DisableNameChecking
$script:passed=0;$script:failed=0;function Check([string]$Name,[bool]$Ok){if($Ok){$script:passed++;Write-Host "PASS $Name"}else{$script:failed++;Write-Host "FAIL $Name" -ForegroundColor Red}}
$path=Join-Path $PSScriptRoot 'content/combat_affordances.json';$objects=Join-Path $PSScriptRoot 'content/callum_study/objects.json';$content=Read-CombatAffordanceContent $path $objects;$all=@($content.rooms.affordances)
Check '1 Sixteen authored affordances load' ($all.Count-eq16);Check '2 Seven room counts are exact' ((@($content.rooms|ForEach-Object{$_.affordances.Count})-join',')-eq'2,2,2,1,2,4,3');Check '3 Every entry has five outcomes' (@($all|Where-Object{@($_.outcomes.PSObject.Properties).Count-ne5}).Count-eq0)
$bad=Get-Content -Raw $path|ConvertFrom-Json;$bad.rooms[0].affordances[0].referent_id='invented_combat_only_noun';$tmp=Join-Path ([IO.Path]::GetTempPath()) ('armand-affordance-'+[guid]::NewGuid().ToString('N')+'.json');$bad|ConvertTo-Json -Depth 15|Set-Content -Encoding utf8 $tmp;$threw=$false;try{$null=Read-CombatAffordanceContent $tmp $objects}catch{$threw=$_.Exception.Message-match'unresolved referent_id'}finally{Remove-Item -LiteralPath $tmp -Force};Check '4 Unresolved referent fails loudly' $threw
$c=New-CombatSession $PSScriptRoot benchmark_b 10;$c.active_combatant='armand';$c.initiative_index=[array]::IndexOf($c.initiative_order,'armand');$state=Get-CombatPlayerState $c;Check '5 Panel exposes four Study hints' ($state.nearby_affordances.Count-eq4);Check '6 Panel uses authored context' (@($state.nearby_affordances.panel_hint)-contains'oil lamp (above Cultist B)');Check '7 Opening prose is authored' ($state.opening_narration-match'writing desk'-and$state.opening_narration-match'oil lamp'-and$state.opening_narration-match'Fire-irons'-and$state.opening_narration-match'paintings')
$c.combatants.armand.position='behind desk';Check '8 Position-invalid lamp is omitted' (@((Get-CombatPlayerState $c).nearby_affordances.id)-notcontains'study_oil_lamp');$c.combatants.armand.position='engaged'
$degreeRolls=20,10,5,2,1;$degreeNames='Exceptional Success','Success','Setback','Failure','Severe Failure';for($i=0;$i-lt5;$i++){$testRoll=[int]$degreeRolls[$i];$expectedDegree=[string]$degreeNames[$i];$x=New-CombatSession $PSScriptRoot benchmark_b ($testRoll+100);$x.reaction_prompt=$null;$x.pending_enemy_sequence=$false;$x.active_combatant='armand';$x.initiative_index=[array]::IndexOf($x.initiative_order,'armand');$r=Invoke-CombatCommand $x 'Bring down the oil lamp on Cultist 2.' -FixedCreativeRoll $testRoll;Check "9 Degree $expectedDegree authored" ($r.telemetry.rolls[0].degree-eq$expectedDegree)}
$c=New-CombatSession $PSScriptRoot benchmark_b 22;$c.reaction_prompt=$null;$c.pending_enemy_sequence=$false;$c.active_combatant='armand';$c.initiative_index=[array]::IndexOf($c.initiative_order,'armand');$r=Invoke-CombatCommand $c 'Bring down the oil lamp on Cultist 2.' -FixedCreativeRoll 15;Check '10 Persistent room change recorded' ($c.room_changes[0].state-eq'floor_fire');Check '11 Single-use affordance spent and omitted' ($c.spent_affordances.Contains('study_oil_lamp')-and@((Get-CombatPlayerState $c).nearby_affordances.id)-notcontains'study_oil_lamp');$c.reaction_prompt=$null;$c.active_combatant='armand';$again=Invoke-CombatCommand $c 'Bring down the oil lamp on Cultist 2.' -FixedCreativeRoll 20;Check '12 Spent maneuver does not reroll' ($again.narration-match'no free reroll')
$s=New-CallumStudySession $PSScriptRoot;$s.PersistentEnvironment.Add($c.room_changes[0]);$intent=[pscustomobject]@{Actor='Armand';Action='wait';Target='study_room';Method=$null;Spell=$null;Purpose=$null};$resolved=Resolve-SliceIntent $s $intent;Check '13 Aftermath enters later investigation narration packet' ((@($resolved.Events)-join' ')-match'floor fire')
$public=Get-CombatPlayerState $c;$json=$public|ConvertTo-Json -Depth 12;Check '14 Public state does not expose outcome tables' ($json-notmatch'burning_prone|outcomes|opening_text');Check '15 Affordance roll feedback uses skill and degree' ($r.roll_feedback-match'Finesse.*Success');Check '16 No affordance deals raw damage' (@($all.outcomes.PSObject.Properties.Value.effect|Where-Object{$_-match'damage'}).Count-eq0)
Write-Host "Combat affordances: $script:passed passed, $script:failed failed";if($script:failed){exit 1}
