Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Resolution.psm1') -Force

function Get-CombatRoll { param($Combat,[int]$Sides=20) $Combat.RollIndex++;$r=[Random]::new([int]($Combat.Seed+$Combat.RollIndex*7919));$r.Next(1,$Sides+1) }
function New-Combatant { param([string]$Id,[string]$Name,[string]$Side,[int]$AC,[int]$HP,[int]$Dex,[string]$Position='engaged') [pscustomobject]@{id=$Id;name=$Name;side=$Side;ac=$AC;hp=$HP;max_hp=$HP;temp_hp=0;dex=$Dex;alive=$true;incapacitated=$false;position=$Position;engaged_targets=[Collections.Generic.List[string]]::new();movement_used=$false;action_used=$false;bonus_action_used=$false;reaction_available=$true;effects=[Collections.Generic.List[string]]::new();awareness='aware';pursuit='none'} }
function New-CombatSession {
 param([string]$Root=(Split-Path -Parent $PSScriptRoot),[ValidateSet('benchmark_a','benchmark_b','benchmark_c')][string]$EncounterId='benchmark_a',[int]$Seed=1)
 $cfg=Get-Content -Raw (Join-Path $Root 'content/combat_prototype.json')|ConvertFrom-Json;$enc=$cfg.encounters.$EncounterId;$fighters=[ordered]@{};$arm=New-Combatant armand Armand player 11 18 3;$arm.engaged_targets.Add('enemy_1');$fighters.armand=$arm
 $g=New-Combatant guillermo Guillermo ally 14 12 2 'near desk';$fighters.guillermo=$g;$i=0
 foreach($tierId in @($enc.enemies)){$i++;$t=$cfg.tiers.$tierId;$e=New-Combatant "enemy_$i" "$($t.name) $i" hostile ([int]$t.ac) ([int]$t.hp) ([int]$t.dex);$e|Add-Member tier $tierId;$e|Add-Member attack_bonus ([int]$t.attack);$e|Add-Member damage_die ([int]$t.damage_die);$e|Add-Member damage_bonus ([int]$t.damage_bonus);$e|Add-Member passive_perception ([int]$t.passive_perception);$e|Add-Member priorities @($t.priorities);$e|Add-Member minor_magic $(if($t.PSObject.Properties['minor_magic']){$t.minor_magic}else{$null});$e.engaged_targets.Add('armand');$fighters[$e.id]=$e}
 $combat=[pscustomobject]@{active=$true;encounter_id=$EncounterId;encounter_name=$enc.name;initiative_order=@();active_combatant=$null;initiative_index=0;turn_number=1;combatants=$fighters;darkness=[pscustomobject]@{active=$false;position=$null};tutorial_required=$true;reaction_prompt=$null;pending_enemy_sequence=$false;end_reason=$null;layer='combat';Seed=$Seed;RollIndex=0;creative_history=[ordered]@{};telemetry=[Collections.Generic.List[object]]::new()}
 $rolls=@();foreach($id in @($fighters.Keys|Where-Object{$_-ne'guillermo'})){$r=Get-CombatRoll $combat 20;$rolls+=[pscustomobject]@{id=$id;total=$r+$fighters[$id].dex;roll=$r}}
 $combat.initiative_order=@($rolls|Sort-Object @{Expression='total';Descending=$true},@{Expression='id';Descending=$false}|ForEach-Object{$_.id});$combat.active_combatant=$combat.initiative_order[0]
 while($combat.active_combatant-ne'armand'-and$combat.active){Invoke-EnemyTurn $combat $combat.active_combatant|Out-Null;if($combat.reaction_prompt){break};Move-CombatInitiative $combat}
 $combat
}
function Reset-CombatBudget {param($Actor)$Actor.movement_used=$false;$Actor.action_used=$false;$Actor.bonus_action_used=$false;$Actor.reaction_available=$true}
function Move-CombatInitiative {param($Combat)$Combat.initiative_index=($Combat.initiative_index+1)%$Combat.initiative_order.Count;if($Combat.initiative_index-eq0){$Combat.turn_number++};$Combat.active_combatant=$Combat.initiative_order[$Combat.initiative_index];Reset-CombatBudget $Combat.combatants[$Combat.active_combatant]}
function Apply-CombatDamage {param($Target,[int]$Damage)$before=$Target.hp;$absorbed=[Math]::Min($Target.temp_hp,$Damage);$Target.temp_hp-=$absorbed;$Damage-=$absorbed;$Target.hp=[Math]::Max(0,$Target.hp-$Damage);if($Target.hp-eq0){$Target.alive=$false;$Target.incapacitated=$true};[pscustomobject]@{before=$before;after=$Target.hp;absorbed=$absorbed}}
function Resolve-CombatAttack {param($Combat,$Attacker,$Target,[int]$Bonus,[int]$Die,[int]$DamageBonus=0,[string]$Label='Attack',[string]$RollMode='normal')$r1=Get-CombatRoll $Combat 20;$r2=Get-CombatRoll $Combat 20;$natural=if($RollMode-eq'advantage'){[Math]::Max($r1,$r2)}elseif($RollMode-eq'disadvantage'){[Math]::Min($r1,$r2)}else{$r1};$hit=($natural+$Bonus)-ge$Target.ac;$damage=if($hit){(Get-CombatRoll $Combat $Die)+$DamageBonus}else{0};$change=if($hit){Apply-CombatDamage $Target $damage}else{$null};[pscustomobject]@{label=$Label;roll=$natural;rolls=$(if($RollMode-eq'normal'){@($r1)}else{@($r1,$r2)});mode=$RollMode;total=$natural+$Bonus;ac=$Target.ac;hit=$hit;damage=$damage;hp_change=$change}}
function Get-LiveEnemies {param($Combat)@($Combat.combatants.Values|Where-Object{$_.side-eq'hostile'-and$_.alive})}
function Complete-CombatIfEnded {param($Combat,[string]$Reason='all_hostiles_defeated')if(@(Get-LiveEnemies $Combat).Count-eq0){$Combat.active=$false;$Combat.end_reason=$Reason;$Combat.layer='investigation';return $true};$false}
function Grant-DarkOnesBlessing {param($Combat)$a=$Combat.combatants.armand;$a.temp_hp=[Math]::Max($a.temp_hp,6)}
function Resolve-EnemyDefeat {param($Combat,$Enemy,[string]$Kind='incapacitated')$Enemy.alive=$false;$Enemy.incapacitated=$true;$Enemy.effects.Add($Kind);Grant-DarkOnesBlessing $Combat;Complete-CombatIfEnded $Combat $(if($Kind-eq'surrendered'){'surrender'}elseif($Kind-eq'fled'){'enemy_fled'}else{'all_hostiles_defeated'})|Out-Null}

function ConvertFrom-CombatCommand {
 param([string]$Text)$t=$Text.Trim();$moves=[Collections.Generic.List[object]]::new();$actions=[Collections.Generic.List[object]]::new();$bonus=$null
 $moveMatches=[regex]::Matches($t,'(?i)\b(misty step|run|walk|crawl|climb|jump|vault|back|move|flee|escape)\b(?:\s+(?:to|toward|behind|beside|through|across|into))?\s*(?:the\s+)?([^,.]+?)(?=\s+and\s+(?:cast|blast|fire|attack|hide|shove|trip|disarm|kick|slam|overturn|bluff|intimidate|tell|have|ask)|[,.;]|$)')
 foreach($m in $moveMatches){$moves.Add([pscustomobject]@{method=$m.Groups[1].Value.ToLower();destination=$m.Groups[2].Value.Trim()})}
 $verbCount=[regex]::Matches($t,'(?i)\b(?:misty step|run|walk|crawl|climb|jump|vault|back|move|flee|escape)\b').Count;while($moves.Count-lt$verbCount){$moves.Add([pscustomobject]@{method='additional movement';destination=$null})}
 foreach($pattern in @('(?i)\b(eldritch blast|fire bolt|cast darkness|darkness|blast|hide|shove|trip|disarm|slam|overturn|bluff|intimidate|kick|attack|search)\b')){foreach($m in [regex]::Matches($t,$pattern)){$actions.Add([pscustomobject]@{kind=$m.Groups[1].Value.ToLower();text=$t})}}
 if($t-match'(?i)\b(?:tell|have|ask|command)\s+guillermo\s+(?:to\s+)?(.+)$'){$g=($Matches[1]-split'(?i)\s+and\s+(?=eldritch|fire|cast|blast|attack|hide|shove|trip|disarm|kick|slam|overturn|bluff|intimidate)')[0];$consequential=$g-match'(?i)sabotage|knock|steal|directly distract|attack|enemy|weapon|lamp';$bonus=[pscustomobject]@{kind='guillermo';command=$g;command_type=$(if($consequential){'consequential'}else{'minor'})};if($consequential){$actions.Add([pscustomobject]@{kind='guillermo_consequential';text=$g})}}
 [pscustomobject]@{raw=$t;movements=@($moves);actions=@($actions);bonus_action=$bonus}
}
function Test-CombatCommand {param($Parsed)if($Parsed.movements.Count-gt1){return [pscustomobject]@{valid=$false;message='You can make one Movement and one Action this turn. Which movement do you want to use?'}};if($Parsed.actions.Count-gt1){return [pscustomobject]@{valid=$false;message='You can take one Action this turn. Which do you want to do?'}};[pscustomobject]@{valid=$true;message=$null}}
function Get-TargetEnemy {param($Combat,[string]$Text)$live=Get-LiveEnemies $Combat;if($Text-match'(?i)(?:enemy|cultist|initiate|adept)\s*([0-9])'){$id="enemy_$($Matches[1])";if($Combat.combatants.Contains($id)-and$Combat.combatants[$id].alive){return $Combat.combatants[$id]}};$live|Select-Object -First 1}
function Invoke-EnemyTurn {
 param($Combat,[string]$EnemyId)$e=$Combat.combatants[$EnemyId];$a=$Combat.combatants.armand;if(-not$e.alive){return [pscustomobject]@{decision='incapacitated'}};$decision='attack';$text=''
 if($Combat.darkness.active-and$e.position-eq$Combat.darkness.position){$e.position='near doorway';$e.movement_used=$true;$decision='leave_darkness';$text="$($e.name) withdraws from the magical darkness and guards the edge."}
 elseif($e.tier-eq'initiate'-and$e.hp-le2){Resolve-EnemyDefeat $Combat $e fled;$decision='retreat';$text="$($e.name) breaks and flees the fight.";return [pscustomobject]@{decision=$decision;narration=$text}}
 elseif($e.tier-eq'adept'-and-not$e.effects.Contains('shadow_bind_used')){$e.effects.Add('shadow_bind_used');$a.effects.Add('shadow_bound');$e.action_used=$true;$decision='shadow_bind';$text="$($e.name) knots the nearby shadows around Armand's feet, putting his next movement at a disadvantage."}
 else{$mode=if($Combat.darkness.active-and$e.position-eq$Combat.darkness.position){'disadvantage'}else{'normal'};$atk=Resolve-CombatAttack $Combat $e $a $e.attack_bonus $e.damage_die $e.damage_bonus "$($e.name) attack" $mode;$e.action_used=$true;$text=if($atk.hit){"$($e.name) strikes Armand for $($atk.damage) damage."}else{"$($e.name) attacks, but misses."};if($atk.hit-and$a.reaction_available){$Combat.reaction_prompt=[pscustomobject]@{type='hellish_rebuke';source=$e.id;message='Use Hellish Rebuke?';options=@('Yes','No')};$Combat.pending_enemy_sequence=$true}}
 [pscustomobject]@{decision=$decision;narration=$text;reaction_pending=($null-ne$Combat.reaction_prompt)}
}
function Invoke-RemainingCombatants {param($Combat)$events=[Collections.Generic.List[string]]::new();do{Move-CombatInitiative $Combat;if(-not$Combat.active-or$Combat.active_combatant-eq'armand'){break};$r=Invoke-EnemyTurn $Combat $Combat.active_combatant;if($r.PSObject.Properties['narration']-and$r.narration){$events.Add($r.narration)};if($Combat.reaction_prompt){break}}while($true);@($events)}
function Invoke-CombatReaction {param($Combat,[bool]$Use,[Nullable[int]]$FixedSaveRoll)$prompt=$Combat.reaction_prompt;if(-not$prompt){throw 'No reaction is pending.'};$a=$Combat.combatants.armand;$e=$Combat.combatants[$prompt.source];$events=[Collections.Generic.List[string]]::new();if($Use-and$a.reaction_available){$save=if($null-ne$FixedSaveRoll){[int]$FixedSaveRoll}else{Get-CombatRoll $Combat 20};$damage=(Get-CombatRoll $Combat 10)+(Get-CombatRoll $Combat 10);if($save+1-ge13){$damage=[Math]::Floor($damage/2)};Apply-CombatDamage $e $damage|Out-Null;$a.reaction_available=$false;$events.Add("Hellish Rebuke lashes $($e.name) for $damage fire damage.");if(-not$e.alive){Resolve-EnemyDefeat $Combat $e}}
 else{$events.Add('Armand holds his reaction.')};$Combat.reaction_prompt=$null;$Combat.pending_enemy_sequence=$false;if($Combat.active){foreach($line in @(Invoke-RemainingCombatants $Combat)){if($line){$events.Add($line)}}};[pscustomobject]@{status='resolved';narration=@($events)-join' ';roll_feedback=$(if($Use){'🎲 Hellish Rebuke • Resolved'}else{$null});state=Get-CombatPlayerState $Combat}}

function Invoke-CombatCommand {
 param($Combat,[string]$Text,[Nullable[int]]$FixedAttackRoll,[Nullable[int]]$FixedDamageRoll,[Nullable[int]]$FixedCreativeRoll,[Nullable[int]]$FixedHideRoll)
 $watch=[Diagnostics.Stopwatch]::StartNew();if(-not$Combat.active){return [pscustomobject]@{status='not_in_combat';narration='Combat is not active.';state=Get-CombatPlayerState $Combat}};if($Combat.reaction_prompt){return [pscustomobject]@{status='reaction_required';narration=$Combat.reaction_prompt.message;state=Get-CombatPlayerState $Combat}};if($Combat.active_combatant-ne'armand'){return [pscustomobject]@{status='waiting';narration="It is not Armand's turn.";state=Get-CombatPlayerState $Combat}}
 $p=ConvertFrom-CombatCommand $Text;$v=Test-CombatCommand $p;if(-not$v.valid){return [pscustomobject]@{status='needs_clarification';narration=$v.message;parsed=$p;state=Get-CombatPlayerState $Combat}}
 $a=$Combat.combatants.armand;$events=[Collections.Generic.List[string]]::new();$rolls=[Collections.Generic.List[object]]::new();$positions=[Collections.Generic.List[object]]::new();$guillermoType=$null
 if($p.movements.Count){
  if($a.movement_used){return [pscustomobject]@{status='needs_clarification';narration='Your Movement is already used this turn.';state=Get-CombatPlayerState $Combat}}
  $m=$p.movements[0];$old=$a.position;$dest=if($m.method-in@('flee','escape')){'adjacent room'}elseif($m.destination){$m.destination}else{'across room'}
  if($m.method-eq'misty step'){$a.position=$dest}
  elseif($a.effects.Contains('shadow_bound')){$check=Resolve-Check -DC 10 -SkillModifier 3 -FixedRoll $(if($null-ne$FixedCreativeRoll){$FixedCreativeRoll}else{Get-CombatRoll $Combat 20});$rolls.Add($check);if($check.Degree-notin@('Failure','Severe Failure')){$a.position=$dest};$a.effects.Remove('shadow_bound')}
  else{$a.position=$dest}
  $a.movement_used=$true;$positions.Add([pscustomobject]@{id='armand';from=$old;to=$a.position})
  if($dest-eq'adjacent room'){
   foreach($e in @(Get-LiveEnemies $Combat|Where-Object{$_.engaged_targets.Contains('armand')})){$atk=Resolve-CombatAttack $Combat $e $a $e.attack_bonus $e.damage_die $e.damage_bonus 'Opportunity Attack';$rolls.Add($atk);$events.Add($(if($atk.hit){"$($e.name) catches Armand leaving for $($atk.damage) damage."}else{"$($e.name) misses an opportunity attack as Armand escapes."}));$e.pursuit=if($e.tier-eq'initiate'-and$e.hp-le2){'retreat'}elseif($e.tier-eq'adept'){'orders_pursuit'}else{'pursuing'}}
   $events.Add('Armand reaches the adjacent room; hiding now requires his Action.')
  }else{$events.Add("Armand moves from $old to $($a.position).")}
 }
 if($p.bonus_action-and$p.bonus_action.command_type-eq'minor'){$a.bonus_action_used=$true;$guillermoType='minor';$Combat.combatants.guillermo.position='nearby cover';$events.Add("Guillermo $($p.bonus_action.command.Trim('.')); this uses Armand's Bonus Action.")}
 if($p.actions.Count){if($a.action_used){return [pscustomobject]@{status='needs_clarification';narration='Your Action is already used this turn.';state=Get-CombatPlayerState $Combat}};$act=$p.actions[0];$a.action_used=$true
  if($act.kind-in@('eldritch blast','fire bolt','blast','attack')){$target=Get-TargetEnemy $Combat $Text;$mode=if($Combat.darkness.active-and$a.position-eq$Combat.darkness.position){'advantage'}else{'normal'};if($null-ne$FixedAttackRoll){$saved=$Combat.RollIndex;$Combat.Seed=[int]$FixedAttackRoll-7920;$Combat.RollIndex=0};$atk=Resolve-CombatAttack $Combat $a $target 5 10 0 $(if($act.kind-eq'fire bolt'){'Fire Bolt'}else{'Eldritch Blast'}) $mode;if($null-ne$FixedAttackRoll){$atk.roll=[int]$FixedAttackRoll;$atk.total=[int]$FixedAttackRoll+5;$atk.hit=$atk.total-ge$target.ac;if($atk.hit){$d=if($null-ne$FixedDamageRoll){[int]$FixedDamageRoll}else{Get-CombatRoll $Combat 10};$atk.damage=$d;$atk.hp_change=Apply-CombatDamage $target $d}};$rolls.Add($atk);$events.Add($(if($atk.hit){"$($atk.label) hits $($target.name) for $($atk.damage) damage."}else{"$($atk.label) misses $($target.name)."}));if(-not$target.alive){Resolve-EnemyDefeat $Combat $target}}
  elseif($act.kind-in@('cast darkness','darkness')){$Combat.darkness.active=$true;$Combat.darkness.position=$a.position;$a.effects.Add('devils_sight');$events.Add("Magical darkness fills $($a.position). Armand sees through it; enemies must adapt or attack at disadvantage.")}
  elseif($act.kind-eq'hide'){$roll=if($null-ne$FixedHideRoll){[int]$FixedHideRoll}else{Get-CombatRoll $Combat 20};$total=$roll+5;$dc=((Get-LiveEnemies $Combat|Measure-Object passive_perception -Maximum).Maximum);$rolls.Add([pscustomobject]@{label='Stealth';roll=$roll;total=$total;dc=$dc;degree=Get-DegreeFromMargin ($total-$dc)});if($a.position-eq'adjacent room'-and$total-ge$dc){$Combat.active=$false;$Combat.end_reason='escaped_and_hidden';$Combat.layer='stealth';$events.Add('Armand disappears into cover in the next room. Pursuit loses him and combat gives way to stealth.')}else{$events.Add("Armand fails to break the enemies' awareness.")}}
  elseif($act.kind-eq'guillermo_consequential'){$guillermoType='consequential';$target=Get-TargetEnemy $Combat $Text;$target.effects.Add('distracted');$events.Add("Guillermo changes the tactical state by $($act.text.Trim('.')); this consumes Armand's Action.")}
  else{$key=$act.text.ToLowerInvariant();if($Combat.creative_history.Contains($key)){$events.Add('The unchanged maneuver offers no free reroll; the enemy is ready for it.')}else{$r=if($null-ne$FixedCreativeRoll){[int]$FixedCreativeRoll}else{Get-CombatRoll $Combat 20};$skill=if($act.kind-match'shove|overturn'){'Athletics'}elseif($act.kind-match'bluff|intimidate'){'Influence'}else{'Finesse'};$mod=@{Athletics=0;Influence=5;Finesse=3}[$skill];$check=Resolve-Check -DC 10 -SkillModifier $mod -FixedRoll $r;$Combat.creative_history[$key]=$check.Degree;$rolls.Add([pscustomobject]@{label=$skill;roll=$r;degree=$check.Degree;total=$check.Total;dc=10});$target=Get-TargetEnemy $Combat $Text;switch($check.Degree){'Exceptional Success'{$target.effects.Add('prone');$target.effects.Add('disadvantaged');$events.Add("The maneuver decisively knocks $($target.name) prone and opens the position.")}'Success'{$target.effects.Add('disadvantaged');$events.Add("The maneuver disrupts $($target.name)'s position.")}'Setback'{$target.effects.Add('disadvantaged');$a.effects.Add('exposed');$events.Add('It works, but Armand loses cover in the exchange.')}'Failure'{$events.Add('The maneuver has no tactical effect.')}'Severe Failure'{$a.position='exposed';$events.Add('Armand overcommits and ends exposed.')}}}}
 }
 if(-not$p.actions.Count-and-not$p.movements.Count-and-not$p.bonus_action){return [pscustomobject]@{status='needs_clarification';narration='Describe one Movement, one Action, or a Guillermo command.';parsed=$p;state=Get-CombatPlayerState $Combat}}
 if($Combat.active-and-not$Combat.reaction_prompt){foreach($line in @(Invoke-RemainingCombatants $Combat)){if($line){$events.Add($line)}}};$watch.Stop();$next=if($Combat.active){$Combat.combatants[$Combat.active_combatant].name}else{'Combat ended'};$events.Add("Armand is at $($a.position). Next: $next.");$feedback=if($rolls.Count){$r=$rolls[0];$label=if($r.PSObject.Properties['label']){$r.label}else{'Movement'};"🎲 $label • $(if($r.PSObject.Properties['hit']){if($r.hit){'Success'}else{'Failure'}}elseif($r.PSObject.Properties['degree']){$r.degree}else{'Resolved'})"}else{$null}
 $entry=[pscustomobject]@{raw_player_command=$Text;parsed_movement=@($p.movements);parsed_action=@($p.actions);parsed_bonus_action=$p.bonus_action;validation=$v;initiative=@($Combat.initiative_order);rolls=@($rolls);position_changes=@($positions);guillermo_command_type=$guillermoType;reaction_use=$null;combat_end_reason=$Combat.end_reason;turn_latency_seconds=$watch.Elapsed.TotalSeconds;narration_retry=$false;narration_fallback=$false};$Combat.telemetry.Add($entry)
 [pscustomobject]@{status=$(if($Combat.reaction_prompt){'reaction_required'}else{'resolved'});narration=@($events)-join' ';roll_feedback=$feedback;parsed=$p;telemetry=$entry;state=Get-CombatPlayerState $Combat}
}
function Get-CombatPlayerState {param($Combat)$list=@($Combat.combatants.Values|ForEach-Object{[pscustomobject]@{id=$_.id;name=$_.name;side=$_.side;hp=$_.hp;max_hp=$_.max_hp;temp_hp=$_.temp_hp;alive=$_.alive;incapacitated=$_.incapacitated;position=$_.position;engaged_targets=@($_.engaged_targets);movement_used=$_.movement_used;action_used=$_.action_used;bonus_action_used=$_.bonus_action_used;reaction_available=$_.reaction_available;effects=@($_.effects);awareness=$_.awareness;pursuit=$_.pursuit}});[pscustomobject]@{active=$Combat.active;encounter_id=$Combat.encounter_id;encounter_name=$Combat.encounter_name;initiative_order=@($Combat.initiative_order);active_combatant=$Combat.active_combatant;turn_number=$Combat.turn_number;combatants=$list;darkness=[pscustomobject]@{active=$Combat.darkness.active;position=$Combat.darkness.position};tutorial_required=$Combat.tutorial_required;reaction_prompt=$Combat.reaction_prompt;end_reason=$Combat.end_reason;layer=$Combat.layer;turn_budget=$(if($Combat.active_combatant-eq'armand'){[pscustomobject]@{movement=$(if($Combat.combatants.armand.movement_used){'Used'}else{'Available'});action=$(if($Combat.combatants.armand.action_used){'Used'}else{'Available'});bonus_action=$(if($Combat.combatants.armand.bonus_action_used){'Used'}else{'Available'})}}else{$null})}}
function Dismiss-CombatTutorial {param($Combat)$Combat.tutorial_required=$false}
Export-ModuleMember -Function New-CombatSession,Get-CombatPlayerState,ConvertFrom-CombatCommand,Test-CombatCommand,Invoke-CombatCommand,Invoke-CombatReaction,Invoke-EnemyTurn,Complete-CombatIfEnded,Resolve-EnemyDefeat,Dismiss-CombatTutorial,Apply-CombatDamage,Resolve-CombatAttack,Grant-DarkOnesBlessing
