Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'VerticalSlice.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'Resolution.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPacket.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPrompt.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationValidation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CommaHarness.psm1') -Force

function Read-HouseContent {param([string]$Root=(Split-Path -Parent $PSScriptRoot))Get-Content -Raw (Join-Path $Root 'content/full_house.json')|ConvertFrom-Json}
function New-HouseSession {
 param([string]$Root=(Split-Path -Parent $PSScriptRoot),[int]$Seed=6001)$s=New-CallumStudySession $Root;$h=Read-HouseContent $Root;$state=$s.State
 $state.Notebook.Locations=[ordered]@{};$state.Player.Location=$h.start_location;$state.Guillermo.Location=$h.start_location
 foreach($room in $h.rooms){if($state.Locations.Contains($room.id)){$state.Locations[$room.id].DisplayName=$room.name;$state.Locations[$room.id].Exits=@($room.exits)}else{Add-LocationState $state $room.id @() @($room.exits) $room.name};foreach($spec in @($room.objects)){if(-not$state.Items.Contains([string]$spec[0])){Add-ItemState $state ([string]$spec[0]) $room.id $null @{} @('prop') ([string]$spec[1]) @($spec[2]) @() 'static-renderable'};$state.Locations[$room.id].VisibleObjects+=@([string]$spec[0])}}
 foreach($clue in $h.clues){$tiers=@($clue.tiers|ForEach-Object{[pscustomobject]@{DC=[int]$_[0];Skill=[string]$_[1];Fact=[string]$_[2]}});Add-ClueState $state $clue.id $clue.room $tiers $clue.name @($clue.referent)}
 foreach($item in $state.Items.Values){if(-not$item.PSObject.Properties['RenderClass']){$item|Add-Member RenderClass 'static-renderable'}}
 $s|Add-Member HouseContent $h;$s|Add-Member HouseSeed $Seed;$s|Add-Member HouseRollIndex 0;$s|Add-Member ExteriorTurns 0;$s|Add-Member EntryRoutesDiscovered ([Collections.Generic.List[string]]::new());$s|Add-Member EntryRoute $null;$s|Add-Member RoomVisits ([ordered]@{});$s|Add-Member AmbientIndex ([ordered]@{});$s|Add-Member Encounter ([pscustomobject]@{study_entered=$false;warning_active=$false;warning_turns_remaining=0;triggered=$false;resolved=$false;outcome=$null});$s|Add-Member Ending $h.ending
 foreach($room in $h.rooms){$s.RoomVisits[$room.id]=0;$s.AmbientIndex[$room.id]=0};$s.RoomVisits.exterior=1;$s
}
function Get-HouseRoom {param($Session,[string]$Id=$Session.State.Player.Location)@($Session.HouseContent.rooms|Where-Object{$_.id-eq$Id}|Select-Object -First 1)[0]}
function Get-HouseRoll {param($Session,[int]$Sides=20)$Session.HouseRollIndex++;[Random]::new([int]($Session.HouseSeed+$Session.HouseRollIndex*6151)).Next(1,$Sides+1)}
function Get-HouseClueCount {param($Session)@($Session.State.Clues.Values|Where-Object Discovered).Count}
function Get-HouseVisibleIds {param($Session)$room=$Session.State.Player.Location;$ids=@($Session.State.Locations[$room].VisibleObjects);if($room-eq'callum_study'-and$Session.SafeDiscovered){$ids+='wall_safe'};if($room-eq'callum_study'-and$Session.SafeOpen-and-not$Session.LeadRecovered){$ids+='burned_note'};@($ids|Select-Object -Unique)}
function Get-HouseNounTable {param($Session,[string]$Location=$Session.State.Player.Location)$ids=if($Location-eq$Session.State.Player.Location){@(Get-HouseVisibleIds $Session)}else{@($Session.State.Locations[$Location].VisibleObjects)};$rows=@($ids|ForEach-Object{$item=$Session.State.Items[$_];[pscustomobject]@{id=$item.Id;kind='object';destination=$null;display_name=$item.DisplayName;aliases=@($item.Aliases)}});$room=Get-HouseRoom $Session $Location;$rows+=[pscustomobject]@{id="location:$Location";kind='location';destination=$null;display_name=$room.name;aliases=@($Location.Replace('_',' '))};foreach($exit in @($Session.HouseContent.navigation.$Location)){$rows+=[pscustomobject]@{id="exit:$($exit.destination)";kind='exit';destination=[string]$exit.destination;display_name=[string]$exit.display_name;aliases=@($exit.aliases)}};@($rows)}
function Get-HousePlayerState {param($Session)$base=Get-SlicePlayerState $Session;$room=Get-HouseRoom $Session;$base.location=[pscustomobject]@{id=$room.id;name=$room.name};$base.visible_objects=@(Get-HouseVisibleIds $Session|ForEach-Object{$Session.State.Items[$_].DisplayName});$base|Add-Member house_state ([pscustomobject]@{entry_route=$Session.EntryRoute;entry_routes_discovered=@($Session.EntryRoutesDiscovered);clues_discovered=Get-HouseClueCount $Session;encounter=$Session.Encounter;room_overview=$room.overview;ambient=@($room.ambient);ending_reached=$Session.LeadRecovered}) -Force;$base}
function Resolve-HouseTarget {
 param($Session,[string]$Text)
 $hits=@();foreach($o in @(Get-HouseNounTable $Session|Where-Object kind -eq 'object')){$terms=@(@($o.display_name)+@($o.aliases)|Where-Object{-not[string]::IsNullOrWhiteSpace([string]$_)}|Sort-Object Length -Descending|Select-Object -Unique);foreach($term in $terms){if($Text-match('(?i)(?<![a-z])'+[regex]::Escape([string]$term)+'(?![a-z])')){$hits+=[pscustomobject]@{id=[string]$o.id;term=[string]$term;length=([string]$term).Length};break}}}
 if(-not$hits.Count){return [pscustomobject]@{status='unknown';target=$null;matched_term=$null;candidates=@()}}
 $best=[int](@($hits|Measure-Object length -Maximum).Maximum);$candidates=@($hits|Where-Object length -eq $best|Select-Object -ExpandProperty id -Unique)
 if($candidates.Count-ne1){return [pscustomobject]@{status='ambiguous';target=$null;matched_term=[string](@($hits|Where-Object length -eq $best)[0].term);candidates=$candidates}}
 $hit=@($hits|Where-Object{$_.id-eq$candidates[0]}|Sort-Object length -Descending)[0];[pscustomobject]@{status='resolved';target=$hit.id;matched_term=$hit.term;candidates=$candidates}
}
function Resolve-HouseReferent {param($Session,[string]$Text,[ValidateSet('object','exit','any')][string]$Kind='any')$hits=@();foreach($entry in @(Get-HouseNounTable $Session|Where-Object{$Kind-eq'any'-or$_.kind-eq$Kind})){$terms=@(@($entry.display_name)+@($entry.aliases)|Where-Object{$_}|Sort-Object Length -Descending|Select-Object -Unique);foreach($term in $terms){if($Text-match('(?i)(?<![a-z])'+[regex]::Escape([string]$term)+'(?![a-z])')){$hits+=[pscustomobject]@{entry=$entry;term=$term;length=([string]$term).Length};break}}};if(-not$hits.Count){return [pscustomobject]@{status='unknown';referent=$null;candidates=@()}};$best=($hits|Measure-Object length -Maximum).Maximum;$top=@($hits|Where-Object length -eq $best);if($top.Count-ne1){return [pscustomobject]@{status='ambiguous';referent=$null;candidates=@($top.entry)}};[pscustomobject]@{status='resolved';referent=$top[0].entry;candidates=@($top[0].entry)}}
function Test-HouseOverviewNounLint {param($Session)$failures=@();$allTerms=@();$nonNouns=@('around','leave','outside','exterior','upstairs','downstairs');foreach($location in @($Session.HouseContent.rooms.id)){foreach($entry in @(Get-HouseNounTable $Session $location)){foreach($term in @($entry.display_name)+@($entry.aliases)){if(([string]$term).Length-ge4-and$term-notin$nonNouns){$allTerms+=[string]$term}}}};foreach($room in $Session.HouseContent.rooms){$allowedTerms=@(Get-HouseNounTable $Session $room.id|ForEach-Object{@($_.display_name)+@($_.aliases)}|ForEach-Object{([string]$_).ToLowerInvariant()}|Select-Object -Unique);foreach($term in @($allTerms|Sort-Object Length -Descending -Unique)){if($room.overview-match('(?i)(?<![a-z])'+[regex]::Escape($term)+'(?![a-z])')-and$allowedTerms-notcontains$term.ToLowerInvariant()){$failures+=[pscustomobject]@{room=$room.id;noun=$term}}}};@($failures|Sort-Object room,noun -Unique)}
function Test-HouseNarrationVocabulary {param($Session,[string]$Text)$failures=@();foreach($location in @($Session.HouseContent.rooms.id)){foreach($entry in @(Get-HouseNounTable $Session $location)){foreach($term in @($entry.display_name)+@($entry.aliases)){if(([string]$term).Length-ge4-and$Text-match('(?i)(?<![a-z])'+[regex]::Escape([string]$term)+'(?![a-z])')){$local=Resolve-HouseReferent $Session ([string]$term) any;if($local.status-eq'unknown'){$failures+=[string]$term}}}}};@($failures|Select-Object -Unique)}
function Find-HouseTarget {param($Session,[string]$Text)$result=Resolve-HouseTarget $Session $Text;if($result.status-eq'resolved'){$result.target}}
function Test-HouseNounContract {param($Session)$failures=@();foreach($id in @(Get-HouseVisibleIds $Session)){$item=$Session.State.Items[$id];$resolved=Resolve-HouseTarget $Session "inspect $($item.DisplayName)";if($resolved.status-ne'resolved'-or$resolved.target-ne$id){$failures+=[pscustomobject]@{location=$Session.State.Player.Location;id=$id;display_name=$item.DisplayName;status=$resolved.status;candidates=@($resolved.candidates)}}};@($failures)}
function New-HouseNarrationPacket {
 param($Session,[string]$PlayerText,[string[]]$ResolvedFacts=@(),[string[]]$Events=@(),[string[]]$Ambient=@())
 $room=Get-HouseRoom $Session;if([string]::IsNullOrWhiteSpace([string]$room.overview)){throw "House authorial intent is missing for $($room.id)."};$visible=@(Get-HouseNounTable $Session)
 $known=@($Session.State.Notebook.Clues.Values|ForEach-Object{@($_.known_facts)});$passthrough=@($known)+@($ResolvedFacts)+@($Events)
 [pscustomobject]@{location=[pscustomobject]@{id=$room.id;display_name=$room.name};player_input=$PlayerText;authorial_intent=$room.overview;resolved_facts=@($ResolvedFacts);observed_facts=@($passthrough|Where-Object{$_});events=@($Events);ambient=@($Ambient);visible_referents=$visible}
}
function Invoke-HouseNarration {
 param($Session,$HousePacket,[string]$Root=(Split-Path -Parent $PSScriptRoot),[scriptblock]$Backend)
 $facts=@($HousePacket.resolved_facts)+@($HousePacket.events);if(-not$facts.Count){$facts=@('No observable change follows the attempt.')}
 $case=[pscustomobject]@{location=$HousePacket.location.display_name;time=$Session.State.Time.CurrentCaseTime.ToString('h:mm tt');weather='rain';actor='Armand';action_type='act';target=$HousePacket.player_input;degree='resolved';facts=$facts;visible=@($HousePacket.visible_referents|ForEach-Object{$_.display_name});visible_referents=@($HousePacket.visible_referents);ambient=@($HousePacket.ambient);events=@($HousePacket.events);observed_facts=@($HousePacket.observed_facts);authorial_intent=$HousePacket.authorial_intent}
 $packet=ConvertTo-NarrationPacket $case;$prompt=Build-NarrationPrompt $packet facts @();if($Backend){$generated=&$Backend $prompt 0}else{$work=Join-Path $Root 'eval/.work';New-Item -ItemType Directory -Force $work|Out-Null;$path=Join-Path $work "house_narrator_$([guid]::NewGuid().ToString('N')).txt";$prompt|Set-Content -NoNewline -Encoding utf8 $path;$generated=Invoke-CommaGeneration $path (Join-Path $Root 'config.json') -Seed (16000+$Session.State.Time.Turn) -Temperature .15 -MaxTokens 180}
 $raw=[string]$(if($generated-is[string]){$generated}elseif($generated.PSObject.Properties['Text']){$generated.Text}else{$generated.RawOutput});$text=if($raw.TrimStart()-match'(?i)^You\b'){$raw.Trim()}else{'You '+$raw.Trim()};$validation=Test-NarrationOutput $text @() 180 Armand;$nounErrors=@(Test-HouseNarrationVocabulary $Session $text);if(-not$validation.Passed-or$nounErrors.Count){$baseErrors=if($validation.PSObject.Properties['Errors']){@($validation.Errors)}else{@()};throw "House narration validation failed: $(@($baseErrors)+$nounErrors-join'; ')"};[pscustomobject]@{text=$text;prompt=$prompt;packet=$packet;validation=$validation}
}
function Get-HouseAmbient {param($Session)$room=Get-HouseRoom $Session;$i=[int]$Session.AmbientIndex[$room.id];$Session.AmbientIndex[$room.id]=$i+1;if($room.ambient.Count){[string]$room.ambient[$i%$room.ambient.Count]}else{''}}
function Test-HouseEncounterTrigger {param($Session,[bool]$CountDown=$true)$e=$Session.Encounter;if($e.triggered-or$e.resolved){return [pscustomobject]@{warning=$false;start_combat=$false}};if($Session.State.Player.Location-eq'callum_study'){$e.study_entered=$true};if(-not$e.warning_active-and$e.study_entered-and(Get-HouseClueCount $Session)-ge3-and$Session.State.Player.Location-ne'cellar'){$e.warning_active=$true;$e.warning_turns_remaining=1;return [pscustomobject]@{warning=$true;start_combat=$false}};if($e.warning_active-and$CountDown){$e.warning_turns_remaining--;if($e.warning_turns_remaining-le0){$e.triggered=$true;$e.warning_active=$false;return [pscustomobject]@{warning=$false;start_combat=$true}}};[pscustomobject]@{warning=$false;start_combat=$false}}
function Resolve-HouseClues {param($Session,[string]$Target,[string]$Text)$state=$Session.State;$matches=@($state.Clues.Values|Where-Object{$_.Location-eq$state.Player.Location-and(@($_.RelatedEntityIds)-contains$Target)});$facts=[Collections.Generic.List[string]]::new();$rollFeedback=$null;foreach($clue in $matches){$passive=Resolve-ClueInterpretation $state $clue.Id Awareness 13;foreach($f in @($passive.NewFacts)){$facts.Add($f)};if($Text-match'(?i)investigate|study|analyze|analyse|read closely|occult|knowledge'){$skill=if($Text-match'(?i)occult|magic'){'Occult'}elseif($Text-match'(?i)history|knowledge'){'Knowledge'}else{'Investigation'};$mod=[int]$state.Player.Skills[$skill];$roll=Get-HouseRoll $Session;$active=Resolve-ClueInterpretation $state $clue.Id $skill ($roll+$mod);foreach($f in @($active.NewFacts)){$facts.Add($f)};$degree=Get-DegreeFromMargin (($roll+$mod)-15);$rollFeedback="🎲 $skill • $degree"};if($state.Notebook.Clues.Contains($clue.Id)){Visit-NotebookLocation $state $state.Player.Location (Get-HouseRoom $Session).name @() @($clue.Id)|Out-Null}};[pscustomobject]@{facts=@($facts);roll_feedback=$rollFeedback;matched=$matches.Count}}
function Move-HousePlayer {param($Session,[string]$Destination)$state=$Session.State;$room=Get-HouseRoom $Session;if(@($room.exits)-notcontains$Destination){return $false};$state.Player.Location=$Destination;$state.Guillermo.Location=$Destination;$Session.RoomVisits[$Destination]=[int]$Session.RoomVisits[$Destination]+1;Add-GameTime $state 1 1;Visit-NotebookLocation $state $Destination (Get-HouseRoom $Session $Destination).name @()|Out-Null;$true}
function Invoke-HouseTurn {
 param($Session,[string]$Text,[switch]$Narrate,[scriptblock]$NarratorBackend)$raw=$Text.Trim();$state=$Session.State;$room=Get-HouseRoom $Session;$events=[Collections.Generic.List[string]]::new();$feedback=$null;$startCombat=$false;$status='resolved';$beforeClues=Get-HouseClueCount $Session
 if($Session.Encounter.warning_active-and$raw-match'(?i)\b(?:hide|sneak|slip away|bluff|call out|intimidate|leave|flee|escape)\b'){$Session.Encounter.warning_active=$false;$Session.Encounter.resolved=$true;$Session.Encounter.outcome=if($raw-match'(?i)hide|sneak|slip'){'stealth'}elseif($raw-match'(?i)bluff|call out|intimidate'){'social'}else{'evasion'};$events.Add("Armand uses the warning to avoid open contact. The footsteps pass without becoming a fight.")}
 elseif($raw-match'(?i)\b(?:look around|survey|take in|where am i)\b'){$events.Add([string]$room.overview);$events.Add((Get-HouseAmbient $Session))}
 elseif($room.id-eq'exterior'-and$raw-match'(?i)\b(?:circle|around|side of|follow the tracks|follow tracks)\b'){foreach($id in 'kitchen','cellar'){if(-not$Session.EntryRoutesDiscovered.Contains($id)){$Session.EntryRoutesDiscovered.Add($id)}};$events.Add('Circling the house reveals a kitchen door and an ajar outer cellar door. Both routes are reachable from the rain-dark side path.');Add-GameTime $state 1 1}
 elseif($raw-match'(?i)\b(?:go|move|walk|run|enter|head|climb|leave|through|upstairs|downstairs)\b|^\s*(?:up|down)\s*$'){$exit=Resolve-HouseReferent $Session $raw exit;$destination=if($exit.status-eq'resolved'){$exit.referent.destination}else{$null};if($room.id-eq'exterior'-and$raw-match'(?i)front door'){$events.Add('The front door remains locked. The paths continue around either side of the house.')}elseif($destination){if(Move-HousePlayer $Session $destination){if($room.id-eq'exterior'){$Session.EntryRoute=$destination};$new=Get-HouseRoom $Session;$events.Add("Armand enters $($new.name). $($new.overview)");$events.Add((Get-HouseAmbient $Session))}}else{$status='needs_clarification';$events.Add('Which connected room or visible route do you want Armand to take?')}}
 elseif($raw-match'(?i)\b(?:ask|tell|send|have)\s+guillermo\b'){$events.Add([string]$room.guillermo);$target=Find-HouseTarget $Session $raw;if(-not$target){$target=if($room.id-eq'exterior'){'mailbox'}else{@($state.Locations[$room.id].VisibleObjects)[0]}};$clues=Resolve-HouseClues $Session $target 'examine';foreach($f in $clues.facts){$events.Add("Armand follows Guillermo and looks for himself: $f")};if($target-eq'large_painting'){$Session.SafeDiscovered=$true;$events.Add('Following Guillermo to the painting exposes the safe behind it.')};Add-GameTime $state 1 1}
 else{$resolution=Resolve-HouseTarget $Session $raw;$target=$resolution.target;if($resolution.status-eq'ambiguous'){$status='needs_clarification';$names=@($resolution.candidates|ForEach-Object{$state.Items[$_].DisplayName});$events.Add("Which $($resolution.matched_term) do you mean: $($names -join ' or ')?")}elseif(-not$target){$status='needs_clarification';$events.Add('Armand cannot identify that object here. Name something visible in the room.')}else{$clues=Resolve-HouseClues $Session $target $raw;$feedback=$clues.roll_feedback;if($clues.facts.Count){foreach($f in $clues.facts){$events.Add($f)}}else{$mundane=$room.mundane.PSObject.Properties[$target];if($mundane){$events.Add([string]$mundane.Value)}else{$events.Add("Armand examines the $($state.Items[$target].DisplayName). It yields no additional evidence.")}};Add-GameTime $state 1 1;if($target-in@('large_painting','paneled_wall')){$Session.SafeDiscovered=$true;$events.Add('The shifted painting and panel line expose a fixed iron safe.')};if($target-eq'wall_safe'-and($raw-match'08[- /]?10[- /]?83|photograph|front page|date')){$Session.SafeDiscovered=$true;$Session.SafeOpen=$true;$events.Add('The date 08-10-83 opens the safe.')};if($target-eq'burned_note'-and$Session.SafeOpen){$Session.LeadRecovered=$true;$lead=Resolve-ClueInterpretation $state external_lead Investigation 10;foreach($f in $lead.NewFacts){$events.Add($f)};$events.Add([string]$Session.Ending.text)}}}
 if($room.id-eq'exterior'){$Session.ExteriorTurns++;if($Session.ExteriorTurns-ge3-and-not$Session.EntryRoutesDiscovered.Count){$events.Add('Rainwater gathers in the wheel ruts and runs toward the side of the house, where the ground disappears around the wall.')}}
 $trigger=Test-HouseEncounterTrigger $Session (-not($events.Count-and$events[0]-match'cellar door, then footsteps'));if($trigger.warning){$events.Add('A cellar door shifts below; footsteps follow under the floorboards. Guillermo goes rigid and stares toward the sound.')};if($trigger.start_combat){$events.Add('The warning closes into contact. Two cultists enter the house.');$startCombat=$true}
 while($events.Count-lt2){$ambient=Get-HouseAmbient $Session;if($ambient){$events.Add($ambient)}else{$events.Add('The house remains still around Armand.')}}
 $ambientLines=@($events|Where-Object{$_-and@($room.ambient)-contains[string]$_});$eventLines=@($events|Where-Object{$_-and@($room.ambient)-notcontains[string]$_});$packet=New-HouseNarrationPacket $Session $raw $eventLines @() $ambientLines
 $rendered=$null;if($Narrate){$rendered=Invoke-HouseNarration $Session $packet (Split-Path -Parent $PSScriptRoot) $NarratorBackend};[pscustomobject]@{status=$status;narration=$(if($rendered){$rendered.text}else{@($events|Where-Object{$_})-join' '});narration_source=$(if($rendered){'comma'}else{'engine_test'});narration_prompt=$(if($rendered){$rendered.prompt}else{$null});narration_packet=$packet;roll_feedback=$feedback;start_combat=$startCombat;clues_added=(Get-HouseClueCount $Session)-$beforeClues;state=Get-HousePlayerState $Session}
}
function Export-HouseSave {param($Session)$clues=[ordered]@{};foreach($c in $Session.State.Clues.Values){if($c.Discovered){$clues[$c.Id]=[pscustomobject]@{facts=@($c.KnownFacts);tier=$c.HighestTierReached}}};$snapshot=[ordered]@{version=1;location=$Session.State.Player.Location;turn=$Session.State.Time.Turn;elapsed_minutes=$Session.State.Time.ElapsedMinutes;entry_route=$Session.EntryRoute;entry_routes=@($Session.EntryRoutesDiscovered);room_visits=$Session.RoomVisits;ambient_index=$Session.AmbientIndex;encounter=$Session.Encounter;safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;lead_recovered=$Session.LeadRecovered;persistent_environment=@($Session.PersistentEnvironment);clues=$clues;theories=$Session.State.Notebook.Theories};ConvertTo-StableStateJson $snapshot 20}
function Import-HouseSave {param([string]$Root,[string]$Json)$data=$Json|ConvertFrom-Json;$s=New-HouseSession $Root;$s.State.Player.Location=$data.location;$s.State.Guillermo.Location=$data.location;$s.State.Time.Turn=[int]$data.turn;$s.State.Time.ElapsedMinutes=[int]$data.elapsed_minutes;$s.EntryRoute=$data.entry_route;foreach($x in @($data.entry_routes)){if(-not[string]::IsNullOrWhiteSpace([string]$x)){$s.EntryRoutesDiscovered.Add([string]$x)}};foreach($p in $data.room_visits.PSObject.Properties){$s.RoomVisits[$p.Name]=[int]$p.Value};foreach($p in $data.ambient_index.PSObject.Properties){$s.AmbientIndex[$p.Name]=[int]$p.Value};foreach($p in $data.encounter.PSObject.Properties){$s.Encounter.($p.Name)=$p.Value};$s.SafeDiscovered=[bool]$data.safe_discovered;$s.SafeOpen=[bool]$data.safe_open;$s.LeadRecovered=[bool]$data.lead_recovered;foreach($x in @($data.persistent_environment)){if($null-ne$x){$s.PersistentEnvironment.Add($x)}};foreach($p in $data.clues.PSObject.Properties){$c=$s.State.Clues[$p.Name];$c.Discovered=$true;$c.HighestTierReached=$p.Value.tier;foreach($f in @($p.Value.facts)){$c.KnownFacts.Add([string]$f)};Sync-NotebookClue $s.State $c.Id $c.DisplayName $c.RelatedEntityIds|Out-Null};$s}
Export-ModuleMember -Function Read-HouseContent,New-HouseSession,Get-HouseVisibleIds,Get-HouseNounTable,Get-HousePlayerState,Resolve-HouseTarget,Resolve-HouseReferent,Find-HouseTarget,Test-HouseNounContract,Test-HouseOverviewNounLint,Test-HouseNarrationVocabulary,New-HouseNarrationPacket,Invoke-HouseNarration,Invoke-HouseTurn,Get-HouseClueCount,Test-HouseEncounterTrigger,Export-HouseSave,Import-HouseSave
