Set-StrictMode -Version Latest

function New-NotebookState {
 [pscustomobject]@{Clues=[ordered]@{};Characters=[ordered]@{};Locations=[ordered]@{};Theories=[ordered]@{}}
}
function Get-NotebookTurn {param($State)[int]$State.Time.Turn}
function Add-UniqueText {param($List,[string]$Text)if(-not[string]::IsNullOrWhiteSpace($Text)-and-not$List.Contains($Text)){$List.Add($Text);$true}else{$false}}
function Sync-NotebookClue {
 param($State,[string]$ClueId,[string]$DisplayName=$ClueId,[string[]]$RelatedEntityIds=@())
 if(-not$State.Clues.Contains($ClueId)){throw "Unknown clue: $ClueId"};$clue=$State.Clues[$ClueId]
 if(-not$clue.Discovered){return $null};$turn=Get-NotebookTurn $State
 if(-not$State.Notebook.Clues.Contains($ClueId)){$State.Notebook.Clues[$ClueId]=[pscustomobject]@{clue_id=$ClueId;display_name=$DisplayName;discovered=$true;source_location=$clue.Location;interpretation_tier_reached=$clue.HighestTierReached;known_facts=[Collections.Generic.List[string]]::new();first_discovered_turn=$turn;last_updated_turn=$turn;player_note=$null;related_entity_ids=@($RelatedEntityIds)}}
 $entry=$State.Notebook.Clues[$ClueId];$changed=$false
 foreach($fact in @($clue.KnownFacts)){if(Add-UniqueText $entry.known_facts ([string]$fact)){$changed=$true}}
 if($entry.interpretation_tier_reached-ne$clue.HighestTierReached){$entry.interpretation_tier_reached=$clue.HighestTierReached;$changed=$true}
 if($changed){$entry.last_updated_turn=$turn};$entry
}
function Set-NotebookClueNote {param($State,[string]$ClueId,[AllowNull()][string]$Note)if(-not$State.Notebook.Clues.Contains($ClueId)){throw "Cannot note unknown Notebook clue: $ClueId"};$State.Notebook.Clues[$ClueId].player_note=$Note;$State.Notebook.Clues[$ClueId].last_updated_turn=Get-NotebookTurn $State}
function Add-NotebookCharacter {param($State,[string]$CharacterId,[string]$DisplayName,[string]$EncounteredLocation,[string[]]$KnownFacts=@(),[string[]]$KnownRelationship=@())$turn=Get-NotebookTurn $State;if(-not$State.Notebook.Characters.Contains($CharacterId)){$State.Notebook.Characters[$CharacterId]=[pscustomobject]@{character_id=$CharacterId;display_name=$DisplayName;known_facts=[Collections.Generic.List[string]]::new();known_relationship=[Collections.Generic.List[string]]::new();first_encountered_location=$EncounteredLocation;first_encountered_turn=$turn;last_updated_turn=$turn;important=$false;player_note=$null}};$entry=$State.Notebook.Characters[$CharacterId];foreach($fact in $KnownFacts){Add-UniqueText $entry.known_facts $fact|Out-Null};foreach($fact in $KnownRelationship){Add-UniqueText $entry.known_relationship $fact|Out-Null};$entry.last_updated_turn=$turn;$entry}
function Add-NotebookCharacterFact {param($State,[string]$CharacterId,[string]$Fact,[switch]$Relationship)if(-not$State.Notebook.Characters.Contains($CharacterId)){throw "Unknown Notebook character: $CharacterId"};$entry=$State.Notebook.Characters[$CharacterId];if($Relationship){Add-UniqueText $entry.known_relationship $Fact|Out-Null}else{Add-UniqueText $entry.known_facts $Fact|Out-Null};$entry.last_updated_turn=Get-NotebookTurn $State}
function Set-NotebookCharacterImportant {param($State,[string]$CharacterId,[bool]$Important)if(-not$State.Notebook.Characters.Contains($CharacterId)){throw "Unknown Notebook character: $CharacterId"};$State.Notebook.Characters[$CharacterId].important=$Important;$State.Notebook.Characters[$CharacterId].last_updated_turn=Get-NotebookTurn $State}
function Set-NotebookCharacterNote {param($State,[string]$CharacterId,[AllowNull()][string]$Note)if(-not$State.Notebook.Characters.Contains($CharacterId)){throw "Unknown Notebook character: $CharacterId"};$State.Notebook.Characters[$CharacterId].player_note=$Note;$State.Notebook.Characters[$CharacterId].last_updated_turn=Get-NotebookTurn $State}
function Visit-NotebookLocation {param($State,[string]$LocationId,[string]$DisplayName,[string[]]$KnownFeatures=@(),[string[]]$DiscoveryIds=@())$turn=Get-NotebookTurn $State;if(-not$State.Notebook.Locations.Contains($LocationId)){$State.Notebook.Locations[$LocationId]=[pscustomobject]@{location_id=$LocationId;display_name=$DisplayName;visited=$true;known_features=[Collections.Generic.List[string]]::new();discovery_ids=[Collections.Generic.List[string]]::new();first_visited_turn=$turn;last_updated_turn=$turn;player_note=$null}};$entry=$State.Notebook.Locations[$LocationId];foreach($x in $KnownFeatures){Add-UniqueText $entry.known_features $x|Out-Null};foreach($x in $DiscoveryIds){if($State.Notebook.Clues.Contains($x)){Add-UniqueText $entry.discovery_ids $x|Out-Null}};$entry.last_updated_turn=$turn;$entry}
function Set-NotebookLocationNote {param($State,[string]$LocationId,[AllowNull()][string]$Note)if(-not$State.Notebook.Locations.Contains($LocationId)){throw "Unknown Notebook location: $LocationId"};$State.Notebook.Locations[$LocationId].player_note=$Note;$State.Notebook.Locations[$LocationId].last_updated_turn=Get-NotebookTurn $State}
function New-NotebookTheory {param($State,[string]$TheoryId,[string]$Title,[string]$Body,[ValidateSet('active','discarded')][string]$Status='active')if($State.Notebook.Theories.Contains($TheoryId)){throw "Theory already exists: $TheoryId"};$turn=Get-NotebookTurn $State;$entry=[pscustomobject]@{theory_id=$TheoryId;title=$Title;body=$Body;linked_clue_ids=[Collections.Generic.List[string]]::new();linked_character_ids=[Collections.Generic.List[string]]::new();linked_location_ids=[Collections.Generic.List[string]]::new();created_turn=$turn;updated_turn=$turn;status=$Status;classification='player_belief'};$State.Notebook.Theories[$TheoryId]=$entry;$entry}
function Update-NotebookTheory {param($State,[string]$TheoryId,[string]$Title,[string]$Body,[ValidateSet('active','discarded')][string]$Status)if(-not$State.Notebook.Theories.Contains($TheoryId)){throw "Unknown theory: $TheoryId"};$entry=$State.Notebook.Theories[$TheoryId];if($PSBoundParameters.ContainsKey('Title')){$entry.title=$Title};if($PSBoundParameters.ContainsKey('Body')){$entry.body=$Body};if($PSBoundParameters.ContainsKey('Status')){$entry.status=$Status};$entry.updated_turn=Get-NotebookTurn $State;$entry}
function Add-NotebookTheoryLink {param($State,[string]$TheoryId,[ValidateSet('clue','character','location')][string]$EntityType,[string]$EntityId)if(-not$State.Notebook.Theories.Contains($TheoryId)){throw "Unknown theory: $TheoryId"};$collection=switch($EntityType){clue{$State.Notebook.Clues}character{$State.Notebook.Characters}location{$State.Notebook.Locations}};if(-not$collection.Contains($EntityId)){throw "Cannot link unknown Notebook ${EntityType}: $EntityId"};$property="linked_${EntityType}_ids";Add-UniqueText $State.Notebook.Theories[$TheoryId].$property $EntityId|Out-Null;$State.Notebook.Theories[$TheoryId].updated_turn=Get-NotebookTurn $State}
function Get-NotebookConfig {param([string]$Path=(Join-Path (Split-Path -Parent $PSScriptRoot) 'notebook_config.json'))Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json}
function Get-NotebookRelevance {
 param($State,[string]$CurrentLocation,[string]$TargetId,[string[]]$RelatedEntityIds=@(),[string[]]$SearchTerms=@(),[Nullable[int]]$MaxEntries,[switch]$DebugScores)
 $cfg=Get-NotebookConfig;$cap=if($null-ne$MaxEntries){[int]$MaxEntries}else{[int]$cfg.relevance_max_entries};$rows=[Collections.Generic.List[object]]::new();$related=@($RelatedEntityIds)
 foreach($entry in $State.Notebook.Clues.Values){$score=0;if($entry.clue_id-eq$TargetId){$score+=$cfg.scores.exact_target};if($entry.clue_id-in$related-or@($entry.related_entity_ids|Where-Object{$_-in$related}).Count){$score+=$cfg.scores.explicit_related};if($entry.source_location-eq$CurrentLocation){$score+=$cfg.scores.same_location};foreach($term in $SearchTerms){if((@($entry.known_facts)+$entry.display_name)-match[regex]::Escape($term)){$score+=$cfg.scores.search_term;break}};if($score-gt0){$rows.Add([pscustomobject]@{kind='clue';id=$entry.clue_id;display_name=$entry.display_name;known_facts=@($entry.known_facts);player_note=$entry.player_note;source_location=$entry.source_location;score=[int]$score;updated=[int]$entry.last_updated_turn})}}
 foreach($entry in $State.Notebook.Characters.Values){$score=if($entry.character_id-eq$TargetId){[int]$cfg.scores.exact_target}elseif($entry.character_id-in$related){[int]$cfg.scores.explicit_related}else{0};if($score-gt0){$rows.Add([pscustomobject]@{kind='character';id=$entry.character_id;display_name=$entry.display_name;known_facts=@($entry.known_facts)+@($entry.known_relationship);player_note=$entry.player_note;source_location=$entry.first_encountered_location;score=$score;updated=[int]$entry.last_updated_turn})}}
 foreach($entry in $State.Notebook.Locations.Values){$score=if($entry.location_id-eq$TargetId){[int]$cfg.scores.exact_target}elseif($entry.location_id-eq$CurrentLocation){[int]$cfg.scores.same_location}elseif($entry.location_id-in$related){[int]$cfg.scores.explicit_related}else{0};if($score-gt0){$rows.Add([pscustomobject]@{kind='location';id=$entry.location_id;display_name=$entry.display_name;known_facts=@($entry.known_features);player_note=$entry.player_note;source_location=$entry.location_id;score=$score;updated=[int]$entry.last_updated_turn})}}
 foreach($entry in $State.Notebook.Theories.Values){$links=@($entry.linked_clue_ids)+@($entry.linked_character_ids)+@($entry.linked_location_ids);if($TargetId-in$links-or@($related|Where-Object{$_-in$links}).Count){$rows.Add([pscustomobject]@{kind='theory';id=$entry.theory_id;display_name=$entry.title;known_facts=@();player_note=$entry.body;source_location=$null;score=[int]$cfg.scores.theory_link;updated=[int]$entry.updated_turn})}}
 $selected=@($rows|Sort-Object @{Expression='score';Descending=$true},@{Expression='updated';Descending=$true},id|Select-Object -First $cap)
 if($DebugScores){return $selected};@($selected|ForEach-Object{[pscustomobject]@{kind=$_.kind;id=$_.id;display_name=$_.display_name;known_facts=@($_.known_facts);player_note=$_.player_note;source_location=$_.source_location}})
}
function ConvertTo-NarratorNotebookEntries {param([object[]]$Entries=@())$lines=[Collections.Generic.List[string]]::new();foreach($entry in $Entries){foreach($fact in @($entry.known_facts)){$lines.Add("KNOWN FACT [$($entry.kind):$($entry.id)]: $fact")};if(-not[string]::IsNullOrWhiteSpace([string]$entry.player_note)){$label=if($entry.kind-eq'theory'){'PLAYER THEORY (belief)'}else{'PLAYER NOTE (belief)'};$lines.Add("$label [$($entry.kind):$($entry.id)]: $($entry.player_note)")}};@($lines)}
function Get-GuillermoTheoryEvidence {param($State,[string]$TheoryId,[string[]]$KnownContradictionClueIds=@())if(-not$State.Notebook.Theories.Contains($TheoryId)){throw "Unknown theory: $TheoryId"};$t=$State.Notebook.Theories[$TheoryId];$evidence=[Collections.Generic.List[object]]::new();foreach($id in @($t.linked_clue_ids)){if($State.Notebook.Clues.Contains($id)){$c=$State.Notebook.Clues[$id];$evidence.Add([pscustomobject]@{kind='clue';id=$id;known_facts=@($c.known_facts)})}};foreach($id in @($t.linked_character_ids)){if($State.Notebook.Characters.Contains($id)){$c=$State.Notebook.Characters[$id];$evidence.Add([pscustomobject]@{kind='character';id=$id;known_facts=@($c.known_facts)+@($c.known_relationship)})}};foreach($id in @($t.linked_location_ids)){if($State.Notebook.Locations.Contains($id)){$c=$State.Notebook.Locations[$id];$evidence.Add([pscustomobject]@{kind='location';id=$id;known_facts=@($c.known_features)})}};$contradictions=@($KnownContradictionClueIds|Where-Object{$State.Notebook.Clues.Contains($_)}|ForEach-Object{$c=$State.Notebook.Clues[$_];[pscustomobject]@{kind='clue';id=$_;known_facts=@($c.known_facts)}});[pscustomobject]@{theory_id=$TheoryId;player_belief=$t.body;linked_known_evidence=@($evidence);known_contradictions=$contradictions}}
function Get-PlayerFacingNotebook {param($State)($State.Notebook|ConvertTo-Json -Depth 12|ConvertFrom-Json)}

Export-ModuleMember -Function New-NotebookState,Sync-NotebookClue,Set-NotebookClueNote,Add-NotebookCharacter,Add-NotebookCharacterFact,Set-NotebookCharacterImportant,Set-NotebookCharacterNote,Visit-NotebookLocation,Set-NotebookLocationNote,New-NotebookTheory,Update-NotebookTheory,Add-NotebookTheoryLink,Get-NotebookRelevance,ConvertTo-NarratorNotebookEntries,Get-GuillermoTheoryEvidence,Get-PlayerFacingNotebook
