Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'InterpreterContext.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentInterpreter.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentSchema.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CoreEngine.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Resolution.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarratorHandoff.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPacket.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPrompt.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationValidation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CommaHarness.psm1') -Force
# Restore public commands after nested module imports replace dependency instances.
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force

function Read-SliceContent {param([string]$Root=(Split-Path -Parent $PSScriptRoot))$dir=Join-Path $Root 'content/callum_study';[pscustomobject]@{Locations=Get-Content -Raw (Join-Path $dir 'location.json')|ConvertFrom-Json;Objects=Get-Content -Raw (Join-Path $dir 'objects.json')|ConvertFrom-Json;Clues=Get-Content -Raw (Join-Path $dir 'clues.json')|ConvertFrom-Json;Slice=Get-Content -Raw (Join-Path $dir 'slice.json')|ConvertFrom-Json;Polish=Get-Content -Raw (Join-Path $dir 'polish.json')|ConvertFrom-Json;Referents=Get-Content -Raw (Join-Path $dir 'referents.json')|ConvertFrom-Json}}
function New-CallumStudySession {
 param([string]$Root=(Split-Path -Parent $PSScriptRoot))$content=Read-SliceContent $Root;$state=New-GameState
 foreach($loc in $content.Locations.locations){Add-LocationState -State $state -Id $loc.id -VisibleObjects @($loc.visible_objects) -Exits @($loc.exits) -DisplayName $loc.display_name}
 foreach($obj in $content.Objects.objects){$parts=if($obj.PSObject.Properties['parts']){@($obj.parts)}else{@()};Add-ItemState -State $state -Id $obj.id -Location $obj.location -Owner $(if($obj.PSObject.Properties['owner']){$obj.owner}else{$null}) -DisplayName $obj.name -Aliases @($obj.aliases) -InteractableParts $parts}
 foreach($clue in $content.Clues.clues){$tiers=@($clue.tiers|ForEach-Object{[pscustomobject]@{DC=[int]$_.dc;Skill=[string]$_.skill;Fact=[string]$_.fact}});Add-ClueState -State $state -Id $clue.id -Location $clue.location -Tiers $tiers -DisplayName $clue.name -RelatedEntityIds @($clue.related)}
 $state.Player.Location=$content.Slice.start_location;$state.Guillermo.Location=$content.Slice.start_location;Visit-NotebookLocation $state callum_study "Callum's Study" @('a disturbed Victorian study lit by gaslight')|Out-Null;Add-NotebookCharacter $state callum 'Callum' callum_study @('Callum is a missing occult researcher and investigator.') @('Armand came to investigate his disappearance.')|Out-Null
 [pscustomobject]@{Id=[guid]::NewGuid().ToString('N');State=$state;Content=$content;SafeDiscovered=$false;SafeOpen=$false;WindowOpen=$false;LeadRecovered=$false;HintDelivered=$false;VisitCounts=[ordered]@{callum_study=1;landing=0};InteractionCounts=[ordered]@{};CheckHistory=[ordered]@{};ReferentStates=[ordered]@{};PersistentEnvironment=[Collections.Generic.List[object]]::new();RecentReferents=@();PendingIntent=$null;History=[Collections.Generic.List[string]]::new();CreatedUtc=[datetime]::UtcNow}
}
function Get-SlicePlayerState {
 param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$visible=@($loc.VisibleObjects|Where-Object{$_-ne'wall_safe'-and$_-ne'burned_note'});if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$visible+='wall_safe'};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$visible+='burned_note'}
 [pscustomobject]@{session_id=$Session.Id;location=[pscustomobject]@{id=$loc.Id;name=$loc.DisplayName};time=$state.Time.CurrentCaseTime.ToString('h:mm tt');visible_objects=@($visible|ForEach-Object{$state.Items[$_].DisplayName});environment_changes=@($Session.PersistentEnvironment);guillermo=[pscustomobject]@{available=($state.Guillermo.Available-and$state.Guillermo.Alive);communication_tier=$state.Guillermo.CommunicationTier};slice_state=[pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;window_open=$Session.WindowOpen;ending_reached=$Session.LeadRecovered;ending_title=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_title}else{$null});ending_text=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_text}else{$null})};notebook=Get-PlayerFacingNotebook $state}
}
function Get-SliceInterpretationContext {
 param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$original=@($loc.VisibleObjects)
 try{
  if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('wall_safe')};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('burned_note')}
  $context=New-InterpretationContext $state $Session.RecentReferents;$entities=[Collections.Generic.List[object]]::new();foreach($entity in $context.Entities){$authored=@($Session.Content.Objects.objects|Where-Object{$_.id-eq$entity.Id}|Select-Object -First 1);if($authored.Count-and$authored[0].PSObject.Properties['capabilities']){$entity.Capabilities=@($authored[0].capabilities)};$entities.Add($entity)}
  foreach($ref in $Session.Content.Referents.referents){$available=switch -Regex ([string]$ref.trigger){'^always$'{$true;break}'^clue:(.+)$'{$state.Notebook.Clues.Contains($Matches[1]);break}'^session:safe_discovered$'{$Session.SafeDiscovered;break}'^session:(.+)$'{$Session.ReferentStates.Contains($Matches[1])-or$state.Notebook.Clues.Contains($Matches[1]);break}default{$false}};if($available-and-not@($entities.Id).Contains([string]$ref.id)){$entities.Add((New-EntityReference $ref.id subfeature $ref.display_name @($ref.aliases) @() @($ref.capabilities) $ref.parent $ref.lifecycle))}}
  $context.Entities=@($entities);$context.RecentReferents=@($Session.RecentReferents|Where-Object{@($context.Entities.Id)-contains$_});$context
 }finally{$loc.VisibleObjects=$original}
}
function Find-SliceTarget {
 param([string]$Text,$Context)$hits=@()
 foreach($entity in $Context.Entities){foreach($name in @($entity.DisplayName)+@($entity.Aliases)|Sort-Object Length -Descending -Unique){if($entity.Id-eq'study_room'-and$name-eq'study'-and$Text-match'(?i)\bstudy\s+(?:the|a|an|that|this|it)\b'){continue};if(-not[string]::IsNullOrWhiteSpace($name)-and$Text-match('(?i)(?<![\p{L}\p{N}])'+[regex]::Escape($name)+'(?![\p{L}\p{N}])')){$hits+=[pscustomobject]@{Id=$entity.Id;Alias=$name;Length=$name.Length};break}}}
 if(-not$hits.Count){return [pscustomobject]@{Target=$null;Candidates=@();Alias=$null}}
 $max=($hits|Measure-Object Length -Maximum).Maximum;$best=@($hits|Where-Object Length -eq $max);[pscustomobject]@{Target=$(if(@($best.Id|Select-Object -Unique).Count-eq1){$best[0].Id}else{$null});Candidates=@($best.Id|Select-Object -Unique);Alias=$best[0].Alias}
}
function New-SliceIntentResult {
 param([string]$Text,[string]$Actor,[string]$Action,$Target,$Method,$Spell,$Area,$Purpose,$SecondaryTarget,[string[]]$Modifiers=@(),$Alias,[bool]$RecentUsed=$false)
 [pscustomobject]@{Status='RESOLVED';OutcomeCategory='MEANINGFUL';Intent=[pscustomobject]@{actor=$Actor.ToLowerInvariant();action=$Action;target=$Target;secondary_target=$SecondaryTarget;method=$Method;area=$Area;communicative_intent=$null;spell=$Spell;purpose=$Purpose;modifiers=@($Modifiers);raw_input=$Text};Reason=$null;Clarification=$null;AliasesMatched=@($(if($Alias){$Alias}));RecentReferentUsed=$RecentUsed;RoutingFamily=$Action;RawModelStructuredOutput='slice_semantic_route';ElapsedSeconds=0.0}
}
function New-SliceClarification {param([string]$Reason,[string]$Text,[string[]]$Candidates=@())$labels=@($Candidates|ForEach-Object{$_-replace'_',' '});[pscustomobject]@{Status='NEEDS_CLARIFICATION';OutcomeCategory='AMBIGUOUS';Intent=$null;Reason=$Reason;Clarification=$(if($Reason-eq'ambiguous_marks'){"Which marks do you mean, the scorch marks by the hearth or the dark stain by the rug?"}elseif($labels.Count){"Which do you mean: $($labels-join', ')?"}else{$Text});AliasesMatched=@();RecentReferentUsed=$false;RoutingFamily=$null;RawModelStructuredOutput='slice_semantic_clarification';ElapsedSeconds=0.0}}
function Add-SliceTurnMetadata {param($Result,[string[]]$Inherited=@(),[string]$PendingEvent='none',[bool]$Compound=$false)$Result|Add-Member -NotePropertyName InheritedFromPending -NotePropertyValue @($Inherited) -Force;$Result|Add-Member -NotePropertyName PendingEvent -NotePropertyValue $PendingEvent -Force;$Result|Add-Member -NotePropertyName CompoundDetected -NotePropertyValue $Compound -Force;$Result}
function Invoke-SliceInterpretation {
 [CmdletBinding()]param($Session,[string]$PlayerText,[scriptblock]$Backend,[string]$DebugLogPath,[Nullable[int]]$Seed)
 $watch=[Diagnostics.Stopwatch]::StartNew();$context=Get-SliceInterpretationContext $Session
 $gestureToGuillermo=$PlayerText-match'(?i)^\s*(?:wave|whistle|point|beckon|snap|clap|smile|pet)\b.*\bGuillermo\b|^\s*wave\s+at\s+Guillermo\s+and\s+whistle'
 $windowOpenPhrase=$PlayerText-match'(?i)^\s*go?t?\s+to\s+(?:the\s+)?window\s+and\s+(?:try\s+to\s+)?open\s+it'
 $trueCompound=$PlayerText-match'(?i)\b(and then|then|after that|and\s+(?:have|ask|tell|send)\s+Guillermo)\b'-or($PlayerText-match'(?i)\band\s+(?:look|inspect|examine|search|open|close|leave|move|take|read|cast|use)\b'-and$PlayerText-notmatch'(?i)\band\s+(?:see|determine|check|figure|work out)\b')
 if($trueCompound-and-not$gestureToGuillermo-and-not$windowOpenPhrase){$Session.PendingIntent=$null;$watch.Stop();$r=New-SliceClarification compound 'That contains two actions. Which should happen first?';$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() 'cleared_compound' $true)}
 if($PlayerText-match'(?i)^\s*(?:cancel|never mind|nevermind)\b'){$Session.PendingIntent=$null;$watch.Stop();$r=New-SliceClarification canceled 'All right. What do you want to do instead?';$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() 'cleared_canceled')}
 $match=Find-SliceTarget $PlayerText $context;$target=$match.Target;$recentUsed=$false
 if($match.Candidates.Count-gt1){$watch.Stop();$r=New-SliceClarification $(if($match.Alias-match'(?i)marks?'){'ambiguous_marks'}else{'ambiguous_target'}) $null $match.Candidates;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}
 if(-not$target-and$PlayerText-match'(?i)\b(it|that|those|them)\b'){$recent=@($context.RecentReferents|Select-Object -Unique);if($recent.Count-eq1){$target=$recent[0];$recentUsed=$true}elseif($recent.Count-gt1){$watch.Stop();$r=New-SliceClarification recent 'Which recent object do you mean?' $recent;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}}
 if($PlayerText-match'(?i)^\s*look down at (?:the )?floor\b'){$target='rug';$match=[pscustomobject]@{Alias='floor'}}
 if($null-ne$Session.PendingIntent-and$target-and$PlayerText-match'(?i)^\s*(?:the |that )?[\p{L}\p{N}_ -]+[.!?]?\s*$'-and$PlayerText-notmatch'(?i)\b(?:look|inspect|examine|search|investigate|read|open|unlock|take|move|go|walk|step|cast|use|ask|tell|have|send|wait)\b'){$pending=$Session.PendingIntent;$Session.PendingIntent=$null;$watch.Stop();$r=New-SliceIntentResult $PlayerText $pending.actor $pending.action $target $pending.method $pending.spell $pending.area $pending.purpose $null @() $match.Alias $false;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @('target') 'consumed')}
 if($PlayerText-match'(?i)^\s*(?:how|what\s+(?:colou?r|size|width|height|depth))\b'){$Session.PendingIntent=$null;$property=if($PlayerText-match'(?i)\b(?:high|height)\b'){'height'}elseif($PlayerText-match'(?i)\b(?:wide|width)\b'){'width'}elseif($PlayerText-match'(?i)\b(?:big|size|large)\b'){'size'}elseif($PlayerText-match'(?i)\bfar\b'){'distance'}elseif($PlayerText-match'(?i)\bheavy\b'){'weight'}elseif($PlayerText-match'(?i)\b(?:deep|depth)\b'){'depth'}elseif($PlayerText-match'(?i)\bcolou?r\b'){'color'}else{'unknown'};$watch.Stop();$r=New-SliceIntentResult $PlayerText armand query_property $target $null $null $null $null $null @() $match.Alias $false;$r.Intent|Add-Member -NotePropertyName property -NotePropertyValue $property;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() 'cleared_query')}
 if($PlayerText-match'(?i)^\s*(?:is|are|do|does|can|have\s+I|has\s+the)\b'){$Session.PendingIntent=$null;$queryTarget=$target;if(-not$queryTarget){$queryTarget=if($PlayerText-match'(?i)\b(?:fire|hearth|fireplace)\b'){'fireplace'}elseif($PlayerText-match'(?i)\bwindow\b'){'window'}elseif($PlayerText-match'(?i)\bdoor\b'){'study_door'}elseif($PlayerText-match'(?i)\bGuillermo\b'){'guillermo'}elseif($PlayerText-match'(?i)\bsafe\b'){'wall_safe'}elseif($PlayerText-match'(?i)\bnote\b'){'burned_note'}elseif($PlayerText-match'(?i)\b(?:blood|stain|discoloration)\b'){'bloodstain'}else{$null}};$watch.Stop();$r=New-SliceIntentResult $PlayerText armand query_state $queryTarget $null $null $null $null $null @() $match.Alias $false;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() 'cleared_query')}
 $actor=if($PlayerText-match'(?i)\b(send|have|ask|tell)\s+Guillermo\b|^\s*Guillermo\b'){'guillermo'}else{'armand'}
 if($actor-eq'guillermo'-and$target-eq'guillermo'-and$PlayerText-notmatch'(?i)^\s*ask Guillermo\b'){$withoutGuillermo=$context.PSObject.Copy();$withoutGuillermo.Entities=@($context.Entities|Where-Object{$_.Id-ne'guillermo'});$alternate=Find-SliceTarget $PlayerText $withoutGuillermo;if($alternate.Target){$match=$alternate;$target=$match.Target}}
 $area=if($PlayerText-match'(?i)\b(under|underneath|beneath|below)\b'){'underneath'}elseif($PlayerText-match'(?i)\b(?:top|on top)\b'){'on_top'}elseif($PlayerText-match'(?i)\bbehind\b'){'behind'}elseif($PlayerText-match'(?i)\binside\b'){'inside'}elseif($PlayerText-match'(?i)\baround\b'){'around'}else{$null}
 $modifiers=@(@('quietly','carefully','quickly','without touching')|Where-Object{$PlayerText-match('(?i)\b'+[regex]::Escape($_)+'\b')})
 $explicitMethod=if($PlayerText-match'(?i)\b(?:with|using|use)\s+(?:the |a |an |my )?([\p{L}\p{N}_ -]+?)(?:\s+(?:to|for|and)\b|[.!?]|$)'){$Matches[1].Trim()}else{$null}
 if($PlayerText-match'(?i)\b(?:use|using|with)\s+(?:the |my )?(crowbar|pry bar)\b.*\b(?:open|unlock|force|pry)\b.*\bsafe\b'-and@($context.Entities.Id)-contains'wall_safe'){$target='wall_safe';$explicitMethod='crowbar';$match=[pscustomobject]@{Alias='safe'}}
 $purpose=$null
 if($PlayerText-match'(?i)\b(?:to|and)\s+(?:see|check|determine|work out|figure out|examine|inspect|look)\s+(.+)$'){$purpose=$Matches[1].Trim(' .')}
 elseif($PlayerText-match'(?i)\b(?:for|whether)\s+(.+)$'){$purpose=$Matches[1].Trim(' .')}
 if($PlayerText-match'(?i)(book.+fit|what (?:sort|kind) of book|what was removed|shelf wear)'-and@($context.Entities.Id)-contains'bookshelf_gap'){$target='bookshelf_gap';$purpose='infer the size or identity of the missing book'}
 elseif($target-eq'receipt'-and$PlayerText-match'(?i)addresses?'){$purpose='determine whether the receipts contain addresses'}
 elseif($target-eq'receipt'-and$PlayerText-match'(?i)(where Callum|travel|been)'){$purpose='determine whether the receipts indicate Callum''s recent whereabouts or travel'}
 elseif($target-eq'rope_fibers'-and$PlayerText-match'(?i)(which way|direction|dragged)'){$purpose='determine the direction in which the rope was dragged'}
 elseif($target-eq'scorch_marks'-and$PlayerText-match'(?i)(ordinary fire|cause|came from)'){$purpose='determine whether the marks came from an ordinary fire'}
 $spell=$null;foreach($candidate in $context.Spells){if($PlayerText-match('(?i)(?<![\p{L}\p{N}])'+[regex]::Escape($candidate.Name)+'(?![\p{L}\p{N}])')){$spell=$candidate.Id;break}}
 if(-not$spell-and$PlayerText-match'(?i)\b(blink|teleport)\b'-and@($context.Spells.Id)-contains'misty_step'){$spell='misty_step'}
 if($gestureToGuillermo){$actor='armand';$action='gesture';$target='guillermo';$method=$(if($PlayerText-match'(?i)whistle'){'wave and whistle'}else{([regex]::Match($PlayerText,'(?i)wave|point|beckon|snap|clap|smile|pet').Value.ToLowerInvariant())})}
 elseif($windowOpenPhrase){$actor='armand';$action='open';$target='window';$method='latch'}
 elseif($spell){$action='cast';$method=$null}
 elseif($PlayerText-match'(?i)\b(send|have)\s+Guillermo\b'){$action='examine';$method=$null}
 elseif($PlayerText-match'(?i)^\s*ask Guillermo\b'){$actor='armand';$action='speak';$target='guillermo';$method='ask'}
 elseif($PlayerText-match'(?i)\b(read|open (?:an? )?(?:letter|correspondence))\b'){$action='read';$method='read'}
 elseif($PlayerText-match'(?i)\b(?:open|unlock|close)\b'){$action=if($PlayerText-match'(?i)\bunlock\b'){'unlock'}elseif($PlayerText-match'(?i)\bclose\b'){'manipulate'}else{'open'};$method=$(if($PlayerText-match'(?i)\bclose\b'){'close'}else{$explicitMethod})}
 elseif($PlayerText-match'(?i)^\s*(?:take(?!\s+a\s+closer\s+look)|pick up|grab)\b'){$action='take';$method=$null}
 elseif($PlayerText-match'(?i)^\s*(move|lift|shift|push|pull|turn|roll|drag)\b'-and$target-and$PlayerText-notmatch'(?i)^\s*move\s+(?:toward|towards|to|into|through)\b'){$action='manipulate';$method=$Matches[1].ToLowerInvariant()}
 elseif($PlayerText-match'(?i)\b(knock|poke|rifle|rummage)\b'){$action=if($PlayerText-match'(?i)rifle|rummage'){'search'}else{'manipulate'};$method=([regex]::Match($PlayerText,'(?i)\b(knock|poke|rifle|rummage)\b').Value.ToLowerInvariant())}
 elseif($PlayerText-match'(?i)^\s*(move|go|walk|step|enter|leave)\b'){$action='move';$method=$null}
 elseif($PlayerText-match'(?i)\b(search|investigate|study|work out|figure out)\b'){$action='investigate';$method=$null}
 elseif($PlayerText-match'(?i)\b(smell|sniff)\b'){$action='examine';$method='smell'}
 elseif($PlayerText-match'(?i)\b(touch|feel)\b'){$action='examine';$method='touch'}
 elseif($PlayerText-match'(?i)\b(stare|gaze)\b'){$action='examine';$method='stare'}
 elseif($PlayerText-match'(?i)\b(look|inspect|examine|check|peer|see)\b'){$action='examine';$method=$(if($area-eq'underneath'){'look_under'}else{$null})}
 else{$action=$null;$method=$null}
 if(-not$method-and$explicitMethod-and-not$spell){$method=$explicitMethod}
 if($action-eq'manipulate'-and$area-eq'underneath'){$purpose='examine underneath'}
 if(-not$target-and$PlayerText-match'(?i)\blight\s+(?:a|the)?\s*fire\b.*\b(?:spell|magic)'){$Session.PendingIntent=[pscustomobject]@{actor='armand';action='cast';method=$null;spell='fire_bolt';area=$null;purpose='ignite a fire';missing=@('target');created_turn=$Session.State.Time.Turn};$watch.Stop();$r=New-SliceClarification missing_target 'Where do you want to direct the fire spell?';$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() 'created')}
 if($action-and$target){if($null-ne$Session.PendingIntent){$Session.PendingIntent=$null;$pendingEvent='cleared_unrelated'}else{$pendingEvent='none'};$watch.Stop();$r=New-SliceIntentResult $PlayerText $actor $action $target $method $spell $area $purpose $null $modifiers $match.Alias $recentUsed;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return (Add-SliceTurnMetadata $r @() $pendingEvent)}
 $result=Invoke-IntentInterpretation $PlayerText $context $Backend $DebugLogPath $Seed;if($result.Intent){foreach($field in @('secondary_target','purpose','modifiers')){if(-not$result.Intent.PSObject.Properties[$field]){$result.Intent|Add-Member -NotePropertyName $field -NotePropertyValue $(if($field-eq'modifiers'){@()}else{$null})}}};$result|Add-Member -NotePropertyName OutcomeCategory -NotePropertyValue $(if($result.Status-eq'NEEDS_CLARIFICATION'){'AMBIGUOUS'}elseif($result.Status-eq'UNRECOGNIZED'){'UNRECOGNIZED'}else{'MEANINGFUL'}) -Force;$result|Add-Member -NotePropertyName AliasesMatched -NotePropertyValue @($(if($match.Alias){$match.Alias})) -Force;$result|Add-Member -NotePropertyName RecentReferentUsed -NotePropertyValue $recentUsed -Force;$result|Add-Member -NotePropertyName RoutingFamily -NotePropertyValue $(if($result.Intent){$result.Intent.action}else{$null}) -Force
 if($result.Intent){foreach($field in @('method','area','communicative_intent','spell','secondary_target','purpose')){if(-not$result.Intent.PSObject.Properties[$field]){$result.Intent|Add-Member -NotePropertyName $field -NotePropertyValue $null}};if(-not$result.Intent.PSObject.Properties['modifiers']){$result.Intent|Add-Member -NotePropertyName modifiers -NotePropertyValue @()}};if($null-ne$Session.PendingIntent){$Session.PendingIntent=$null;$pendingEvent='cleared_unrelated'}else{$pendingEvent='none'};Add-SliceTurnMetadata $result @() $pendingEvent
}
function Get-ClueDelta {param($Before,$After)$old=@{};foreach($c in @($Before.Clues.PSObject.Properties.Value)){$old[$c.clue_id]=@($c.known_facts).Count};$changes=@();foreach($c in @($After.Clues.PSObject.Properties.Value)){if(-not$old.ContainsKey($c.clue_id)-or@($c.known_facts).Count-gt$old[$c.clue_id]){$changes+=$c}};@($changes)}
function Invoke-SliceClue {param($Session,[string]$ClueId,[string]$Skill,[int]$Score)$result=Resolve-ClueInterpretation $Session.State $ClueId $Skill $Score;if($result.NewFacts.Count){Visit-NotebookLocation $Session.State callum_study "Callum's Study" @() @($ClueId)|Out-Null};$result}
function Get-SliceMundaneResult {param($Session,[string]$Target,[string]$Action,[string]$Method)$entry=$Session.Content.Polish.mundane_results.PSObject.Properties[$Target];if($null-eq$entry){return $null};$values=$entry.Value;$key=if($Method-in@('look_under','smell','touch','stare','knock')){$Method}elseif($Action-eq'read'){'read'}elseif($Action-eq'manipulate'){'manipulate'}elseif($Target-eq'window_latch'){'inspect'}elseif($Target-eq'guillermo' -and $Action-eq'speak'){'ask'}else{'repeat'};$property=$values.PSObject.Properties[$key];if($property){[string]$property.Value}else{$null}}
function Invoke-SliceActiveClueCheck {
 param($Session,$Intent,[string]$ClueId,[string]$Skill,[Nullable[int]]$FixedRoll)
 $clue=$Session.State.Clues[$ClueId];$next=@($clue.Tiers|Where-Object{$_.Skill-eq$Skill-and-not$clue.KnownFacts.Contains([string]$_.Fact)}|Sort-Object DC|Select-Object -First 1);if(-not$next.Count){return [pscustomobject]@{Repeated=$true;Check=$null;NewFacts=@()}}
 $method=if($Intent.PSObject.Properties['Method']){[string]$Intent.Method}else{''};$purpose=if($Intent.PSObject.Properties['Purpose']){[string]$Intent.Purpose}else{''};$modifiers=if($Intent.PSObject.Properties['Modifiers']){@($Intent.Modifiers)-join','}else{''};$world="safe:$($Session.SafeDiscovered):$($Session.SafeOpen):facts:$($clue.KnownFacts.Count)";$key="$($Intent.Actor)|$($Intent.Action)|$($Intent.Target)|$Skill|$method|$purpose|$modifiers|$($next[0].DC)|$world"
 if($Session.CheckHistory.Contains($key)){return [pscustomobject]@{Repeated=$true;Check=$null;NewFacts=@()}}
 $modifier=[int]$Session.State.Player.Skills[$Skill];$checkArgs=@{Mode='active';DC=[int]$next[0].DC;SkillModifier=$modifier};if($null-ne$FixedRoll){$checkArgs.FixedRoll=$FixedRoll};$check=Resolve-Check @checkArgs;$result=Invoke-SliceClue $Session $ClueId $Skill ([int]$check.Total);$Session.CheckHistory[$key]=[pscustomobject]@{Outcome=$check.Degree;FactCount=$clue.KnownFacts.Count}
 [pscustomobject]@{Repeated=$false;Check=[pscustomobject]@{Mode='active';Skill=$Skill;Outcome=$check.Degree;NaturalRoll=$check.NaturalRoll;Modifier=$check.SkillModifier;DC=$check.DC;Margin=$check.Margin};NewFacts=@($result.NewFacts)}
}
function Format-SliceRollFeedback {param($Check,[ValidateSet('minimal','standard','detailed')][string]$Mode='standard')if($null-eq$Check-or$Check.Mode-ne'active'-or$Mode-eq'minimal'){return $null};if($Mode-eq'detailed'){return "🎲 $($Check.Skill) • $($Check.Outcome) • d20 $($Check.NaturalRoll) + $($Check.Modifier) vs DC $($Check.DC)"};"🎲 $($Check.Skill) • $($Check.Outcome)"}
function Resolve-SliceIntent {
 [CmdletBinding()]param($Session,$Intent,[Nullable[int]]$FixedRoll)
 $s=$Session.State;$preLocation=[string]$s.Player.Location;$preItems=[ordered]@{};foreach($id in @('burned_note','crowbar')){if($s.Items.Contains($id)){$preItems[$id]=[pscustomobject]@{location=$s.Items[$id].Location;owner=$s.Items[$id].Owner}}};$target=[string]$Intent.Target;$action=[string]$Intent.Action;$actor=[string]$Intent.Actor;$method=[string]$Intent.Method;$events=[Collections.Generic.List[string]]::new();$degree='resolved';$skill='Investigation';$dc=10;$roll=$FixedRoll;$accepted=$true;$reason=$null;$notebookTarget=$target;$classification='MEANINGFUL';$tone='neutral';$mundane=$null;$activeCheck=$null;$key="$target|$action|$method";$prior=if($Session.InteractionCounts.Contains($key)){[int]$Session.InteractionCounts[$key]}else{0};$Session.InteractionCounts[$key]=$prior+1
 if($action-eq'cast'-and$Intent.Spell-eq'misty_step'){if($target-eq'wall_safe'){$accepted=$false;$reason='Misty Step needs a visible destination you can occupy; the inside of the opaque safe is not visible.'}elseif($target-and@((Get-SliceInterpretationContext $Session).Entities.Id)-contains$target){Invoke-SpellSlotUse $s;$destination=if($s.Items.Contains($target)){$s.Items[$target].DisplayName}elseif($s.Locations.Contains($target)){$s.Locations[$target].DisplayName}else{$target};$events.Add("Armand vanishes through a curl of mist and reappears beside the $destination.") }else{$accepted=$false;$reason='Misty Step needs a visible destination you can actually occupy.'}}
 elseif($action-eq'move'){if($target-in@('landing','study_door')-and$s.Player.Location-eq'callum_study'){$s.Player.Location='landing';$s.Guillermo.Location='landing';$Session.VisitCounts.landing++;Visit-NotebookLocation $s landing 'Upstairs Landing' @('a narrow landing outside the study')|Out-Null;$events.Add('Armand steps onto the upstairs landing.')}elseif($target-in@('callum_study','study_entrance')-and$s.Player.Location-eq'landing'){$s.Player.Location='callum_study';$s.Guillermo.Location='callum_study';$Session.VisitCounts.callum_study++;$events.Add('Armand returns to the changed study.')}else{$accepted=$false;$reason='There is nowhere to go in that direction.'}}
 elseif($action-eq'cast'-and$Intent.Spell-eq'detect_magic'){$events.Add('A faint magical presence clings to the scorch marks, but its meaning remains unclear.');Invoke-SliceClue $Session occult_residue Occult 10|Out-Null;$notebookTarget='occult_residue'}
 elseif($action-eq'cast'){$category=if($target-eq'paneled_wall'){'force_against_wall'}elseif($target-in@('writing_desk','chair','bookshelves')){'force_against_furniture'}else{'default'};$mundane=if($Intent.Spell-eq'fire_bolt'-and$target-eq'fireplace'){'A spark flares against the cold hearth, but without laid fuel no fire catches.'}else{[string]$Session.Content.Polish.unsupported_action_responses.$category};$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 elseif($action-eq'query_property'){$classification='MUNDANE';$tone='dry_humor_allowed';$property=if($Intent.PSObject.Properties['Property']){[string]$Intent.Property}else{'unknown'};$mundane=if($target-eq'window'-and$property-eq'height'){'The window sill sits roughly at your waist. Climbing through would take some effort, but hardly an expedition.'}elseif($target-eq'writing_desk'-and$property-in@('width','size')){'The writing desk is broad enough for its scattered papers and a pair of working elbows. Nothing here offers an honest exact measurement.'}elseif($target-eq'large_painting'-and$property-eq'distance'){'The painting hangs across the study, only several deliberate strides away. The room offers no exact scale.'}elseif($target-eq'rug'-and$property-eq'color'){'In the gaslight, the rug reads as a tired, dark red beneath its dust.'}elseif($target-eq'chair'-and$property-eq'weight'){'The upholstered chair looks solid but movable by one person; its exact weight is anyone''s guess.'}elseif($target-eq'fireplace'-and$property-eq'depth'){'The fireplace is deep enough for a modest coal fire. From here, an exact measurement would be theatre rather than investigation.'}elseif($target-eq'study_room'-and$property-eq'size'){'The study is compact: a few strides across, crowded by desk, shelves, hearth, and chair. Nothing supplies an exact measurement.'}else{'You can judge it only roughly from here; nothing in the room gives an exact measurement.'};$events.Add($mundane)}
 elseif($action-eq'query_state'){$classification='MUNDANE';$tone='neutral';$mundane=switch($target){'fireplace'{'The hearth is cold and unlit.'}'window'{'The window is closed.'}'study_door'{'The study door is unlocked.'}'guillermo'{if($s.Guillermo.Location-eq$s.Player.Location-and$s.Guillermo.Available-and$s.Guillermo.Alive){'Guillermo is here with you.'}else{'Guillermo is not here.'}}'wall_safe'{if(-not$Session.SafeDiscovered){'No safe is currently visible.'}elseif($Session.SafeOpen){'The concealed safe stands open.'}else{'The concealed safe is closed and locked.'}}'burned_note'{if($s.Items.burned_note.Owner-eq'Armand'){'You have the partially burned note.'}elseif($Session.SafeOpen){'The partially burned note remains inside the open safe.'}else{'No note is currently visible.'}}'bloodstain'{if($Session.ReferentStates.Contains('bloodstain')){'A dark discoloration remains visible beside the rug.'}else{'You have not identified any blood in the room.'}}default{'Nothing currently visible answers that question.'}};$events.Add($mundane)}
 elseif($action-eq'gesture'-and$target-eq'guillermo'){$mundane=[string]$Session.Content.Polish.mundane_results.guillermo.gesture;$events.Add($mundane);$classification='MUNDANE';$tone='guillermo_comic'}
 elseif($target-eq'window'-and$action-in@('open','manipulate')){if($method-eq'close'){if($Session.WindowOpen){$Session.WindowOpen=$false;$events.Add('The latch gives a reluctant click as the window closes. Rain becomes a muted tapping beyond the glass.')}else{$events.Add('The window is already closed; the cold brass latch confirms it with bureaucratic finality.');$classification='MUNDANE';$tone='dry_humor_allowed'}}else{if($Session.WindowOpen){$events.Add('The window is already open to the rain-cooled night.');$classification='MUNDANE'}else{$Session.WindowOpen=$true;$events.Add('The latch gives with a reluctant click. Rain-cooled air slips into the study, stirring the edges of the papers without moving them from the desk. Beyond the glass, the street is black and shining.')}}}
 elseif($actor-eq'Guillermo'-and$target-eq'large_painting'){$engine=Resolve-StructuredIntent -State $s -Intent $Intent -Skill Investigation -DC 10 -FixedRoll $(if($null-ne$roll){$roll}else{11}) -Events @() -Visible @('large painting');$degree=$engine.Resolution.Degree;if($degree-in@('Success','Exceptional Success')){$Session.SafeDiscovered=$true;$events.Add('Guillermo climbs the frame, tugs it aside, and points urgently at the safe.')}else{$events.Add('The frame knocks against the wall; Guillermo retreats to the desk.');Add-GuillermoIncident $s "painting_$($s.Time.Turn)" failure 'Guillermo knocked the painting and retreated.' 2|Out-Null}}
 elseif($actor-eq'Guillermo'-and$target-eq'bookshelves'){$Session.ReferentStates['bookshelf_gap']='visible';$events.Add('Guillermo examines the shelves and taps an empty gap where a volume was recently removed; the gap does not identify the missing book.');$classification='MEANINGFUL';$notebookTarget='bookshelves'}
 elseif($target-eq'large_painting'-and$action-in@('examine','search','investigate','manipulate')){if($Session.SafeDiscovered){$mundane=Get-SliceMundaneResult $Session $target $action $method;$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}else{$Session.SafeDiscovered=$true;$events.Add('The painting shifts, exposing a fixed iron safe behind it.');$notebookTarget='wall_safe'}}
 elseif($target-eq'painting_frame'-and$action-in@('examine','search','investigate','manipulate')){$Session.SafeDiscovered=$true;$events.Add('The painting frame shifts with the canvas, exposing a fixed iron safe behind it.');$notebookTarget='wall_safe'}
 elseif($target-eq'paneled_wall'-and$action-in@('examine','search','investigate')){$Session.SafeDiscovered=$true;$events.Add('A shallow mismatch in the paneling leads behind the painting, where a fixed iron safe is concealed.');$notebookTarget='wall_safe'}
 elseif($target-eq'study_room'){$Session.ReferentStates['bloodstain']='visible';$Session.ReferentStates['scorch_marks']='visible';$Session.ReferentStates['rope_fibers']='visible';$events.Add('Rain traces the window. Coarse fibers catch on a scratched writing desk scattered with papers; unusual dark patterns mark the cold hearth, a dark discoloration lies beside the rumpled rug, and a large painting hangs slightly askew.')}
 elseif(-not($target-eq'receipt'-and$Intent.PSObject.Properties['Purpose']-and$Intent.Purpose)-and($action-eq'read'-or$method-in@('look_under','smell','touch','stare','knock')-or$target-eq'window_latch'-or($target-eq'guillermo'-and$action-eq'speak'))-and($mundane=Get-SliceMundaneResult $Session $target $action $method)){$events.Add($mundane);$classification='MUNDANE';$tone=if($target-eq'guillermo'){'guillermo_comic'}else{'dry_humor_allowed'}}
 elseif($target-in@('rug','bloodstain') -and $action-in@('examine','search','investigate','manipulate')){$Session.ReferentStates['bloodstain']='visible';$passive=Invoke-SliceClue $Session bloodstain Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent bloodstain Investigation $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The pattern yields nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$events.Add('The dark mark remains visible, but yields no further certainty.')};$notebookTarget='bloodstain'}
 elseif($target-in@('fireplace','scorch_marks') -and $action-in@('examine','search','investigate')){$Session.ReferentStates['scorch_marks']='visible';$passive=Invoke-SliceClue $Session scorch_marks Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent scorch_marks Occult $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The pattern yields nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$events.Add('The scorched stone remains unexplained.')};$notebookTarget='scorch_marks'}
 elseif($target-in@('writing_desk','rope_fibers')-and$action-in@('examine','search','investigate')){$passive=Invoke-SliceClue $Session rope_fibers Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent rope_fibers Investigation $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The fibers yield nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$mundane=Get-SliceMundaneResult $Session writing_desk $action $(if($method){$method}else{'repeat'});$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'};$notebookTarget='rope_fibers'}
 elseif($target-eq'receipt'-and$Intent.PSObject.Properties['Purpose']-and$Intent.Purpose){$mundane='The receipts identify ink and a costly lunch, but contain no address, itinerary, or reliable evidence of Callum''s recent whereabouts.';$events.Add($mundane);$classification='MUNDANE';$tone='neutral'}
 elseif($target-eq'bookshelf_gap'){$events.Add('The shelf wear confirms that a volume was removed recently, but does not reliably establish its size, title, or present location.');$classification='MEANINGFUL';$notebookTarget='bookshelves'}
 elseif($target-eq'bookshelves'){$Session.ReferentStates['bookshelf_gap']='visible';$mundane=Get-SliceMundaneResult $Session bookshelves $action stare;if(-not$mundane){$mundane='Most volumes are ordinary reference works; one empty gap shows recent use but does not identify the missing book.'};$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 elseif($target-eq'desk_drawers'){$mundane=[string]$Session.Content.Polish.mundane_results.desk_drawers.repeat;$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 elseif($target-in@('wall_safe','safe_dial','safe_door')-and$action-in@('open','unlock','use','investigate','manipulate')){if(-not$Session.SafeDiscovered){$accepted=$false;$reason='You do not see a safe here.'}elseif($Session.SafeOpen){$events.Add('The safe is already open.');$classification='MUNDANE'}else{$useCrowbar=($method-match'(?i)crowbar|pry|force');$useFinesse=($method-match'(?i)finesse|pick|lock|manipulat');$useCombination=($method-match'(?i)dial|combination|code');if(-not($useCrowbar-or$useFinesse-or$useCombination)){$accepted=$false;$reason='The safe does not open freely. You could try the dial, work the lock, force it, or name another approach.'}elseif($useCombination-and-not$s.Notebook.Clues.Contains('callum_symbol')){$accepted=$false;$reason='You do not yet know a combination to enter.'}else{$effective=if($null-ne$roll){[int]$roll}else{if($useCrowbar){8}elseif($useCombination){16}else{12}};$dc=15;$total=$effective+$s.Player.Skills.Finesse;if($useCombination){$total+=5};if($total-ge$dc){$Session.SafeOpen=$true;$events.Add('The safe opens, revealing a partially burned note inside it.');$degree=if($useCrowbar){'Setback'}else{'Success'};if($useCrowbar){$events.Add('The crowbar bends and the metal door shrieks loudly.')}}elseif($useCrowbar-and$total-ge10){$Session.SafeOpen=$true;$events.Add('The safe door tears open, revealing a partially burned note inside it; the crowbar bends and the crash echoes onto the landing.');$degree='Setback'}else{$events.Add('The lock resists, and the attempt produces a sharp metallic click.');$degree='Failure';Add-GameTime $s 2 1}}}}
 elseif($target-eq'burned_note'-and$action-in@('take','examine','search','read')){if(-not$Session.SafeOpen){$accepted=$false;$reason='The note is not accessible.'}elseif($action-eq'take'){Move-InventoryItem $s burned_note Armand;$Session.LeadRecovered=$true;Invoke-SliceClue $Session external_lead Investigation 10|Out-Null;$events.Add($Session.Content.Slice.lead_fact);$events.Add('You take the partially burned note from the safe. The lead points beyond the house, without identifying who took Callum.');$degree='Success';$notebookTarget='external_lead'}else{Invoke-SliceClue $Session external_lead Investigation 10|Out-Null;$events.Add($Session.Content.Slice.lead_fact);$events.Add($(if($s.Items.burned_note.Owner-eq'Armand'){'You read it while holding it; its location does not change.'}else{'You read it where it remains inside the open safe.'}));$degree='Success';$notebookTarget='external_lead'}}
 elseif($action-eq'wait'){$events.Add('Rain ticks against the window while the disturbed room remains still.');Add-GameTime $s 1 1}
 elseif($target-and$s.Items.Contains($target)){$mundane="You try the $action against the $($s.Items[$target].DisplayName). It answers with an ordinary scrape, rustle, or silence and offers no new evidence.";$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 else{$accepted=$false;$reason='You do not see anything matching that description here.'}
 if(-not$accepted){return [pscustomobject]@{Accepted=$false;Reason=$reason;Degree='ENGINE_REJECTED';Classification='IMPOSSIBLE';Check=$null;Events=@();Handoff=$null;NotebookTarget=$notebookTarget;PreLocation=$preLocation;PostLocation=[string]$s.Player.Location;PreItemLocations=$preItems;PostItemLocations=$preItems}}
 if($Session.PersistentEnvironment.Count){$aftermath=@($Session.PersistentEnvironment|ForEach-Object{$_.description})-join', ';$events.Add("The room still bears the aftermath: $aftermath.")}
 if($action-notin@('wait','move')-and$events.Count){Add-GameTime $s 1 1};$Session.RecentReferents=@($target|Where-Object{$_});$visible=@((Get-SlicePlayerState $Session).visible_objects);$resolution=[pscustomobject]@{Degree=$degree};$safeIntent=[pscustomobject]@{Actor=$actor;Action=$action;Target=$(if($s.Items.Contains($target)){$s.Items[$target].DisplayName}else{$target});Method=$Intent.Method;Purpose=$(if($Intent.PSObject.Properties['Purpose']){$Intent.Purpose}else{$null})};if($Intent.PSObject.Properties['Property']){$safeIntent|Add-Member -NotePropertyName Property -NotePropertyValue $Intent.Property};$entries=Get-NotebookRelevance $s $null $notebookTarget @($target) @() ([int]$Session.Content.Polish.relevance.max_entries);$known=@(ConvertTo-NarratorNotebookEntries $entries|Where-Object{$_});$authorized=Get-SliceInterpretationContext $Session;$affordances=@($visible)+@($authorized.Entities|ForEach-Object{$_.DisplayName})+@($authorized.Entities|ForEach-Object{$_.Aliases})+@($s.Player.Inventory|ForEach-Object{$s.Items[$_].DisplayName})+@($events);$handoff=New-NarratorHandoff -Intent $safeIntent -Resolution $resolution -PostActionState ([pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;window_open=$Session.WindowOpen;lead_recovered=$Session.LeadRecovered}) -Events @($events) -Visible $visible -NotebookEntries $known -NewThisTurn @($events) -KnownContext $known -MundaneResult $mundane -Tone $tone -SupportedAffordances $affordances
 if(-not$Session.HintDelivered-and$s.Notebook.Clues.Contains('bloodstain')-and$s.Notebook.Clues.Contains('rope_fibers')-and-not$Session.SafeDiscovered){$Session.HintDelivered=$true;$hint='Guillermo looks at Armand, looks at the large painting, then looks back at Armand. He repeats the gesture once.';$handoff.Events+=@($hint);$handoff.NewThisTurn+=@($hint)}
 $postItems=[ordered]@{};foreach($id in @('burned_note','crowbar')){if($s.Items.Contains($id)){$postItems[$id]=[pscustomobject]@{location=$s.Items[$id].Location;owner=$s.Items[$id].Owner}}};$handoff.PostActionState|Add-Member -NotePropertyName player_location -NotePropertyValue ([string]$s.Player.Location) -Force;$handoff.PostActionState|Add-Member -NotePropertyName item_locations -NotePropertyValue $postItems -Force
 [pscustomobject]@{Accepted=$true;Reason=$null;Degree=$degree;Classification=$classification;Check=$activeCheck;Events=@($handoff.Events);Handoff=$handoff;NotebookTarget=$notebookTarget;PreLocation=$preLocation;PostLocation=[string]$s.Player.Location;PreItemLocations=$preItems;PostItemLocations=$postItems}
}
function Get-SafeFallbackNarration {param($Resolution)if($Resolution.Events.Count){$text=@($Resolution.Events)-join' ';$text=$text-replace'\bArmand returns\b','You return';$text=$text-replace'\bArmand steps\b','You step';$text=$text-replace'\bArmand vanishes\b','You vanish';$text=$text-replace'\bArmand\b','You';$text=$text-replace'\bYou vanish([^.!?]*?)\band reappears\b','You vanish$1and reappear';return $text};'The attempt changes nothing you can presently observe.'}
function Test-SliceNarrationGrounding {
 param($Session,$Resolution,[string]$Text,$BaseValidation)$errors=[Collections.Generic.List[string]]::new()
 if($Resolution.PSObject.Properties['PreLocation']-and$Resolution.PreLocation-eq$Resolution.PostLocation-and$Text-match'(?i)\byou\s+(?:enter|step into|leave|cross into|step through|emerge into|return to)\b'){$errors.Add('Narration invents a location transition without an authoritative Player.Location change.')}
 if($Resolution.PSObject.Properties['PostItemLocations']-and$Resolution.PostItemLocations.Contains('burned_note')){$note=$Resolution.PostItemLocations['burned_note'];if($note.location-eq'safe'-and$Text-match'(?i)\b(?:note|letter)\b.{0,50}\b(?:on|atop|upon)\s+(?:the\s+)?(?:writing\s+)?(?:desk|table)\b'){$errors.Add('Narration relocates the burned note from the safe to the desk.')}if($note.owner-ne'Armand'-and$Text-match'(?i)\b(?:pocket|take|carry|holding|in your hand)\b.{0,50}\b(?:note|letter)\b|\b(?:note|letter)\b.{0,50}\b(?:pocket|take|carry|holding|in your hand)\b'){$errors.Add('Narration invents possession of the burned note.')}}
 if(([string]$Resolution.Handoff.Attempt.Method+[string]$Resolution.Handoff.Attempt.Purpose+[string]$Resolution.Handoff.Attempt.Description)-notmatch'(?i)crowbar|pry'-and$Text-match'(?i)\b(?:crowbar|pry bar)\b'){$errors.Add('Narration invents use of the crowbar.')}
 if($Resolution.Handoff.Attempt.Action-eq'gesture'-and$Text-match'(?i)\b(?:you|Armand)\s+(?:ask|say|tell|question|inquire)|["“”]'){$errors.Add('Narration converts a nonverbal gesture into invented player dialogue.')}
 if($Resolution.Handoff.Attempt.Action-eq'gesture'-and$Text-match'(?i)\bGuillermo\s+(?:says|asks|answers|replies|speaks)\b'){$errors.Add('Narration gives Early-tier Guillermo unsupported speech.')}
 if($Text-match'(?i)\b(?:harmless experiment|no supported consequence|result category|mundane result|safe target|nothing consequential appears)\b'){$errors.Add('Narration exposes internal engine classification language.')}
 $targetText=[string]$Resolution.Handoff.Attempt.Target;$eventText=@($Resolution.Events)-join' '
 foreach($topic in @(@{pattern='\b(?:blood|bloodstain|dark discoloration|stain beside the rug)\b';targets='blood|discoloration|rug|study'},@{pattern='\b(?:scorch|soot|dark pattern|hearth keeps|ordinary fire|occult energy)\b';targets='scorch|fireplace|hearth|study'},@{pattern='\b(?:rope fibers?|hemp cordage|coarse fibers?|strands)\b';targets='fiber|desk|study'})){if($Text-match("(?i)"+$topic.pattern)-and$targetText-notmatch("(?i)"+$topic.targets)-and$eventText-notmatch("(?i)"+$topic.pattern)){$errors.Add('Narration answers with evidence from a different target.')}}
 foreach($foreign in @(@{name='window|latch';targets='window|latch|study'},@{name='fireplace|hearth';targets='fireplace|hearth|scorch|study'},@{name='desk';targets='desk|fiber|receipt|correspondence|study'},@{name='painting';targets='painting|frame|study'},@{name='note|letter';targets='note|correspondence|study'})){if($Text-match("(?i)\byou\s+(?:test|inspect|investigate|examine|open|read|touch|move)\s+(?:the\s+)?(?:[a-z]+\s+){0,3}(?:"+$foreign.name+")\b")-and$targetText-notmatch("(?i)"+$foreign.targets)-and$eventText-notmatch("(?i)"+$foreign.name)){$errors.Add('Narration invents a follow-on action against a different target.')}}
 if($Text-match'(?i)\byou\s+(?:decide|choose|resolve|intend)\b'){$errors.Add('Narration invents a player decision or follow-on action.')}
 if($targetText-match'(?i)desk'-and$Text-match'(?i)\b(?:drawers? on each side|receipt (?:is |lies )?in (?:one of )?(?:the )?drawers?|flooring prevent)\b'){$errors.Add('Narration contradicts the authored desk and drawer structure.')}
 if($targetText-match'(?i)blood|discoloration'-and$Text-match'(?i)\b(?:near|beside|at|by)\s+(?:the\s+)?fireplace\b'){$errors.Add('Narration moves the blood evidence away from the rug.')}
 if($targetText-match'(?i)fiber'-and$eventText-notmatch'(?i)pull|tension|tying'-and$Text-match'(?i)\b(?:used for tying|tied|binding|bound)\b'){$errors.Add('Narration invents a higher-tier use for the fibers.')}
 if($Text-match'(?i)\bthis is a clue\b'){$errors.Add('Narration exposes meta-game clue classification.')}
 if($targetText-eq'study'-and$Text-match'(?i)\b(?:violence|struggle|cause|used recently|forced)\b'){$errors.Add('Narration interprets an overview beyond its authored observations.')}
 $sentences=@([regex]::Matches($Text,'[.!?](?:["”'']?\s|$)'));if($sentences.Count-gt5){$errors.Add('Narration exceeds the bounded five-sentence maximum.')}
 $sentenceTexts=@($Text-split'(?<=[.!?])\s+'|ForEach-Object{($_.Trim().ToLowerInvariant()-replace'[^a-z0-9 ]','')}|Where-Object{$_});if(@($sentenceTexts|Group-Object|Where-Object{$_.Count-gt1}).Count){$errors.Add('Narration repeats a sentence verbatim.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,60}\b(open|opened|ajar|contents? (?:are |is )?visible)\b'){$errors.Add('Narration contradicts closed safe state.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,80}\b(unlocked|lock (?:has been |was )?(?:picked|opened))\b'){$errors.Add('Narration invents successful safe access.')}
 if($Session.SafeDiscovered-and$Text-match'(?i)\bsafe\b.{0,80}\b(was not there before|wasn.t there before|has appeared|newly appeared)\b'){$errors.Add('Narration invents a safe continuity change.')}
 if(-not$Session.SafeDiscovered-and$Text-match'(?i)\b(concealed |wall )?safe\b'){$errors.Add('Narration reveals the hidden safe.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\b(partially burned|burned note|Blackthorn Station)\b'){$errors.Add('Narration reveals inaccessible safe contents.')}
 if($Text-match'(?i)\bnotebook (?:lies|rests|sits|is)\b'){$errors.Add('Narration invents a physical Notebook object.')}
 if((@($Resolution.Events)-join' ')-match'(?i)\b(discoloration|blood|fibers?|scorch|residue)\b'-and$Text-match'(?i)\b(find|see|shows?) (?:absolutely )?(?:nothing|no sign)\b'){$errors.Add('Narration contradicts positive evidence.')}
 if($Text-match'(?i)\bstudy door\b.{0,30}\blocked\b'){$errors.Add('Narration invents a locked door state.')}
 if((@($Resolution.Events)-join' ')-match'(?i)steps onto the upstairs landing'-and$Text-match'(?i)door remains closed|cannot (?:open|pass|enter).{0,20}door'){$errors.Add('Narration contradicts successful movement through the study door.')}
 if($Text-match'(?i)\byou (?:do not|don.t) (?:know|understand|realize|believe)\b'){$errors.Add('Narration assigns player knowledge or belief.')}
 $support=(@($Resolution.Handoff.SupportedAffordances)+@($Resolution.Events)+@($Resolution.Handoff.MundaneResult)-join' ').ToLowerInvariant();foreach($noun in @('drawer','letter','cabinet','box','key','knife','chair','note','receipt','correspondence','gap','dial','frame')){if($Text-match("(?i)\b"+[regex]::Escape($noun)+"s?\b")-and$support-notmatch("(?i)\b"+[regex]::Escape($noun)+"s?\b")){$errors.Add("Narration introduces unsupported physical affordance: $noun.")}}
 if($Resolution.Handoff.Attempt.Target-eq'study'-and$Text-match'(?i)\b(dried blood|hemp cordage|magical discharge|occult (?:energy|cause)|inconsistent with an ordinary fire)\b'){$errors.Add('Narration prematurely interprets an overview observation.')}
 foreach($detail in @('wife','husband','woman','clerk')){if($Text-match("(?i)\b"+[regex]::Escape($detail)+"\b")-and$support-notmatch("(?i)\b"+[regex]::Escape($detail)+"\b")){$errors.Add("Narration introduces unsupported consequential detail: $detail.")}}
 $newText=@($Resolution.Handoff.NewThisTurn)-join' ';$notebookFacts=@($Session.State.Notebook.Clues.Values|ForEach-Object{$_.known_facts})-join' ';$knownText=(@($Resolution.Handoff.KnownContext)-join' ')+' '+$notebookFacts;$currentTarget=[string]$Resolution.Handoff.Attempt.Target;$knownRules=@(@{marker='blood';targets='bloodstain|dark discoloration|rug'},@{marker='fibers?';targets='rope_fibers|rope fibers|writing desk'},@{marker='three-pointed crown';targets='safe|dial|writing desk'},@{marker='magical residue';targets='scorch|fireplace|hearth'},@{marker='Blackthorn Station';targets='note|burned_note'});foreach($rule in $knownRules){if($knownText-match("(?i)"+$rule.marker)-and$newText-notmatch("(?i)"+$rule.marker)-and$Text-match("(?i)"+$rule.marker)-and$currentTarget-notmatch("(?i)"+$rule.targets)){$errors.Add("Narration unnecessarily restates known context: $($rule.marker).")}}
 [pscustomobject]@{Passed=($BaseValidation.Passed-and$errors.Count-eq0);Lexical=$BaseValidation.Lexical;Structural=$BaseValidation.Structural;GroundingErrors=@($errors);RawOutput=$Text;ValidatedOutput=$(if($BaseValidation.Passed-and$errors.Count-eq0){$Text}else{$null})}
}
function Invoke-SliceNarration {
 param($Session,$Resolution,[scriptblock]$NarratorBackend,[int]$MaxAttempts=2,[string]$Root=(Split-Path -Parent $PSScriptRoot))
 if($Resolution.Handoff.Attempt.Action-in@('query_state','query_property','gesture','move')-or($Resolution.Handoff.Attempt.Action-eq'cast'-and(@($Resolution.Events)-join' ')-match'(?i)vanishes through a curl of mist')){$text=Get-SafeFallbackNarration $Resolution;$valid=[pscustomobject]@{Passed=$true;Lexical=$null;Structural=$null;GroundingErrors=@();RawOutput=$text;ValidatedOutput=$text};return [pscustomobject]@{Text=$text;RawOutputs=@();Validations=@($valid);Validation=$valid;RetryOccurred=$false;FallbackUsed=$false;ElapsedSeconds=0.0;PromptCharacters=0;PromptBytes=0}}
 $case=Convert-HandoffToNarrationCase $Resolution.Handoff $Session.State.Player.Location $Session.State.Time.CurrentCaseTime.ToString('h:mm tt') rain;$packet=ConvertTo-NarrationPacket $case;$allExamples=@(Read-NarrationExemplars (Join-Path $Root 'exemplars/playability_polish_exemplars.json') -ExpectedCount 7);$ids=if($Resolution.Handoff.Attempt.Action-eq'gesture'){@('guillermo-gesture')}elseif($Resolution.Handoff.Attempt.Action-eq'query_property'){@('property-query')}elseif($Resolution.Handoff.Attempt.Target-match'correspondence|letter'){@('correspondence-dry','ordinary-atmospheric')}elseif($Resolution.Check-and$Resolution.Degree-match'Failure|Setback'){@('failed-check','ordinary-atmospheric')}elseif($Resolution.Handoff.Attempt.Target-match'blood|discoloration|fiber|scorch'){@('clue-tier','ordinary-atmospheric')}elseif($Resolution.Classification-eq'MUNDANE'){@('mundane-dry','ordinary-atmospheric')}else{@('ordinary-atmospheric')};$examples=@($allExamples|Where-Object{$_.id-in$ids});$prompt=Build-NarrationPrompt $packet facts $examples;$raws=@();$validations=@();$lastValidation=$null;$elapsed=0.0
 for($i=0;$i-lt$MaxAttempts;$i++){$watch=[Diagnostics.Stopwatch]::StartNew();if($null-ne$NarratorBackend){$g=&$NarratorBackend $prompt $i}else{$work=Join-Path $Root 'eval/.work';New-Item -ItemType Directory -Force $work|Out-Null;$path=Join-Path $work "slice_narrator_$([guid]::NewGuid().ToString('N')).txt";$prompt|Set-Content -NoNewline -Encoding utf8 $path;$cfg=Join-Path $Root 'config.json';$g=Invoke-CommaGeneration $path $cfg -Seed (12000+$Session.State.Time.Turn+$i) -Temperature .15 -MaxTokens 160};$watch.Stop();$elapsed+=$watch.Elapsed.TotalSeconds;$raw=[string]$(if($g.PSObject.Properties['Text']){$g.Text}else{$g.RawOutput});$raws+=$raw;$text='You '+(($raw-replace'(?s)\s*FACTS\s*$','').TrimStart());$base=Test-NarrationOutput $text @($Session.Content.Slice.hidden_truth) 120 $Resolution.Handoff.Attempt.Actor;$lastValidation=Test-SliceNarrationGrounding $Session $Resolution $text $base;$validations+=$lastValidation;if($lastValidation.Passed){return [pscustomobject]@{Text=$text;RawOutputs=$raws;Validations=$validations;Validation=$lastValidation;RetryOccurred=($i-gt0);FallbackUsed=$false;ElapsedSeconds=$elapsed;PromptCharacters=$prompt.Length;PromptBytes=[Text.Encoding]::UTF8.GetByteCount($prompt)}}}
 [pscustomobject]@{Text=(Get-SafeFallbackNarration $Resolution);RawOutputs=$raws;Validations=$validations;Validation=$lastValidation;RetryOccurred=($MaxAttempts-gt1);FallbackUsed=$true;ElapsedSeconds=$elapsed;PromptCharacters=$prompt.Length;PromptBytes=[Text.Encoding]::UTF8.GetByteCount($prompt)}
}

Export-ModuleMember -Function Read-SliceContent,New-CallumStudySession,Get-SlicePlayerState,Get-SliceInterpretationContext,Invoke-SliceInterpretation,Resolve-SliceIntent,Format-SliceRollFeedback,Invoke-SliceNarration,Get-SafeFallbackNarration,Test-SliceNarrationGrounding
