Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'InterpreterContext.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentInterpreter.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentSchema.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CoreEngine.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Resolution.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarratorHandoff.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPacket.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPrompt.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationValidation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CommaHarness.psm1') -Force
# Restore public commands after nested module imports replace dependency instances.
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force

function Read-SliceContent {param([string]$Root=(Split-Path -Parent $PSScriptRoot))$dir=Join-Path $Root 'content/callum_study';[pscustomobject]@{Locations=Get-Content -Raw (Join-Path $dir 'location.json')|ConvertFrom-Json;Objects=Get-Content -Raw (Join-Path $dir 'objects.json')|ConvertFrom-Json;Clues=Get-Content -Raw (Join-Path $dir 'clues.json')|ConvertFrom-Json;Slice=Get-Content -Raw (Join-Path $dir 'slice.json')|ConvertFrom-Json;Polish=Get-Content -Raw (Join-Path $dir 'polish.json')|ConvertFrom-Json;Referents=Get-Content -Raw (Join-Path $dir 'referents.json')|ConvertFrom-Json}}
function New-CallumStudySession {
 param([string]$Root=(Split-Path -Parent $PSScriptRoot))$content=Read-SliceContent $Root;$state=New-GameState
 foreach($loc in $content.Locations.locations){Add-LocationState -State $state -Id $loc.id -VisibleObjects @($loc.visible_objects) -Exits @($loc.exits) -DisplayName $loc.display_name}
 foreach($obj in $content.Objects.objects){$parts=if($obj.PSObject.Properties['parts']){@($obj.parts)}else{@()};Add-ItemState -State $state -Id $obj.id -Location $obj.location -Owner $(if($obj.PSObject.Properties['owner']){$obj.owner}else{$null}) -DisplayName $obj.name -Aliases @($obj.aliases) -InteractableParts $parts}
 foreach($clue in $content.Clues.clues){$tiers=@($clue.tiers|ForEach-Object{[pscustomobject]@{DC=[int]$_.dc;Skill=[string]$_.skill;Fact=[string]$_.fact}});Add-ClueState -State $state -Id $clue.id -Location $clue.location -Tiers $tiers -DisplayName $clue.name -RelatedEntityIds @($clue.related)}
 $state.Player.Location=$content.Slice.start_location;$state.Guillermo.Location=$content.Slice.start_location;Visit-NotebookLocation $state callum_study "Callum's Study" @('a disturbed Victorian study lit by gaslight')|Out-Null;Add-NotebookCharacter $state callum 'Callum' callum_study @('Callum is a missing occult researcher and investigator.') @('Armand came to investigate his disappearance.')|Out-Null
 [pscustomobject]@{Id=[guid]::NewGuid().ToString('N');State=$state;Content=$content;SafeDiscovered=$false;SafeOpen=$false;LeadRecovered=$false;HintDelivered=$false;VisitCounts=[ordered]@{callum_study=1;landing=0};InteractionCounts=[ordered]@{};CheckHistory=[ordered]@{};ReferentStates=[ordered]@{};RecentReferents=@();History=[Collections.Generic.List[string]]::new();CreatedUtc=[datetime]::UtcNow}
}
function Get-SlicePlayerState {
 param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$visible=@($loc.VisibleObjects|Where-Object{$_-ne'wall_safe'-and$_-ne'burned_note'});if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$visible+='wall_safe'};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$visible+='burned_note'}
 [pscustomobject]@{session_id=$Session.Id;location=[pscustomobject]@{id=$loc.Id;name=$loc.DisplayName};time=$state.Time.CurrentCaseTime.ToString('h:mm tt');visible_objects=@($visible|ForEach-Object{$state.Items[$_].DisplayName});guillermo=[pscustomobject]@{available=($state.Guillermo.Available-and$state.Guillermo.Alive);communication_tier=$state.Guillermo.CommunicationTier};slice_state=[pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;ending_reached=$Session.LeadRecovered;ending_title=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_title}else{$null});ending_text=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_text}else{$null})};notebook=Get-PlayerFacingNotebook $state}
}
function Get-SliceInterpretationContext {
 param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$original=@($loc.VisibleObjects)
 try{
  if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('wall_safe')};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('burned_note')}
  $context=New-InterpretationContext $state $Session.RecentReferents;$entities=[Collections.Generic.List[object]]::new();foreach($entity in $context.Entities){$authored=@($Session.Content.Objects.objects|Where-Object{$_.id-eq$entity.Id}|Select-Object -First 1);if($authored.Count-and$authored[0].PSObject.Properties['capabilities']){$entity.Capabilities=@($authored[0].capabilities)};$entities.Add($entity)}
  foreach($ref in $Session.Content.Referents.referents){$available=switch -Regex ([string]$ref.trigger){'^always$'{$true;break}'^clue:(.+)$'{$state.Notebook.Clues.Contains($Matches[1]);break}'^session:safe_discovered$'{$Session.SafeDiscovered;break}'^session:(.+)$'{$Session.ReferentStates.Contains($Matches[1])-or$state.Notebook.Clues.Contains($Matches[1]);break}default{$false}};if($available-and-not@($entities.Id).Contains([string]$ref.id)){$entities.Add((New-EntityReference $ref.id subfeature $ref.display_name @($ref.aliases) @() @($ref.capabilities) $ref.parent $ref.lifecycle))}}
  $context.Entities=@($entities);$context.RecentReferents=@($Session.RecentReferents|Where-Object{@($context.Entities.Id)-contains$_});$context
 }finally{$loc.VisibleObjects=$original}
}
function Find-SliceTarget {
 param([string]$Text,$Context)$hits=@()
 foreach($entity in $Context.Entities){foreach($name in @($entity.DisplayName)+@($entity.Aliases)|Sort-Object Length -Descending -Unique){if($entity.Id-eq'study_room'-and$name-eq'study'-and$Text-match'(?i)\bstudy\s+(?:the|a|an|that|this|it)\b'){continue};if(-not[string]::IsNullOrWhiteSpace($name)-and$Text-match('(?i)(?<![\p{L}\p{N}])'+[regex]::Escape($name)+'(?![\p{L}\p{N}])')){$hits+=[pscustomobject]@{Id=$entity.Id;Alias=$name;Length=$name.Length};break}}}
 if(-not$hits.Count){return [pscustomobject]@{Target=$null;Candidates=@();Alias=$null}}
 $max=($hits|Measure-Object Length -Maximum).Maximum;$best=@($hits|Where-Object Length -eq $max);[pscustomobject]@{Target=$(if(@($best.Id|Select-Object -Unique).Count-eq1){$best[0].Id}else{$null});Candidates=@($best.Id|Select-Object -Unique);Alias=$best[0].Alias}
}
function New-SliceIntentResult {
 param([string]$Text,[string]$Actor,[string]$Action,$Target,$Method,$Spell,$Area,$Purpose,$SecondaryTarget,[string[]]$Modifiers=@(),$Alias,[bool]$RecentUsed=$false)
 [pscustomobject]@{Status='RESOLVED';OutcomeCategory='MEANINGFUL';Intent=[pscustomobject]@{actor=$Actor.ToLowerInvariant();action=$Action;target=$Target;secondary_target=$SecondaryTarget;method=$Method;area=$Area;communicative_intent=$null;spell=$Spell;purpose=$Purpose;modifiers=@($Modifiers);raw_input=$Text};Reason=$null;Clarification=$null;AliasesMatched=@($(if($Alias){$Alias}));RecentReferentUsed=$RecentUsed;RoutingFamily=$Action;RawModelStructuredOutput='slice_semantic_route';ElapsedSeconds=0.0}
}
function New-SliceClarification {param([string]$Reason,[string]$Text,[string[]]$Candidates=@())$labels=@($Candidates|ForEach-Object{$_-replace'_',' '});[pscustomobject]@{Status='NEEDS_CLARIFICATION';OutcomeCategory='AMBIGUOUS';Intent=$null;Reason=$Reason;Clarification=$(if($Reason-eq'ambiguous_marks'){"Which marks do you mean, the scorch marks by the hearth or the dark stain by the rug?"}elseif($labels.Count){"Which do you mean: $($labels-join', ')?"}else{$Text});AliasesMatched=@();RecentReferentUsed=$false;RoutingFamily=$null;RawModelStructuredOutput='slice_semantic_clarification';ElapsedSeconds=0.0}}
function Invoke-SliceInterpretation {
 [CmdletBinding()]param($Session,[string]$PlayerText,[scriptblock]$Backend,[string]$DebugLogPath,[Nullable[int]]$Seed)
 $watch=[Diagnostics.Stopwatch]::StartNew();$context=Get-SliceInterpretationContext $Session
 if($PlayerText-match'(?i)\b(and then|then|after that)\b'){$watch.Stop();$r=New-SliceClarification compound 'I can do those in sequence. Which action should happen first?';$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}
 $match=Find-SliceTarget $PlayerText $context;$target=$match.Target;$recentUsed=$false
 if($match.Candidates.Count-gt1){$watch.Stop();$r=New-SliceClarification $(if($match.Alias-match'(?i)marks?'){'ambiguous_marks'}else{'ambiguous_target'}) $null $match.Candidates;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}
 if(-not$target-and$PlayerText-match'(?i)\b(it|that|those|them)\b'){$recent=@($context.RecentReferents|Select-Object -Unique);if($recent.Count-eq1){$target=$recent[0];$recentUsed=$true}elseif($recent.Count-gt1){$watch.Stop();$r=New-SliceClarification recent 'Which recent object do you mean?' $recent;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}}
 if($PlayerText-match'(?i)^\s*look down at (?:the )?floor\b'){$target='rug';$match=[pscustomobject]@{Alias='floor'}}
 $actor=if($PlayerText-match'(?i)\b(send|have|ask|tell)\s+Guillermo\b|^\s*Guillermo\b'){'guillermo'}else{'armand'}
 if($actor-eq'guillermo'-and$target-eq'guillermo'-and$PlayerText-notmatch'(?i)^\s*ask Guillermo\b'){$withoutGuillermo=$context.PSObject.Copy();$withoutGuillermo.Entities=@($context.Entities|Where-Object{$_.Id-ne'guillermo'});$alternate=Find-SliceTarget $PlayerText $withoutGuillermo;if($alternate.Target){$match=$alternate;$target=$match.Target}}
 $area=if($PlayerText-match'(?i)\b(under|underneath|beneath|below)\b'){'underneath'}elseif($PlayerText-match'(?i)\bbehind\b'){'behind'}elseif($PlayerText-match'(?i)\binside\b'){'inside'}elseif($PlayerText-match'(?i)\baround\b'){'around'}else{$null}
 $modifiers=@(@('quietly','carefully','quickly','without touching')|Where-Object{$PlayerText-match('(?i)\b'+[regex]::Escape($_)+'\b')})
 $explicitMethod=if($PlayerText-match'(?i)\b(?:with|using)\s+(?:the |a |an |my )?([\p{L}\p{N}_ -]+?)(?:\s+(?:to|for|and)\b|[.!?]|$)'){$Matches[1].Trim()}else{$null}
 $purpose=$null
 if($PlayerText-match'(?i)\b(?:to|and)\s+(?:see|check|determine|work out|figure out|examine|inspect|look)\s+(.+)$'){$purpose=$Matches[1].Trim(' .')}
 elseif($PlayerText-match'(?i)\b(?:for|whether)\s+(.+)$'){$purpose=$Matches[1].Trim(' .')}
 if($PlayerText-match'(?i)(book.+fit|what (?:sort|kind) of book|what was removed|shelf wear)'-and@($context.Entities.Id)-contains'bookshelf_gap'){$target='bookshelf_gap';$purpose='infer the size or identity of the missing book'}
 elseif($target-eq'receipt'-and$PlayerText-match'(?i)addresses?'){$purpose='determine whether the receipts contain addresses'}
 elseif($target-eq'receipt'-and$PlayerText-match'(?i)(where Callum|travel|been)'){$purpose='determine whether the receipts indicate Callum''s recent whereabouts or travel'}
 elseif($target-eq'rope_fibers'-and$PlayerText-match'(?i)(which way|direction|dragged)'){$purpose='determine the direction in which the rope was dragged'}
 elseif($target-eq'scorch_marks'-and$PlayerText-match'(?i)(ordinary fire|cause|came from)'){$purpose='determine whether the marks came from an ordinary fire'}
 $spell=$null;foreach($candidate in $context.Spells){if($PlayerText-match('(?i)(?<![\p{L}\p{N}])'+[regex]::Escape($candidate.Name)+'(?![\p{L}\p{N}])')){$spell=$candidate.Id;break}}
 if(-not$spell-and$PlayerText-match'(?i)\b(blink|teleport)\b'-and@($context.Spells.Id)-contains'misty_step'){$spell='misty_step'}
 if($spell){$action='cast';$method=$null}
 elseif($PlayerText-match'(?i)\b(send|have)\s+Guillermo\b'){$action='examine';$method=$null}
 elseif($PlayerText-match'(?i)^\s*ask Guillermo\b'){$actor='armand';$action='speak';$target='guillermo';$method='ask'}
 elseif($PlayerText-match'(?i)\b(read|open (?:an? )?(?:letter|correspondence))\b'){$action='read';$method='read'}
 elseif($PlayerText-match'(?i)^\s*(move|lift|shift|push|pull|turn|roll|drag)\b'-and$target-and$PlayerText-notmatch'(?i)^\s*move\s+(?:toward|towards|to|into|through)\b'){$action='manipulate';$method=$Matches[1].ToLowerInvariant()}
 elseif($PlayerText-match'(?i)\b(knock|poke|rifle|rummage)\b'){$action=if($PlayerText-match'(?i)rifle|rummage'){'search'}else{'manipulate'};$method=([regex]::Match($PlayerText,'(?i)\b(knock|poke|rifle|rummage)\b').Value.ToLowerInvariant())}
 elseif($PlayerText-match'(?i)^\s*(move|go|walk|step|enter|leave)\b'){$action='move';$method=$null}
 elseif($PlayerText-match'(?i)\b(search|investigate|study|work out|figure out)\b'){$action='investigate';$method=$null}
 elseif($PlayerText-match'(?i)\b(smell|sniff)\b'){$action='examine';$method='smell'}
 elseif($PlayerText-match'(?i)\b(touch|feel)\b'){$action='examine';$method='touch'}
 elseif($PlayerText-match'(?i)\b(stare|gaze)\b'){$action='examine';$method='stare'}
 elseif($PlayerText-match'(?i)\b(look|inspect|examine|check|peer|see)\b'){$action='examine';$method=$(if($area-eq'underneath'){'look_under'}else{$null})}
 else{$action=$null;$method=$null}
 if(-not$method-and$explicitMethod-and-not$spell){$method=$explicitMethod}
 if($action-eq'manipulate'-and$area-eq'underneath'){$purpose='examine underneath'}
 if($action-and$target){$watch.Stop();$r=New-SliceIntentResult $PlayerText $actor $action $target $method $spell $area $purpose $null $modifiers $match.Alias $recentUsed;$r.ElapsedSeconds=$watch.Elapsed.TotalSeconds;return $r}
 $result=Invoke-IntentInterpretation $PlayerText $context $Backend $DebugLogPath $Seed;if($result.Intent){foreach($field in @('secondary_target','purpose','modifiers')){if(-not$result.Intent.PSObject.Properties[$field]){$result.Intent|Add-Member -NotePropertyName $field -NotePropertyValue $(if($field-eq'modifiers'){@()}else{$null})}}};$result|Add-Member -NotePropertyName OutcomeCategory -NotePropertyValue $(if($result.Status-eq'NEEDS_CLARIFICATION'){'AMBIGUOUS'}elseif($result.Status-eq'UNRECOGNIZED'){'UNRECOGNIZED'}else{'MEANINGFUL'}) -Force;$result|Add-Member -NotePropertyName AliasesMatched -NotePropertyValue @($(if($match.Alias){$match.Alias})) -Force;$result|Add-Member -NotePropertyName RecentReferentUsed -NotePropertyValue $recentUsed -Force;$result|Add-Member -NotePropertyName RoutingFamily -NotePropertyValue $(if($result.Intent){$result.Intent.action}else{$null}) -Force;$result
}
function Get-ClueDelta {param($Before,$After)$old=@{};foreach($c in @($Before.Clues.PSObject.Properties.Value)){$old[$c.clue_id]=@($c.known_facts).Count};$changes=@();foreach($c in @($After.Clues.PSObject.Properties.Value)){if(-not$old.ContainsKey($c.clue_id)-or@($c.known_facts).Count-gt$old[$c.clue_id]){$changes+=$c}};@($changes)}
function Invoke-SliceClue {param($Session,[string]$ClueId,[string]$Skill,[int]$Score)$result=Resolve-ClueInterpretation $Session.State $ClueId $Skill $Score;if($result.NewFacts.Count){Visit-NotebookLocation $Session.State callum_study "Callum's Study" @() @($ClueId)|Out-Null};$result}
function Get-SliceMundaneResult {param($Session,[string]$Target,[string]$Action,[string]$Method)$entry=$Session.Content.Polish.mundane_results.PSObject.Properties[$Target];if($null-eq$entry){return $null};$values=$entry.Value;$key=if($Method-in@('look_under','smell','touch','stare','knock')){$Method}elseif($Action-eq'read'){'read'}elseif($Action-eq'manipulate'){'manipulate'}elseif($Target-eq'window_latch'){'inspect'}elseif($Target-eq'guillermo' -and $Action-eq'speak'){'ask'}else{'repeat'};$property=$values.PSObject.Properties[$key];if($property){[string]$property.Value}else{$null}}
function Invoke-SliceActiveClueCheck {
 param($Session,$Intent,[string]$ClueId,[string]$Skill,[Nullable[int]]$FixedRoll)
 $clue=$Session.State.Clues[$ClueId];$next=@($clue.Tiers|Where-Object{$_.Skill-eq$Skill-and-not$clue.KnownFacts.Contains([string]$_.Fact)}|Sort-Object DC|Select-Object -First 1);if(-not$next.Count){return [pscustomobject]@{Repeated=$true;Check=$null;NewFacts=@()}}
 $method=if($Intent.PSObject.Properties['Method']){[string]$Intent.Method}else{''};$purpose=if($Intent.PSObject.Properties['Purpose']){[string]$Intent.Purpose}else{''};$modifiers=if($Intent.PSObject.Properties['Modifiers']){@($Intent.Modifiers)-join','}else{''};$world="safe:$($Session.SafeDiscovered):$($Session.SafeOpen):facts:$($clue.KnownFacts.Count)";$key="$($Intent.Actor)|$($Intent.Action)|$($Intent.Target)|$Skill|$method|$purpose|$modifiers|$($next[0].DC)|$world"
 if($Session.CheckHistory.Contains($key)){return [pscustomobject]@{Repeated=$true;Check=$null;NewFacts=@()}}
 $modifier=[int]$Session.State.Player.Skills[$Skill];$checkArgs=@{Mode='active';DC=[int]$next[0].DC;SkillModifier=$modifier};if($null-ne$FixedRoll){$checkArgs.FixedRoll=$FixedRoll};$check=Resolve-Check @checkArgs;$result=Invoke-SliceClue $Session $ClueId $Skill ([int]$check.Total);$Session.CheckHistory[$key]=[pscustomobject]@{Outcome=$check.Degree;FactCount=$clue.KnownFacts.Count}
 [pscustomobject]@{Repeated=$false;Check=[pscustomobject]@{Mode='active';Skill=$Skill;Outcome=$check.Degree;NaturalRoll=$check.NaturalRoll;Modifier=$check.SkillModifier;DC=$check.DC;Margin=$check.Margin};NewFacts=@($result.NewFacts)}
}
function Format-SliceRollFeedback {param($Check,[ValidateSet('minimal','standard','detailed')][string]$Mode='standard')if($null-eq$Check-or$Check.Mode-ne'active'-or$Mode-eq'minimal'){return $null};if($Mode-eq'detailed'){return "🎲 $($Check.Skill) • $($Check.Outcome) • d20 $($Check.NaturalRoll) + $($Check.Modifier) vs DC $($Check.DC)"};"🎲 $($Check.Skill) • $($Check.Outcome)"}
function Resolve-SliceIntent {
 [CmdletBinding()]param($Session,$Intent,[Nullable[int]]$FixedRoll)
 $s=$Session.State;$target=[string]$Intent.Target;$action=[string]$Intent.Action;$actor=[string]$Intent.Actor;$method=[string]$Intent.Method;$events=[Collections.Generic.List[string]]::new();$degree='resolved';$skill='Investigation';$dc=10;$roll=$FixedRoll;$accepted=$true;$reason=$null;$notebookTarget=$target;$classification='MEANINGFUL';$tone='neutral';$mundane=$null;$activeCheck=$null;$key="$target|$action|$method";$prior=if($Session.InteractionCounts.Contains($key)){[int]$Session.InteractionCounts[$key]}else{0};$Session.InteractionCounts[$key]=$prior+1
 if($action-eq'cast'-and$Intent.Spell-eq'misty_step'){if($target-eq'wall_safe'){$accepted=$false;$reason='Misty Step needs a visible destination you can occupy; the inside of the opaque safe is not visible.'}elseif($target-and@((Get-SliceInterpretationContext $Session).Entities.Id)-contains$target){Invoke-SpellSlotUse $s;$destination=if($s.Items.Contains($target)){$s.Items[$target].DisplayName}elseif($s.Locations.Contains($target)){$s.Locations[$target].DisplayName}else{$target};$events.Add("Armand vanishes through a curl of mist and reappears beside $destination.") }else{$accepted=$false;$reason='Misty Step needs a visible destination you can actually occupy.'}}
 elseif($action-eq'move'){if($target-in@('landing','study_door')-and$s.Player.Location-eq'callum_study'){$s.Player.Location='landing';$s.Guillermo.Location='landing';$Session.VisitCounts.landing++;Visit-NotebookLocation $s landing 'Upstairs Landing' @('a narrow landing outside the study')|Out-Null;$events.Add('Armand steps onto the upstairs landing.')}elseif($target-in@('callum_study','study_entrance')-and$s.Player.Location-eq'landing'){$s.Player.Location='callum_study';$s.Guillermo.Location='callum_study';$Session.VisitCounts.callum_study++;$events.Add('Armand returns to the changed study.')}else{$accepted=$false;$reason='There is nowhere to go in that direction.'}}
 elseif($action-eq'cast'-and$Intent.Spell-eq'detect_magic'){$events.Add('A faint magical presence clings to the scorch marks, but its meaning remains unclear.');Invoke-SliceClue $Session occult_residue Occult 10|Out-Null;$notebookTarget='occult_residue'}
 elseif($action-eq'cast'){$category=if($target-eq'paneled_wall'){'force_against_wall'}elseif($target-in@('writing_desk','chair','bookshelves')){'force_against_furniture'}else{'default'};$mundane=[string]$Session.Content.Polish.unsupported_action_responses.$category;$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 elseif($actor-eq'Guillermo'-and$target-eq'large_painting'){$engine=Resolve-StructuredIntent -State $s -Intent $Intent -Skill Investigation -DC 10 -FixedRoll $(if($null-ne$roll){$roll}else{11}) -Events @() -Visible @('large painting');$degree=$engine.Resolution.Degree;if($degree-in@('Success','Exceptional Success')){$Session.SafeDiscovered=$true;$events.Add('Guillermo climbs the frame, tugs it aside, and points urgently at the safe.')}else{$events.Add('The frame knocks against the wall; Guillermo retreats to the desk.');Add-GuillermoIncident $s "painting_$($s.Time.Turn)" failure 'Guillermo knocked the painting and retreated.' 2|Out-Null}}
 elseif($actor-eq'Guillermo'-and$target-eq'bookshelves'){$Session.ReferentStates['bookshelf_gap']='visible';$events.Add('Guillermo examines the shelves and taps an empty gap where a volume was recently removed; the gap does not identify the missing book.');$classification='MEANINGFUL';$notebookTarget='bookshelves'}
 elseif($target-eq'large_painting'-and$action-in@('examine','search','investigate','manipulate')){if($Session.SafeDiscovered){$mundane=Get-SliceMundaneResult $Session $target $action $method;$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}else{$Session.SafeDiscovered=$true;$events.Add('The painting shifts, exposing a fixed iron safe behind it.');$notebookTarget='wall_safe'}}
 elseif($target-eq'painting_frame'-and$action-in@('examine','search','investigate','manipulate')){$Session.SafeDiscovered=$true;$events.Add('The painting frame shifts with the canvas, exposing a fixed iron safe behind it.');$notebookTarget='wall_safe'}
 elseif($target-eq'paneled_wall'-and$action-in@('examine','search','investigate')){$Session.SafeDiscovered=$true;$events.Add('A shallow mismatch in the paneling leads behind the painting, where a fixed iron safe is concealed.');$notebookTarget='wall_safe'}
 elseif($target-eq'study_room'){$Session.ReferentStates['bloodstain']='visible';$Session.ReferentStates['scorch_marks']='visible';$events.Add('Rain traces the window. A scratched writing desk scattered with papers faces a cold hearth marked by unusual dark patterns; beside a rumpled rug lies a dark discoloration, while a large painting hangs slightly askew.')}
 elseif(-not($target-eq'receipt'-and$Intent.PSObject.Properties['Purpose']-and$Intent.Purpose)-and($action-eq'read'-or$method-in@('look_under','smell','touch','stare','knock')-or$target-eq'window_latch'-or($target-eq'guillermo'-and$action-eq'speak'))-and($mundane=Get-SliceMundaneResult $Session $target $action $method)){$events.Add($mundane);$classification='MUNDANE';$tone=if($target-eq'guillermo'){'guillermo_comic'}else{'dry_humor_allowed'}}
 elseif($target-in@('rug','bloodstain') -and $action-in@('examine','search','investigate','manipulate')){$Session.ReferentStates['bloodstain']='visible';$passive=Invoke-SliceClue $Session bloodstain Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent bloodstain Investigation $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The pattern yields nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$events.Add('The dark mark remains visible, but yields no further certainty.')};$notebookTarget='bloodstain'}
 elseif($target-in@('fireplace','scorch_marks') -and $action-in@('examine','search','investigate')){$Session.ReferentStates['scorch_marks']='visible';$passive=Invoke-SliceClue $Session scorch_marks Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent scorch_marks Occult $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The pattern yields nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$events.Add('The scorched stone remains unexplained.')};$notebookTarget='scorch_marks'}
 elseif($target-in@('writing_desk','rope_fibers')-and$action-in@('examine','search','investigate')){$passive=Invoke-SliceClue $Session rope_fibers Awareness 10;$new=@($passive.NewFacts);if($action-eq'investigate'){$active=Invoke-SliceActiveClueCheck $Session $Intent rope_fibers Investigation $FixedRoll;$activeCheck=$active.Check;$new+=@($active.NewFacts);if($active.Repeated){$events.Add('The fibers yield nothing further under the same approach.');$classification='MUNDANE'};$degree=if($activeCheck){$activeCheck.Outcome}else{'resolved'}};if($new.Count){$events.Add($new[-1])}elseif(-not$events.Count){$mundane=Get-SliceMundaneResult $Session writing_desk $action $(if($method){$method}else{'repeat'});$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'};$notebookTarget='rope_fibers'}
 elseif($target-eq'receipt'-and$Intent.PSObject.Properties['Purpose']-and$Intent.Purpose){$mundane='The receipts identify ink and a costly lunch, but contain no address, itinerary, or reliable evidence of Callum''s recent whereabouts.';$events.Add($mundane);$classification='MUNDANE';$tone='neutral'}
 elseif($target-eq'bookshelf_gap'){$events.Add('The shelf wear confirms that a volume was removed recently, but does not reliably establish its size, title, or present location.');$classification='MEANINGFUL';$notebookTarget='bookshelves'}
 elseif($target-eq'bookshelves'){$Session.ReferentStates['bookshelf_gap']='visible';$mundane=Get-SliceMundaneResult $Session bookshelves $action stare;if(-not$mundane){$mundane='Most volumes are ordinary reference works; one empty gap shows recent use but does not identify the missing book.'};$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 elseif($target-in@('wall_safe','safe_dial','safe_door')-and$action-in@('open','unlock','use','investigate','manipulate')){if(-not$Session.SafeDiscovered){$accepted=$false;$reason='No safe is visible.'}else{$useCrowbar=([string]$Intent.Method-match'crowbar|pry');$hasCombination=$s.Notebook.Clues.Contains('callum_symbol');$effective=if($null-ne$roll){[int]$roll}else{if($useCrowbar){8}elseif($hasCombination){16}else{12}};$dc=15;$total=$effective+$s.Player.Skills.Finesse;if($hasCombination-and-not$useCrowbar){$total+=5};if($total-ge$dc){$Session.SafeOpen=$true;$events.Add('The safe opens, revealing a partially burned note.');$degree=if($useCrowbar){'Setback'}else{'Success'};if($useCrowbar){$events.Add('The crowbar bends and the metal door shrieks loudly.')}}elseif($useCrowbar-and$total-ge10){$Session.SafeOpen=$true;$events.Add('The safe door tears open, but the crowbar bends and the crash echoes onto the landing.');$degree='Setback'}else{$events.Add('The lock resists, and the attempt produces a sharp metallic click.');$degree='Failure';Add-GameTime $s 2 1}}}
 elseif($target-eq'burned_note'-and$action-in@('take','examine','search')){if(-not$Session.SafeOpen){$accepted=$false;$reason='The note is not accessible.'}else{Move-InventoryItem $s burned_note Armand;$Session.LeadRecovered=$true;Invoke-SliceClue $Session external_lead Investigation 10|Out-Null;$events.Add($Session.Content.Slice.lead_fact);$events.Add('The lead points beyond the house, without identifying who took Callum.');$degree='Success';$notebookTarget='external_lead'}}
 elseif($action-eq'wait'){$events.Add('Rain ticks against the window while the disturbed room remains still.');Add-GameTime $s 1 1}
 elseif($target-and$s.Items.Contains($target)){$mundane="The $($s.Items[$target].DisplayName) permits the harmless experiment, but reveals no new evidence.";$events.Add($mundane);$classification='MUNDANE';$tone='dry_humor_allowed'}
 else{$accepted=$false;$reason='You do not see anything matching that description here.'}
 if(-not$accepted){return [pscustomobject]@{Accepted=$false;Reason=$reason;Degree='ENGINE_REJECTED';Classification='IMPOSSIBLE';Check=$null;Events=@();Handoff=$null;NotebookTarget=$notebookTarget}}
 if($action-notin@('wait','move')-and$events.Count){Add-GameTime $s 1 1};$Session.RecentReferents=@($target|Where-Object{$_});$visible=@((Get-SlicePlayerState $Session).visible_objects);$resolution=[pscustomobject]@{Degree=$degree};$safeIntent=[pscustomobject]@{Actor=$actor;Action=$action;Target=$(if($s.Items.Contains($target)){$s.Items[$target].DisplayName}else{$target});Method=$Intent.Method;Purpose=$(if($Intent.PSObject.Properties['Purpose']){$Intent.Purpose}else{$null})};$entries=Get-NotebookRelevance $s $null $notebookTarget @($target) @() ([int]$Session.Content.Polish.relevance.max_entries);$known=@(ConvertTo-NarratorNotebookEntries $entries|Where-Object{$_});$authorized=Get-SliceInterpretationContext $Session;$affordances=@($visible)+@($authorized.Entities|ForEach-Object{$_.DisplayName})+@($authorized.Entities|ForEach-Object{$_.Aliases})+@($s.Player.Inventory|ForEach-Object{$s.Items[$_].DisplayName})+@($events);$handoff=New-NarratorHandoff -Intent $safeIntent -Resolution $resolution -PostActionState ([pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;lead_recovered=$Session.LeadRecovered}) -Events @($events) -Visible $visible -NotebookEntries $known -NewThisTurn @($events) -KnownContext $known -MundaneResult $mundane -Tone $tone -SupportedAffordances $affordances
 if(-not$Session.HintDelivered-and$s.Notebook.Clues.Contains('bloodstain')-and$s.Notebook.Clues.Contains('rope_fibers')-and-not$Session.SafeDiscovered){$Session.HintDelivered=$true;$hint='Guillermo looks at Armand, looks at the large painting, then looks back at Armand. He repeats the gesture once.';$handoff.Events+=@($hint);$handoff.NewThisTurn+=@($hint)}
 [pscustomobject]@{Accepted=$true;Reason=$null;Degree=$degree;Classification=$classification;Check=$activeCheck;Events=@($handoff.Events);Handoff=$handoff;NotebookTarget=$notebookTarget}
}
function Get-SafeFallbackNarration {param($Resolution)if($Resolution.Events.Count){$text=@($Resolution.Events)-join' ';$text=$text-replace'\bArmand returns\b','You return';$text=$text-replace'\bArmand steps\b','You step';$text=$text-replace'\bArmand\b','You';return $text};'The attempt changes nothing you can presently observe.'}
function Test-SliceNarrationGrounding {
 param($Session,$Resolution,[string]$Text,$BaseValidation)$errors=[Collections.Generic.List[string]]::new()
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,60}\b(open|opened|ajar|contents? (?:are |is )?visible)\b'){$errors.Add('Narration contradicts closed safe state.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,80}\b(unlocked|lock (?:has been |was )?(?:picked|opened))\b'){$errors.Add('Narration invents successful safe access.')}
 if($Session.SafeDiscovered-and$Text-match'(?i)\bsafe\b.{0,80}\b(was not there before|wasn.t there before|has appeared|newly appeared)\b'){$errors.Add('Narration invents a safe continuity change.')}
 if(-not$Session.SafeDiscovered-and$Text-match'(?i)\b(concealed |wall )?safe\b'){$errors.Add('Narration reveals the hidden safe.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\b(partially burned|burned note|Blackthorn Station)\b'){$errors.Add('Narration reveals inaccessible safe contents.')}
 if($Text-match'(?i)\bnotebook (?:lies|rests|sits|is)\b'){$errors.Add('Narration invents a physical Notebook object.')}
 if((@($Resolution.Events)-join' ')-match'(?i)\b(discoloration|blood|fibers?|scorch|residue)\b'-and$Text-match'(?i)\b(find|see|shows?) (?:absolutely )?(?:nothing|no sign)\b'){$errors.Add('Narration contradicts positive evidence.')}
 if($Text-match'(?i)\bstudy door\b.{0,30}\blocked\b'){$errors.Add('Narration invents a locked door state.')}
 if((@($Resolution.Events)-join' ')-match'(?i)steps onto the upstairs landing'-and$Text-match'(?i)door remains closed|cannot (?:open|pass|enter).{0,20}door'){$errors.Add('Narration contradicts successful movement through the study door.')}
 if($Text-match'(?i)\byou (?:do not|don.t) (?:know|understand|realize|believe)\b'){$errors.Add('Narration assigns player knowledge or belief.')}
 $support=(@($Resolution.Handoff.SupportedAffordances)+@($Resolution.Events)+@($Resolution.Handoff.MundaneResult)-join' ').ToLowerInvariant();foreach($noun in @('drawer','letter','cabinet','box','key','knife','chair','note','receipt','correspondence','gap','dial','frame')){if($Text-match("(?i)\b"+[regex]::Escape($noun)+"s?\b")-and$support-notmatch("(?i)\b"+[regex]::Escape($noun)+"s?\b")){$errors.Add("Narration introduces unsupported physical affordance: $noun.")}}
 if($Resolution.Handoff.Attempt.Target-eq'study'-and$Text-match'(?i)\b(dried blood|hemp cordage|magical discharge|occult (?:energy|cause)|inconsistent with an ordinary fire)\b'){$errors.Add('Narration prematurely interprets an overview observation.')}
 foreach($detail in @('wife','husband','woman','clerk')){if($Text-match("(?i)\b"+[regex]::Escape($detail)+"\b")-and$support-notmatch("(?i)\b"+[regex]::Escape($detail)+"\b")){$errors.Add("Narration introduces unsupported consequential detail: $detail.")}}
 $newText=@($Resolution.Handoff.NewThisTurn)-join' ';$notebookFacts=@($Session.State.Notebook.Clues.Values|ForEach-Object{$_.known_facts})-join' ';$knownText=(@($Resolution.Handoff.KnownContext)-join' ')+' '+$notebookFacts;$currentTarget=[string]$Resolution.Handoff.Attempt.Target;$knownRules=@(@{marker='blood';targets='bloodstain|dark discoloration|rug'},@{marker='fibers?';targets='rope_fibers|rope fibers|writing desk'},@{marker='three-pointed crown';targets='safe|dial|writing desk'},@{marker='magical residue';targets='scorch|fireplace|hearth'},@{marker='Blackthorn Station';targets='note|burned_note'});foreach($rule in $knownRules){if($knownText-match("(?i)"+$rule.marker)-and$newText-notmatch("(?i)"+$rule.marker)-and$Text-match("(?i)"+$rule.marker)-and$currentTarget-notmatch("(?i)"+$rule.targets)){$errors.Add("Narration unnecessarily restates known context: $($rule.marker).")}}
 [pscustomobject]@{Passed=($BaseValidation.Passed-and$errors.Count-eq0);Lexical=$BaseValidation.Lexical;Structural=$BaseValidation.Structural;GroundingErrors=@($errors);RawOutput=$Text;ValidatedOutput=$(if($BaseValidation.Passed-and$errors.Count-eq0){$Text}else{$null})}
}
function Invoke-SliceNarration {
 param($Session,$Resolution,[scriptblock]$NarratorBackend,[int]$MaxAttempts=2,[string]$Root=(Split-Path -Parent $PSScriptRoot))$case=Convert-HandoffToNarrationCase $Resolution.Handoff $Session.State.Player.Location $Session.State.Time.CurrentCaseTime.ToString('h:mm tt') rain;$packet=ConvertTo-NarrationPacket $case;$examples=@(Read-NarrationExemplars (Join-Path $Root 'exemplars/playability_polish_exemplars.json') -ExpectedCount 7);$prompt=Build-NarrationPrompt $packet facts $examples;$raws=@();$validations=@();$lastValidation=$null;$elapsed=0.0
 for($i=0;$i-lt$MaxAttempts;$i++){$watch=[Diagnostics.Stopwatch]::StartNew();if($null-ne$NarratorBackend){$g=&$NarratorBackend $prompt $i}else{$work=Join-Path $Root 'eval/.work';New-Item -ItemType Directory -Force $work|Out-Null;$path=Join-Path $work "slice_narrator_$([guid]::NewGuid().ToString('N')).txt";$prompt|Set-Content -NoNewline -Encoding utf8 $path;$cfg=Join-Path $Root 'config.json';$g=Invoke-CommaGeneration $path $cfg -Seed (12000+$Session.State.Time.Turn+$i) -Temperature .15 -MaxTokens 160};$watch.Stop();$elapsed+=$watch.Elapsed.TotalSeconds;$raw=[string]$(if($g.PSObject.Properties['Text']){$g.Text}else{$g.RawOutput});$raws+=$raw;$text='You '+(($raw-replace'(?s)\s*FACTS\s*$','').TrimStart());$base=Test-NarrationOutput $text @($Session.Content.Slice.hidden_truth) 120 $Resolution.Handoff.Attempt.Actor;$lastValidation=Test-SliceNarrationGrounding $Session $Resolution $text $base;$validations+=$lastValidation;if($lastValidation.Passed){return [pscustomobject]@{Text=$text;RawOutputs=$raws;Validations=$validations;Validation=$lastValidation;RetryOccurred=($i-gt0);FallbackUsed=$false;ElapsedSeconds=$elapsed;PromptCharacters=$prompt.Length;PromptBytes=[Text.Encoding]::UTF8.GetByteCount($prompt)}}}
 [pscustomobject]@{Text=(Get-SafeFallbackNarration $Resolution);RawOutputs=$raws;Validations=$validations;Validation=$lastValidation;RetryOccurred=($MaxAttempts-gt1);FallbackUsed=$true;ElapsedSeconds=$elapsed;PromptCharacters=$prompt.Length;PromptBytes=[Text.Encoding]::UTF8.GetByteCount($prompt)}
}

Export-ModuleMember -Function Read-SliceContent,New-CallumStudySession,Get-SlicePlayerState,Get-SliceInterpretationContext,Invoke-SliceInterpretation,Resolve-SliceIntent,Format-SliceRollFeedback,Invoke-SliceNarration,Get-SafeFallbackNarration,Test-SliceNarrationGrounding
