Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'InterpreterContext.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentInterpreter.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'IntentSchema.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CoreEngine.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarratorHandoff.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPacket.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationPrompt.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'NarrationValidation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'CommaHarness.psm1') -Force
# Restore public commands after nested module imports replace dependency instances.
Import-Module (Join-Path $PSScriptRoot 'GameState.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Clues.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'Notebook.psm1') -Force -DisableNameChecking
Import-Module (Join-Path $PSScriptRoot 'IncidentLedger.psm1') -Force

function Read-SliceContent {param([string]$Root=(Split-Path -Parent $PSScriptRoot))$dir=Join-Path $Root 'content/callum_study';[pscustomobject]@{Locations=Get-Content -Raw (Join-Path $dir 'location.json')|ConvertFrom-Json;Objects=Get-Content -Raw (Join-Path $dir 'objects.json')|ConvertFrom-Json;Clues=Get-Content -Raw (Join-Path $dir 'clues.json')|ConvertFrom-Json;Slice=Get-Content -Raw (Join-Path $dir 'slice.json')|ConvertFrom-Json}}
function New-CallumStudySession {
 param([string]$Root=(Split-Path -Parent $PSScriptRoot))$content=Read-SliceContent $Root;$state=New-GameState
 foreach($loc in $content.Locations.locations){Add-LocationState -State $state -Id $loc.id -VisibleObjects @($loc.visible_objects) -Exits @($loc.exits) -DisplayName $loc.display_name}
 foreach($obj in $content.Objects.objects){$parts=if($obj.PSObject.Properties['parts']){@($obj.parts)}else{@()};Add-ItemState -State $state -Id $obj.id -Location $obj.location -Owner $(if($obj.PSObject.Properties['owner']){$obj.owner}else{$null}) -DisplayName $obj.name -Aliases @($obj.aliases) -InteractableParts $parts}
 foreach($clue in $content.Clues.clues){$tiers=@($clue.tiers|ForEach-Object{[pscustomobject]@{DC=[int]$_.dc;Skill=[string]$_.skill;Fact=[string]$_.fact}});Add-ClueState -State $state -Id $clue.id -Location $clue.location -Tiers $tiers -DisplayName $clue.name -RelatedEntityIds @($clue.related)}
 $state.Player.Location=$content.Slice.start_location;$state.Guillermo.Location=$content.Slice.start_location;Visit-NotebookLocation $state callum_study "Callum's Study" @('a disturbed Victorian study lit by gaslight')|Out-Null;Add-NotebookCharacter $state callum 'Callum' callum_study @('Callum is a missing occult researcher and investigator.') @('Armand came to investigate his disappearance.')|Out-Null
 [pscustomobject]@{Id=[guid]::NewGuid().ToString('N');State=$state;Content=$content;SafeDiscovered=$false;SafeOpen=$false;LeadRecovered=$false;HintDelivered=$false;VisitCounts=[ordered]@{callum_study=1;landing=0};RecentReferents=@();History=[Collections.Generic.List[string]]::new();CreatedUtc=[datetime]::UtcNow}
}
function Get-SlicePlayerState {
 param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$visible=@($loc.VisibleObjects|Where-Object{$_-ne'wall_safe'-and$_-ne'burned_note'});if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$visible+='wall_safe'};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$visible+='burned_note'}
 [pscustomobject]@{session_id=$Session.Id;location=[pscustomobject]@{id=$loc.Id;name=$loc.DisplayName};time=$state.Time.CurrentCaseTime.ToString('h:mm tt');visible_objects=@($visible|ForEach-Object{$state.Items[$_].DisplayName});guillermo=[pscustomobject]@{available=($state.Guillermo.Available-and$state.Guillermo.Alive);communication_tier=$state.Guillermo.CommunicationTier};slice_state=[pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;ending_reached=$Session.LeadRecovered;ending_title=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_title}else{$null});ending_text=$(if($Session.LeadRecovered){$Session.Content.Slice.ending_text}else{$null})};notebook=Get-PlayerFacingNotebook $state}
}
function Get-SliceInterpretationContext {param($Session)$state=$Session.State;$loc=$state.Locations[$state.Player.Location];$original=@($loc.VisibleObjects);try{if($Session.SafeDiscovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('wall_safe')};if($Session.SafeOpen-and-not$Session.LeadRecovered-and$state.Player.Location-eq'callum_study'){$loc.VisibleObjects+=@('burned_note')};New-InterpretationContext $state $Session.RecentReferents}finally{$loc.VisibleObjects=$original}}
function Get-ClueDelta {param($Before,$After)$old=@{};foreach($c in @($Before.Clues.PSObject.Properties.Value)){$old[$c.clue_id]=@($c.known_facts).Count};$changes=@();foreach($c in @($After.Clues.PSObject.Properties.Value)){if(-not$old.ContainsKey($c.clue_id)-or@($c.known_facts).Count-gt$old[$c.clue_id]){$changes+=$c}};@($changes)}
function Invoke-SliceClue {param($Session,[string]$ClueId,[string]$Skill,[int]$Score)$result=Resolve-ClueInterpretation $Session.State $ClueId $Skill $Score;if($result.NewFacts.Count){Visit-NotebookLocation $Session.State callum_study "Callum's Study" @() @($ClueId)|Out-Null};$result}
function Resolve-SliceIntent {
 [CmdletBinding()]param($Session,$Intent,[Nullable[int]]$FixedRoll)
 $s=$Session.State;$target=[string]$Intent.Target;$action=[string]$Intent.Action;$actor=[string]$Intent.Actor;$events=[Collections.Generic.List[string]]::new();$degree='resolved';$skill='Investigation';$dc=10;$roll=$FixedRoll;$accepted=$true;$reason=$null;$notebookTarget=$target
 if($action-eq'move'-or($action-eq'cast'-and$Intent.Spell-eq'misty_step')){if($target-in@('landing','study_door')-and$s.Player.Location-eq'callum_study'){$s.Player.Location='landing';$s.Guillermo.Location='landing';$Session.VisitCounts.landing++;Visit-NotebookLocation $s landing 'Upstairs Landing' @('a narrow landing outside the study')|Out-Null;$events.Add('Armand steps onto the upstairs landing.')}elseif($target-in@('callum_study','study_entrance')-and$s.Player.Location-eq'landing'){$s.Player.Location='callum_study';$s.Guillermo.Location='callum_study';$Session.VisitCounts.callum_study++;$events.Add('Armand returns to the changed study.')}elseif($Intent.Spell-eq'misty_step'-and$target-eq'wall_safe'){$accepted=$false;$reason='You cannot see a destination inside the opaque safe.'}else{$accepted=$false;$reason='That route does not lead anywhere accessible.'}}
 elseif($action-eq'cast'-and$Intent.Spell-eq'detect_magic'){$events.Add('A faint magical presence clings to the scorch marks, but its meaning remains unclear.');Invoke-SliceClue $Session occult_residue Occult 10|Out-Null;$notebookTarget='occult_residue'}
 elseif($actor-eq'Guillermo'-and$target-eq'large_painting'){$engine=Resolve-StructuredIntent -State $s -Intent $Intent -Skill Investigation -DC 10 -FixedRoll $(if($null-ne$roll){$roll}else{11}) -Events @() -Visible @('large painting');$degree=$engine.Resolution.Degree;if($degree-in@('Success','Exceptional Success')){$Session.SafeDiscovered=$true;$events.Add('Guillermo climbs the frame, tugs it aside, and points urgently at the safe.')}else{$events.Add('The frame knocks against the wall; Guillermo retreats to the desk.');Add-GuillermoIncident $s "painting_$($s.Time.Turn)" failure 'Guillermo knocked the painting and retreated.' 2|Out-Null}}
 elseif($target-in@('large_painting','paneled_wall')-and$action-in@('examine','search','investigate')){$Session.SafeDiscovered=$true;$events.Add('The painting shifts, exposing a fixed iron safe behind it.');$notebookTarget='wall_safe'}
 elseif($target-eq'study_room'){$events.Add('The writing desk, cold hearth, rumpled rug, large painting, bookshelves, rain-streaked window, and paneled walls show signs of disturbance.')}
 elseif($target-eq'rug' -and $action-in@('examine','search','investigate')){Invoke-SliceClue $Session bloodstain Awareness 10|Out-Null;$score=if($null-ne$roll){[int]$roll+4}else{15};$clue=Invoke-SliceClue $Session bloodstain Investigation $score;$events.Add($(if($clue.NewFacts.Count){$clue.NewFacts[-1]}else{'The dark mark remains visible, but yields no further certainty.'}));$degree=if($clue.NewFacts.Count){'Success'}else{'Failure'};$notebookTarget='bloodstain'}
 elseif($target-eq'fireplace' -and $action-in@('examine','search','investigate')){Invoke-SliceClue $Session scorch_marks Awareness 10|Out-Null;$score=if($null-ne$roll){[int]$roll+4}else{15};$clue=Invoke-SliceClue $Session scorch_marks Occult $score;$events.Add($(if($clue.NewFacts.Count){$clue.NewFacts[-1]}else{'The scorched stone remains unexplained.'}));$degree=if($clue.NewFacts.Count){'Success'}else{'Failure'};$notebookTarget='scorch_marks'}
 elseif($target-eq'writing_desk'-and$action-in@('examine','search','investigate')){$score=if($null-ne$roll){[int]$roll+4}else{15};$clueId=if($action-eq'search'){'callum_symbol'}else{'rope_fibers'};if($clueId-eq'rope_fibers'){Invoke-SliceClue $Session rope_fibers Awareness 10|Out-Null};$clue=Invoke-SliceClue $Session $clueId Investigation $score;$events.Add($(if($clue.NewFacts.Count){$clue.NewFacts[-1]}else{'The desk holds ordinary receipts and correspondence, but nothing consequential appears.'}));$degree=if($clue.NewFacts.Count){'Success'}else{'Failure'};$notebookTarget=$clueId}
 elseif($target-eq'bookshelves'){$events.Add('Most volumes are ordinary reference works; one gap shows recent use, but offers no consequential evidence.')}
 elseif($target-eq'wall_safe'-and$action-in@('open','unlock','use','investigate')){if(-not$Session.SafeDiscovered){$accepted=$false;$reason='No safe is visible.'}else{$useCrowbar=([string]$Intent.Method-match'crowbar|pry');$hasCombination=$s.Notebook.Clues.Contains('callum_symbol');$effective=if($null-ne$roll){[int]$roll}else{if($useCrowbar){8}elseif($hasCombination){16}else{12}};$dc=15;$total=$effective+$s.Player.Skills.Finesse;if($hasCombination-and-not$useCrowbar){$total+=5};if($total-ge$dc){$Session.SafeOpen=$true;$events.Add('The safe opens, revealing a partially burned note.');$degree=if($useCrowbar){'Setback'}else{'Success'};if($useCrowbar){$events.Add('The crowbar bends and the metal door shrieks loudly.')}}elseif($useCrowbar-and$total-ge10){$Session.SafeOpen=$true;$events.Add('The safe door tears open, but the crowbar bends and the crash echoes onto the landing.');$degree='Setback'}else{$events.Add('The lock resists, and the attempt produces a sharp metallic click.');$degree='Failure';Add-GameTime $s 2 1}}}
 elseif($target-eq'burned_note'-and$action-in@('take','examine','search')){if(-not$Session.SafeOpen){$accepted=$false;$reason='The note is not accessible.'}else{Move-InventoryItem $s burned_note Armand;$Session.LeadRecovered=$true;Invoke-SliceClue $Session external_lead Investigation 10|Out-Null;$events.Add($Session.Content.Slice.lead_fact);$events.Add('The lead points beyond the house, without identifying who took Callum.');$degree='Success';$notebookTarget='external_lead'}}
 elseif($action-eq'wait'){$events.Add('Rain ticks against the window while the disturbed room remains still.');Add-GameTime $s 1 1}
 else{$accepted=$false;$reason='That action has no supported consequence in this prototype.'}
 if(-not$accepted){return [pscustomobject]@{Accepted=$false;Reason=$reason;Degree='ENGINE_REJECTED';Events=@();Handoff=$null;NotebookTarget=$notebookTarget}}
 if($action-notin@('wait','move')-and$events.Count){Add-GameTime $s 1 1};$visible=@((Get-SlicePlayerState $Session).visible_objects);$resolution=[pscustomobject]@{Degree=$degree};$safeIntent=[pscustomobject]@{Actor=$actor;Action=$action;Target=$(if($s.Items.Contains($target)){$s.Items[$target].DisplayName}else{$target});Method=$Intent.Method};$entries=Get-NotebookRelevance $s $s.Player.Location $notebookTarget @($target) @() 4;$handoff=New-NarratorHandoff $safeIntent $resolution ([pscustomobject]@{safe_discovered=$Session.SafeDiscovered;safe_open=$Session.SafeOpen;lead_recovered=$Session.LeadRecovered}) @($events) $visible @() @() (ConvertTo-NarratorNotebookEntries $entries)
 if(-not$Session.HintDelivered-and$s.Notebook.Clues.Contains('bloodstain')-and$s.Notebook.Clues.Contains('rope_fibers')-and-not$Session.SafeDiscovered){$Session.HintDelivered=$true;$handoff.Events+=@('Guillermo looks at Armand, looks at the large painting, then looks back at Armand. He repeats the gesture once.')}
 [pscustomobject]@{Accepted=$true;Reason=$null;Degree=$degree;Events=@($handoff.Events);Handoff=$handoff;NotebookTarget=$notebookTarget}
}
function Get-SafeFallbackNarration {param($Resolution)if($Resolution.Events.Count){$text=@($Resolution.Events)-join' ';$text=$text-replace'\bArmand returns\b','You return';$text=$text-replace'\bArmand steps\b','You step';$text=$text-replace'\bArmand\b','You';return $text};'The attempt changes nothing you can presently observe.'}
function Test-SliceNarrationGrounding {
 param($Session,$Resolution,[string]$Text,$BaseValidation)$errors=[Collections.Generic.List[string]]::new()
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,60}\b(open|opened|ajar|contents? (?:are |is )?visible)\b'){$errors.Add('Narration contradicts closed safe state.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\bsafe\b.{0,80}\b(unlocked|lock (?:has been |was )?(?:picked|opened))\b'){$errors.Add('Narration invents successful safe access.')}
 if($Session.SafeDiscovered-and$Text-match'(?i)\bsafe\b.{0,80}\b(was not there before|wasn.t there before|has appeared|newly appeared)\b'){$errors.Add('Narration invents a safe continuity change.')}
 if(-not$Session.SafeDiscovered-and$Text-match'(?i)\b(concealed |wall )?safe\b'){$errors.Add('Narration reveals the hidden safe.')}
 if(-not$Session.SafeOpen-and$Text-match'(?i)\b(partially burned|burned note|Blackthorn Station)\b'){$errors.Add('Narration reveals inaccessible safe contents.')}
 if($Text-match'(?i)\bnotebook (?:lies|rests|sits|is)\b'){$errors.Add('Narration invents a physical Notebook object.')}
 if((@($Resolution.Events)-join' ')-match'(?i)\b(discoloration|blood|fibers?|scorch|residue)\b'-and$Text-match'(?i)\b(find|see|shows?) (?:absolutely )?(?:nothing|no sign)\b'){$errors.Add('Narration contradicts positive evidence.')}
 if($Text-match'(?i)\bstudy door\b.{0,30}\blocked\b'){$errors.Add('Narration invents a locked door state.')}
 if($Text-match'(?i)\byou (?:do not|don.t) (?:know|understand|realize|believe)\b'){$errors.Add('Narration assigns player knowledge or belief.')}
 [pscustomobject]@{Passed=($BaseValidation.Passed-and$errors.Count-eq0);Lexical=$BaseValidation.Lexical;Structural=$BaseValidation.Structural;GroundingErrors=@($errors);RawOutput=$Text;ValidatedOutput=$(if($BaseValidation.Passed-and$errors.Count-eq0){$Text}else{$null})}
}
function Invoke-SliceNarration {
 param($Session,$Resolution,[scriptblock]$NarratorBackend,[int]$MaxAttempts=2,[string]$Root=(Split-Path -Parent $PSScriptRoot))$case=Convert-HandoffToNarrationCase $Resolution.Handoff $Session.State.Player.Location $Session.State.Time.CurrentCaseTime.ToString('h:mm tt') rain;$packet=ConvertTo-NarrationPacket $case;$examples=@(Read-NarrationExemplars (Join-Path $Root 'exemplars/narration_exemplars.json'))+@(Read-NarrationExemplars (Join-Path $Root 'exemplars/grounding_retry_exemplars.json') -ExpectedCount 3);$prompt=Build-NarrationPrompt $packet facts $examples;$raws=@();$lastValidation=$null;$elapsed=0.0
 for($i=0;$i-lt$MaxAttempts;$i++){$watch=[Diagnostics.Stopwatch]::StartNew();if($null-ne$NarratorBackend){$g=&$NarratorBackend $prompt $i}else{$work=Join-Path $Root 'eval/.work';New-Item -ItemType Directory -Force $work|Out-Null;$path=Join-Path $work "slice_narrator_$([guid]::NewGuid().ToString('N')).txt";$prompt|Set-Content -NoNewline -Encoding utf8 $path;$cfg=Join-Path $Root 'config.json';$g=Invoke-CommaGeneration $path $cfg -Seed (12000+$Session.State.Time.Turn+$i) -Temperature .15 -MaxTokens 160};$watch.Stop();$elapsed+=$watch.Elapsed.TotalSeconds;$raw=[string]$(if($g.PSObject.Properties['Text']){$g.Text}else{$g.RawOutput});$raws+=$raw;$text='You '+(($raw-replace'(?s)\s*FACTS\s*$','').TrimStart());$base=Test-NarrationOutput $text @($Session.Content.Slice.hidden_truth) 120 $Resolution.Handoff.Attempt.Actor;$lastValidation=Test-SliceNarrationGrounding $Session $Resolution $text $base;if($lastValidation.Passed){return [pscustomobject]@{Text=$text;RawOutputs=$raws;Validation=$lastValidation;RetryOccurred=($i-gt0);FallbackUsed=$false;ElapsedSeconds=$elapsed}}}
 [pscustomobject]@{Text=(Get-SafeFallbackNarration $Resolution);RawOutputs=$raws;Validation=$lastValidation;RetryOccurred=($MaxAttempts-gt1);FallbackUsed=$true;ElapsedSeconds=$elapsed}
}

Export-ModuleMember -Function Read-SliceContent,New-CallumStudySession,Get-SlicePlayerState,Get-SliceInterpretationContext,Resolve-SliceIntent,Invoke-SliceNarration,Get-SafeFallbackNarration,Test-SliceNarrationGrounding
